# Analysis for the deepeval metrics

In [1]:
gold_source = (
    "/home/baptvit/Documents/github/graphrag-on-fhir/evaluations/data/gold/deepeval/"
)

In [2]:
import glob
import os

import pandas as pd

all_files = glob.glob(os.path.join(gold_source, "*.csv"))

all_dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df["consumer_id"] = file.split("/")[-1]
    all_dfs.append(df)


df_gold = pd.concat(all_dfs, ignore_index=True)

In [3]:
df_gold.columns

Index(['consumer_id', 'test_name', 'success', 'metric_name', 'threshold',
       'metric_success', 'score', 'reason', 'strict_mode', 'evaluation_model',
       'error', 'evaluation_cost', 'verbose_logs', 'conversational',
       'multimodal', 'input', 'actual_output', 'expected_output', 'context',
       'retrieval_context', 'Unnamed: 0.8', 'Unnamed: 0.7', 'Unnamed: 0.6',
       'Unnamed: 0.5', 'Unnamed: 0.4', 'Unnamed: 0.3', 'Unnamed: 0.2',
       'Unnamed: 0.1', 'Unnamed: 0', 'delete'],
      dtype='object')

## Filter only the L0 and L1 results for BRACIS

In [4]:
import numpy as np

In [5]:
test_name = np.unique(df_gold[["test_name"]].values)

In [6]:
test_name[0]

'Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_0_hop'

In [7]:
list_search = list(set([expertiment.split(":")[-1] for expertiment in test_name]))

In [8]:
list_search

['lexical_search_2_hop',
 'lexical_search_1_hop',
 'similarity_search_0_hop',
 'similarity_search_1_hop',
 'lexical_search_0_hop']

In [9]:
df_gold = df_gold.loc[df_gold["test_name"].str.contains("lexical_search_1_hop") | df_gold["test_name"].str.contains("lexical_search_0_hop")]

In [10]:
df_gold.head()

,consumer_id,test_name,success,metric_name,threshold,metric_success,score,reason,strict_mode,evaluation_model,...,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,delete
24,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:llama-3-70b-instruct-awq:lexical_search_1_hop,False,Hallucination,0.5,True,0.000000,The score is 0.00 because there are no contrad...,False,Custom Azure OpenAI Model,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:llama-3-70b-instruct-awq:lexical_search_1_hop,False,Answer Relevancy,0.5,True,1.000000,The score is 1.00 because the output is fully ...,False,Custom Azure OpenAI Model,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:llama-3-70b-instruct-awq:lexical_search_1_hop,False,Contextual Relevancy,0.5,False,0.333333,The score is 0.33 because while the context in...,False,Custom Azure OpenAI Model,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q1:llama-3-70b-instruct-awq:lexical_search_1_hop,True,Hallucination,0.5,True,0.000000,The score is 0.00 because the actual output fu...,False,Custom Azure OpenAI Model,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q1:llama-3-70b-instruct-awq:lexical_search_1_hop,True,Answer Relevancy,0.5,True,0.565217,The score is 0.57 because while some parts of ...,False,Custom Azure OpenAI Model,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_gold[df_gold["context"].isna()]

,consumer_id,test_name,success,metric_name,threshold,metric_success,score,reason,strict_mode,evaluation_model,...,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,delete
1549,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q4:gemini-1.5-pro:lexical_search_1_hop,False,Hallucination,0.5,True,0.0,The score is 0.00 because the output aligns wi...,False,Custom Azure OpenAI Model,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN
1550,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q4:gemini-1.5-pro:lexical_search_1_hop,False,Answer Relevancy,0.5,True,1.0,The score is 1.00 because there are no irrelev...,False,Custom Azure OpenAI Model,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,NaN
1551,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:gemini-1.5-pro:lexical_search_1_hop,True,Hallucination,0.5,True,0.0,The score is 0.00 because the actual output fu...,False,Custom Azure OpenAI Model,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN
1552,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:gemini-1.5-pro:lexical_search_1_hop,True,Answer Relevancy,0.5,True,1.0,"The score is 1.00, indicating a perfect releva...",False,Custom Azure OpenAI Model,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,NaN
1553,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:gemini-1.5-pro:lexical_search_1_hop,True,Contextual Relevancy,0.5,True,1.0,The score is 1.00 because the retrieval contex...,False,Custom Azure OpenAI Model,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,NaN
1554,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q7:gemini-1.5-pro:lexical_search_1_hop,False,Hallucination,0.5,True,0.0,The score is 0.00 because the actual output fu...,False,Custom Azure OpenAI Model,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,NaN
1555,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q7:gemini-1.5-pro:lexical_search_1_hop,False,Answer Relevancy,0.5,True,1.0,It appears there is no irrelevant information ...,False,Custom Azure OpenAI Model,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,NaN

In [12]:
df_gold["error"].unique()

array([nan,
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 2982616 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 2934370 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1179389 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1153253 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1179526 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1156312 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1150255 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1127686 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1177756 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1156322 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Error code: 400 - {\'message\': \'Input is too long for requested model.\'}", \'type\': \'invalid_request_error\', \'code\': \'400\'}}',
       'No route',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1297062 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1272904 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 162230 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\', \'callstack\': \'  File "/usr/local/bin/gunicorn", line 8, in <module>\\n    sys.exit(run())\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 66, in run\\n    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 235, in run\\n    super().run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 71, in run\\n    Arbiter(self).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 201, in run\\n    self.manage_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 570, in manage_workers\\n    self.spawn_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 641, in spawn_workers\\n    self.spawn_worker()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker\\n    worker.init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process\\n    super().init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 143, in init_process\\n    self.run()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 107, in run\\n    return asyncio.run(self._serve())\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run\\n    return runner.run(main)\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run\\n    return self._loop.run_until_complete(task)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro\\n    await self.app(scope, receive_or_disconnect, send_no_error)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__\\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app\\n    await app(scope, receive, sender)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__\\n    await self.middleware_stack(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app\\n    await route.handle(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app\\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 75, in wrapped_app\\n    response = await handler(conn, exc)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 82, in _datadog_error_tracking_wrapper\\n    return await call_next(request, exception)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 112, in create_response_from_api_error\\n    return _create_response(\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 51, in _create_response\\n    problem_response = {"message": message, "type": type, "param": param, "code": code, "callstack": "at ".join(traceback.format_stack())}\\n\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 156982 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 140503 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\', \'callstack\': \'  File "/usr/local/bin/gunicorn", line 8, in <module>\\n    sys.exit(run())\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 66, in run\\n    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 235, in run\\n    super().run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 71, in run\\n    Arbiter(self).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 210, in run\\n    self.manage_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 570, in manage_workers\\n    self.spawn_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 641, in spawn_workers\\n    self.spawn_worker()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker\\n    worker.init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process\\n    super().init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 143, in init_process\\n    self.run()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 107, in run\\n    return asyncio.run(self._serve())\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run\\n    return runner.run(main)\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run\\n    return self._loop.run_until_complete(task)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro\\n    await self.app(scope, receive_or_disconnect, send_no_error)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__\\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app\\n    await app(scope, receive, sender)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__\\n    await self.middleware_stack(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app\\n    await route.handle(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app\\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 75, in wrapped_app\\n    response = await handler(conn, exc)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 82, in _datadog_error_tracking_wrapper\\n    return await call_next(request, exception)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 112, in create_response_from_api_error\\n    return _create_response(\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 51, in _create_response\\n    problem_response = {"message": message, "type": type, "param": param, "code": code, "callstack": "at ".join(traceback.format_stack())}\\n\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 135564 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Evaluation LLM outputted an invalid JSON. Please use a better evaluation model.',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 145717 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\', \'callstack\': \'  File "/usr/local/bin/gunicorn", line 8, in <module>\\n    sys.exit(run())\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 66, in run\\n    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 235, in run\\n    super().run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 71, in run\\n    Arbiter(self).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 201, in run\\n    self.manage_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 570, in manage_workers\\n    self.spawn_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 641, in spawn_workers\\n    self.spawn_worker()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker\\n    worker.init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process\\n    super().init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 143, in init_process\\n    self.run()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 107, in run\\n    return asyncio.run(self._serve())\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run\\n    return runner.run(main)\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run\\n    return self._loop.run_until_complete(task)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro\\n    await self.app(scope, receive_or_disconnect, send_no_error)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__\\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app\\n    await app(scope, receive, sender)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__\\n    await self.middleware_stack(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app\\n    await route.handle(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app\\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 75, in wrapped_app\\n    response = await handler(conn, exc)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 82, in _datadog_error_tracking_wrapper\\n    return await call_next(request, exception)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 112, in create_response_from_api_error\\n    return _create_response(\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 51, in _create_response\\n    problem_response = {"message": message, "type": type, "param": param, "code": code, "callstack": "at ".join(traceback.format_stack())}\\n\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 135560 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',

In [13]:
import numpy as np

df_gold = df_gold[df_gold["error"].isna()]
df_gold = df_gold[df_gold["context"].notna()]

In [14]:
df_gold = df_gold.query('not context.str.contains("No data available for this question")')

In [15]:
df_5 = df_gold[
    [
        "consumer_id",
        "test_name",
        "success",
        "metric_name",
        "threshold",
        "metric_success",
        "score",
        "reason",
    ]
].head()

In [16]:
df_5.to_dict()

{'consumer_id': {24: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv',
  25: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv',
  26: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv',
  27: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv',
  28: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv'},
 'test_name': {24: 'Q5:llama-3-70b-instruct-awq:lexical_search_1_hop',
  25: 'Q5:llama-3-70b-instruct-awq:lexical_search_1_hop',
  26: 'Q5:llama-3-70b-instruct-awq:lexical_search_1_hop',
  27: 'Q1:llama-3-70b-instruct-awq:lexical_search_1_hop',
  28: 'Q1:llama-3-70b-instruct-awq:lexical_search_1_hop'},
 'success': {24: False, 25: False, 26: False, 27: True, 28: True},
 'metric_name': {24: 'Hallucination',
  25: 'Answer Relevancy',
  26: 'Contextual Relevancy',
  27: 'Hallucination',
  28: 'Answer Relevancy'},
 'threshold': {24: 0.5, 25: 0.5, 26: 0.5, 27: 0.5, 28: 0.5},
 'metric_success': {24: True, 25: True, 26: False, 27: True, 28: True},
 'score': {24: 0.0,
  25: 1.0,
  26: 0.3333333333333333,
  27: 0.0,
  28: 0.5652173913043478},
 'reason': {24: 'The score is 0.00 because there are no contradictions between the actual output and the context, and all details are factually aligned.',
  25: 'The score is 1.00 because the output is fully relevant and directly addresses the input without any irrelevant statements. Great job staying on point!',
  26: "The score is 0.33 because while the context includes some care plan details such as 'Care Plan for Lifestyle education regarding hypertension' and 'Physiotherapy care plan started on October 31, 2023,' most of the retrieval context focuses on specific event details or conditions that do not summarize the overall care plan history as requested.",
  27: 'The score is 0.00 because the actual output fully aligns with the provided context, with no contradictions or deviations observed.',
  28: 'The score is 0.57 because while some parts of the output may touch on related information, the majority of the statements are irrelevant to the input, focusing on details like prescription dates, prescribers, Medicare coverage, and facility names, which do not directly address the medications or their usage instructions.'}}

In [17]:
# Create DataFrame
df = df_gold

# Create the pivot table
pivot = pd.pivot_table(
    df,
    values=["success", "threshold", "metric_success", "score"],
    index=["consumer_id", "test_name"],
    columns=["metric_name"],
    aggfunc="first",  # Use 'first' to get the value as is since duplicates are unlikely
)

# Optional: Flatten the column multi-index for cleaner display
pivot.columns = ["_".join(col).strip() for col in pivot.columns.values]
pivot.reset_index(inplace=True)

# Display the pivot table
pivot

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,success_Hallucination,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,False,True,1.000000,0.333333,0.0,False,False,False,0.5,0.5,0.5
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.968750,1.000000,0.0,True,True,True,0.5,0.5,0.5
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.956522,1.000000,0.0,True,True,True,0.5,0.5,0.5
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.931034,0.650000,0.0,True,True,True,0.5,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q6:llama-3-70b-instruct-awq:lexical_search_1_hop,True,True,False,1.000000,0.600000,1.0,False,False,False,0.5,0.5,0.5
355,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:llama-3-70b-instruct-awq:lexical_search_0_hop,True,True,False,1.000000,0.666667,1.0,False,False,False,0.5,0.5,0.5
356,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:llama-3-70b-instruct-awq:lexical_search_1_hop,True,NaN,NaN,1.000000,NaN,NaN,False,NaN,NaN,0.5,NaN,NaN
357,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
358,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:lexical_search_1_hop,True,True,False,0.740741,0.571429,1.0,False,False,False,0.5,0.5,0.5

In [18]:
pivot.head().to_dict()

{'consumer_id': {0: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv',
  1: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv',
  2: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv',
  3: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv',
  4: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv'},
 'test_name': {0: 'Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_0_hop',
  1: 'Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_1_hop',
  2: 'Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_0_hop',
  3: 'Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_1_hop',
  4: 'Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_0_hop'},
 'metric_success_Answer Relevancy': {0: True,
  1: True,
  2: True,
  3: True,
  4: True},
 'metric_success_Contextual Relevancy': {0: False,
  1: True,
  2: True,
  3: True,
  4: True},
 'metric_success_Hallucination': {0: True, 1: True, 2: True, 3: True, 4: True},
 'score_Answer Relevancy': {0: 1.0,
  1: 0.96875,
  2: 0.9565217391304348,
  3: 1.0,
  4: 0.9310344827586208},
 'score_Contextual Relevancy': {0: 0.3333333333333333,
  1: 1.0,
  2: 1.0,
  3: 1.0,
  4: 0.65},
 'score_Hallucination': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0},
 'success_Answer Relevancy': {0: False, 1: True, 2: True, 3: True, 4: True},
 'success_Contextual Relevancy': {0: False,
  1: True,
  2: True,
  3: True,
  4: True},
 'success_Hallucination': {0: False, 1: True, 2: True, 3: True, 4: True},
 'threshold_Answer Relevancy': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'threshold_Contextual Relevancy': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'threshold_Hallucination': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5}}

In [19]:
df = pivot
# Analysis 1: Overall success rates by metric
success_rates = (
    df[
        [
            "metric_success_Answer Relevancy",
            "metric_success_Contextual Relevancy",
            "metric_success_Hallucination",
        ]
    ].mean()
    * 100
)

print("Overall Success Rates by Metric (%):")
print(success_rates)

# Analysis 2: Average scores by metric
average_scores = df[
    ["score_Answer Relevancy", "score_Contextual Relevancy", "score_Hallucination"]
].mean()

print("\nAverage Scores by Metric:")
print(average_scores)


# Analysis 3: Threshold compliance (scores >= threshold)
def threshold_compliance(row, metric):
    return row[f"score_{metric}"] >= row[f"threshold_{metric}"]


for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
    df[f"threshold_compliance_{metric}"] = df.apply(
        threshold_compliance, axis=1, metric=metric
    )

threshold_compliance_rates = (
    df[
        [
            "threshold_compliance_Answer Relevancy",
            "threshold_compliance_Contextual Relevancy",
            "threshold_compliance_Hallucination",
        ]
    ].mean()
    * 100
)

print("\nThreshold Compliance Rates by Metric (%):")
print(threshold_compliance_rates)

# Analysis 4: Breakdown by test_name
breakdown = df.groupby(["consumer_id", "test_name"]).mean()

print("\nBreakdown by Test Name:")
print(breakdown)

Overall Success Rates by Metric (%):
metric_success_Answer Relevancy        95.238095
metric_success_Contextual Relevancy    83.601286
metric_success_Hallucination           76.012461
dtype: object

Average Scores by Metric:
score_Answer Relevancy        0.911742
score_Contextual Relevancy    0.736707
score_Hallucination           0.240265
dtype: float64

Threshold Compliance Rates by Metric (%):
threshold_compliance_Answer Relevancy        94.707521
threshold_compliance_Contextual Relevancy    72.423398
threshold_compliance_Hallucination           21.448468
dtype: float64

Breakdown by Test Name:
                                                                                                      metric_success_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             1.0
                                                   Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             1.0
...                                                                                                                               ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q6:llama-3-70b-instruct-awq:lexical_search_1_hop                               1.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_0_hop                               1.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_1_hop                               1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                               1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                               1.0

                                                                                                      metric_success_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                                 0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                                 1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                                 1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                                 1.0
                                                   Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                                 1.0
...                                                                                                                                   ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q6:llama-3-70b-instruct-awq:lexical_search_1_hop                                   1.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_0_hop                                   1.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_1_hop                                   NaN
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                                   1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                                   1.0

                                                                                                      metric_success_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
...                                                                                                                            ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q6:llama-3-70b-instruct-awq:lexical_search_1_hop                            0.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_0_hop                            0.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_1_hop                            NaN
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                            1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                            0.0

                                                                                                       score_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                1.000000
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                0.968750
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                0.956522
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                1.000000
                                                   Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                0.931034
...                                                                                                                       ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q6:llama-3-70b-instruct-awq:lexical_search_1_hop                  1.000000
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_0_hop                  1.000000
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_1_hop                  1.000000
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                  1.000000
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                  0.740741

                                                                                                       score_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                    0.333333
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                    1.000000
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                    1.000000
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                    1.000000
                                                   Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                    0.650000
...                                                                                                                           ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q6:llama-3-70b-instruct-awq:lexical_search_1_hop                      0.600000
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_0_hop                      0.666667
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_1_hop                           NaN
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                      1.000000
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                      0.571429

                                                                                                       score_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                  0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                  0.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                  0.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                  0.0
                                                   Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                  0.0
...                                                                                                                    ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q6:llama-3-70b-instruct-awq:lexical_search_1_hop                    1.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_0_hop                    1.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_1_hop                    NaN
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                    0.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                    1.0

                                                                                                      success_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      1.0
                                                   Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      1.0
...                                                                                                                        ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q6:llama-3-70b-instruct-awq:lexical_search_1_hop                        0.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_0_hop                        0.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_1_hop                        0.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                        1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                        0.0

                                                                                                      success_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
...                                                                                                                            ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q6:llama-3-70b-instruct-awq:lexical_search_1_hop                            0.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_0_hop                            0.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_1_hop                            NaN
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                            1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                            0.0

                                                                                                      success_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                   0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                   1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                   1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                   1.0
                                                   Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                   1.0
...                                                                                                                     ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q6:llama-3-70b-instruct-awq:lexical_search_1_hop                     0.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_0_hop                     0.0
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_1_hop                     NaN
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                     1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                     0.0

                                                                                                       threshold_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                         0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                         0.5
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                         0.5
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                         0.5
                                                   Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                         0.5
...                                                                                                                           ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q6:llama-3-70b-instruct-awq:lexical_search_1_hop                           0.5
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_0_hop                           0.5
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_1_hop                           0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                           0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                           0.5

                                                                                                       threshold_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             0.5
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             0.5
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             0.5
                                                   Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             0.5
...                                                                                                                               ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q6:llama-3-70b-instruct-awq:lexical_search_1_hop                               0.5
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_0_hop                               0.5
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_1_hop                               NaN
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                               0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                               0.5

                                                                                                       threshold_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.5
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.5
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.5
                                                   Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.5
...                                                                                                                        ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q6:llama-3-70b-instruct-awq:lexical_search_1_hop                        0.5
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_0_hop                        0.5
                                                   Q7:llama-3-70b-instruct-awq:lexical_search_1_hop                        NaN
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                        0.5

In [20]:
df = pivot

df[["question", "model", "search_type"]] = df["test_name"].str.split(":", expand=True)

In [21]:
df.columns

Index(['consumer_id', 'test_name', 'metric_success_Answer Relevancy',
       'metric_success_Contextual Relevancy', 'metric_success_Hallucination',
       'score_Answer Relevancy', 'score_Contextual Relevancy',
       'score_Hallucination', 'success_Answer Relevancy',
       'success_Contextual Relevancy', 'success_Hallucination',
       'threshold_Answer Relevancy', 'threshold_Contextual Relevancy',
       'threshold_Hallucination', 'threshold_compliance_Answer Relevancy',
       'threshold_compliance_Contextual Relevancy',
       'threshold_compliance_Hallucination', 'question', 'model',
       'search_type'],
      dtype='object')

In [22]:
df["true_consumer_id"] = df["consumer_id"].str.split("-").str[0]

In [23]:
df["hops"] = df["test_name"].str[-5:]

In [24]:
df["hops"] = df["hops"].str.replace("_hop", "", regex=False).astype(int)

In [25]:
df = df.replace("anthropic.claude-v3-5-sonnet-v2", "anthropic.claude-v3-opus")
df = df.replace("gpt-4o-2024-11-20", "gpt-4o-2024-08-06")

In [26]:
df = df.replace("lexical_search_0_hop", "L0")
df = df.replace("lexical_search_1_hop", "L1")
df = df.replace("similarity_search_1_hop", "S1")
df = df.replace("similarity_search_0_hop", "S0")

In [27]:
df = df[df["search_type"] != "lexical_search_2_hop"]

In [28]:
df

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,...,threshold_Contextual Relevancy,threshold_Hallucination,threshold_compliance_Answer Relevancy,threshold_compliance_Contextual Relevancy,threshold_compliance_Hallucination,question,model,search_type,true_consumer_id,hops
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,False,True,1.000000,0.333333,0.0,False,False,...,0.5,0.5,True,False,False,Q1,DeepSeek-R1-Distill-Llama-70B-FP8,L0,Allen322_Ferry570_ad134528,0
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.968750,1.000000,0.0,True,True,...,0.5,0.5,True,True,False,Q1,DeepSeek-R1-Distill-Llama-70B-FP8,L1,Allen322_Ferry570_ad134528,1
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.956522,1.000000,0.0,True,True,...,0.5,0.5,True,True,False,Q2,DeepSeek-R1-Distill-Llama-70B-FP8,L0,Allen322_Ferry570_ad134528,0
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,True,True,False,Q2,DeepSeek-R1-Distill-Llama-70B-FP8,L1,Allen322_Ferry570_ad134528,1
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q3:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.931034,0.650000,0.0,True,True,...,0.5,0.5,True,True,False,Q3,DeepSeek-R1-Distill-Llama-70B-FP8,L0,Allen322_Ferry570_ad134528,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q6:llama-3-70b-instruct-awq:lexical_search_1_hop,True,True,False,1.000000,0.600000,1.0,False,False,...,0.5,0.5,True,True,True,Q6,llama-3-70b-instruct-awq,L1,Milton509_Ortiz186_d66b5418,1
355,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:llama-3-70b-instruct-awq:lexical_search_0_hop,True,True,False,1.000000,0.666667,1.0,False,False,...,0.5,0.5,True,True,True,Q7,llama-3-70b-instruct-awq,L0,Milton509_Ortiz186_d66b5418,0
356,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:llama-3-70b-instruct-awq:lexical_search_1_hop,True,NaN,NaN,1.000000,NaN,NaN,False,NaN,...,NaN,NaN,True,False,False,Q7,llama-3-70b-instruct-awq,L1,Milton509_Ortiz186_d66b5418,1
357,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,True,True,False,Q8,llama-3-70b-instruct-awq,L0,Milton509_Ortiz186_d66b5418,0
358,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:lexical_search_1_hop,True,True,False,0.740741,0.571429,1.0,False,False,...,0.5,0.5,True,True,True,Q8,llama-3-70b-instruct-awq,L1,Milton509_Ortiz186_d66b5418,1

In [29]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = (
    df.groupby(["consumer_id", "question", "search_type", "hops"])
    .apply(analyze_metrics)
    .reset_index()
)
grouped_df

/tmp/ipykernel_12401/833737725.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(analyze_metrics)

,consumer_id,question,search_type,hops,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,L0,0,1.000000,0.0,1.0,0.333333,0.0,0.0,0.0,0.0,1.0
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,L1,1,0.968750,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2,L0,0,0.956522,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2,L1,1,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q3,L0,0,0.931034,1.0,1.0,0.650000,1.0,1.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q6,L1,1,1.000000,0.0,1.0,0.600000,0.0,1.0,1.0,0.0,0.0
355,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7,L0,0,1.000000,0.0,1.0,0.666667,0.0,1.0,1.0,0.0,0.0
356,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7,L1,1,1.000000,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
357,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,L0,0,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
358,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,L1,1,0.740741,0.0,1.0,0.571429,0.0,1.0,1.0,0.0,0.0

In [30]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = (
    df.groupby(["consumer_id", "search_type"]).apply(analyze_metrics).reset_index()
)
grouped_df

/tmp/ipykernel_12401/1437396366.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(["consumer_id", "search_type"]).apply(analyze_metrics).reset_index()

,consumer_id,search_type,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L0,0.985945,0.625000,1.000000,0.682411,0.625000,0.625000,0.250000,0.625000,0.750000
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L1,0.971551,0.500000,1.000000,0.877381,0.666667,1.000000,0.333333,0.666667,0.666667
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L0,0.771987,0.625000,0.875000,0.681324,0.625000,0.875000,0.125000,0.625000,0.875000
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L1,0.973637,0.125000,1.000000,0.773810,0.142857,0.857143,0.857143,0.142857,0.142857
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L0,1.000000,0.750000,1.000000,0.690247,0.750000,0.750000,0.125000,0.750000,0.875000
5,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L1,0.994681,0.625000,1.000000,0.892857,0.857143,0.857143,0.000000,0.750000,1.000000
6,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L0,0.921972,0.875000,1.000000,0.711837,0.875000,0.875000,0.140625,0.875000,0.875000
7,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L1,0.939804,0.500000,1.000000,0.737408,0.666667,0.833333,0.166667,0.666667,0.833333
8,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L0,0.962533,0.625000,1.000000,0.719444,0.625000,0.750000,0.250000,0.625000,0.750000
9,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L1,0.986607,0.375000,1.000000,0.640542,0.500000,0.666667,0.166667,0.500000,0.833333
10,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,L0,0.730000,0.750000,0.750000,0.861111,0.750000,1.000000,0.250000,0.750000,0.750000
11,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,L1,0.972709,0.500000,1.000000,0.696800,0.500000,0.750000,0.250000,0.500000,0.750000
12,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,L0,0.792707,0.750000,0.875000,0.747069,0.750000,1.000000,0.250000,0.750000,0.750000
13,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,L1,0.912143,0.875000,1.000000,0.744731,0.875000,1.000000,0.125000,0.875000,0.875000
14,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,L0,1.000000,0.875000,1.000000,0.861111,0.875000,0.875000,0.000000,0.875000,1.000000
15,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,L1,0.966667,0.500000,1.000000,0.843750,0.666667,0.833333,0.000000,0.571429,1.000000
16,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,L0,1.000000,0.875000,1.000000,0.861111,0.875000,0.875000,0.000000,0.875000,1.000000
17,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,L1,0.966667,0.500000,1.000000,0.843750,0.666667,0.833333,0.000000,0.571429,1.000000
18,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,L0,0.914583,0.875000,0.875000,0.906944,0.875000,1.000000,0.000000,0.875000,1.000000
19,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,L1,0.869744,0.625000,0.875000,0.752232,0.625000,0.875000,0.250000,0.625000,0.750000
20,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,L0,0.822290,0.625000,0.875000,0.854875,0.714286,0.857143,0.125000,0.625000,0.875000
21,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,L1,0.959812,0.500000,1.000000,0.783333,0.500000,1.000000,0.500000,0.500000,0.500000
22,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,L0,0.919355,0.285714,1.000000,0.628542,0.285714,0.571429,0.285714,0.285714,0.714286
23,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,L1,0.712723,0.500000,0.875000,0.566146,0.500000,0.750000,0.375000,0.500000,0.625000
24,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,L0,0.821769,0.571429,0.857143,0.638095,0.571429,0.714286,0.285714,0.571429,0.714286
25,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,L1,0.953602,0.571429,1.000000,0.809751,0.571429,1.000000,0.428571,0.571429,0.571429
26,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,L0,0.878571,0.428571,1.000000,0.692857,0.600000,0.600000,0.142857,0.428571,0.857143
27,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,L1,0.903061,0.428571,0.857143,0.907895,0.750000,1.000000,0.285714,0.428571,0.714286
28,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,L0,1.000000,0.571429,1.000000,0.642857,0.571429,0.857143,0.285714,0.571429,0.714286
29,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,L1,0.975510,0.428571,1.000000,0.868764,0.428571,1.000000,0.571429,0.428571,0.428571
30,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,L0,0.822449,0.714286,0.857143,0.664153,0.714286,0.714286,0.142857,0.714286,0.857143
31,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,L1,0.866647,0.285714,1.000000,0.502646,0.285714,0.428571,0.285714,0.285714,0.714286
32,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,L0,0.956602,0.714286,1.000000,0.862745,0.714286,1.000000,0.285714,0.714286,0.714286
33,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,L1,1.000000,0.285714,1.000000,0.666667,0.666667,0.666667,0.000000,0.666667,1.000000
34,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,L0,0.964729,0.714286,1.000000,0.651190,0.714286,0.857143,0.285714,0.714286,0.714286
35,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,L1,0.962728,0.142857,1.000000,0.861111,0.333333,1.000000,0.666667,0.333333,0.333333
36,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,L0,0.935338,0.571429,1.000000,0.752315,0.666667,0.833333,0.166667,0.666667,0.833333
37,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,L1,0.942641,0.285714,1.000000,0.863636,1.000000,1.000000,0.000000,0.666667,1.000000
38,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,L0,0.972144,0.714286,1.000000,0.666994,0.714286,0.857143,0.285714,0.714286,0.714286
39,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,L1,0.801713,0.250000,0.875000,0.652778,0.666667,0.666667,0.000000,0.666667,1.000000
40,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,L0,0.840000,0.714286,0.857143,0.678546,0.714286,0.857143,0.285714,0.714286,0.714286
41,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,L1,0.740053,0.250000,0.750000,0.530864,0.666667,1.000000,0.250000,0.500000,0.750000
42,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,L1,0.956481,0.000000,1.000000,0.801587,0.000000,1.000000,1.000000,0.000000,0.000000
43,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,L0,0.915152,0.666667,1.000000,0.812500,0.500000,0.750000,0.000000,0.666667,1.000000
44,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,L1,0.982759,0.600000,1.000000,0.696635,0.750000,0.750000,0.200000,0.600000,0.800000
45,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,L0,0.803102,0.428571,0.857143,0.632784,0.428571,0.714286,0.285714,0.428571,0.714286
46,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,L1,0.875348,0.285714,1.000000,0.630000,0.400000,0.800000,0.400000,0.400000,0.600000
47,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,L0,0.960111,0.428571,1.000000,0.654942,0.428571,0.857143,0.428571,0.428571,0.571429
48,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,L1,0.868481,0.142857,0.857143,0.576190,0.250000,0.750000,0.500000,0.250000,0.500000

In [31]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_12401/3565463073.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()

,search_type,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,L0,0.903319,0.662857,0.942857,0.732786,0.674419,0.825581,0.196121,0.666667,0.804598
1,L1,0.919840,0.417582,0.961538,0.741560,0.553957,0.848921,0.292517,0.523810,0.707483

In [32]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["question"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_12401/1271303342.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["question"]).apply(analyze_metrics).reset_index()

,question,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Q1,0.732348,0.291667,0.854167,0.437682,0.311111,0.400000,0.166667,0.291667,0.833333
1,Q2,0.861341,0.880000,0.880000,0.900621,0.956522,0.956522,0.043478,0.956522,0.956522
2,Q3,0.901862,0.541667,0.958333,0.719818,0.702703,0.864865,0.187500,0.684211,0.815789
3,Q4,0.908048,0.127660,0.936170,0.620213,0.157895,0.789474,0.641026,0.153846,0.358974
4,Q5,0.969828,0.869565,0.978261,0.829701,0.851064,0.914894,0.043478,0.869565,0.956522
5,Q6,0.992381,0.291667,1.000000,0.677679,0.416667,0.888889,0.550000,0.375000,0.450000
6,Q7,0.950887,0.595745,0.978723,0.857018,0.700000,0.950000,0.230769,0.717949,0.769231
7,Q8,0.956247,0.875000,1.000000,0.907370,0.933333,1.000000,0.062500,0.875000,0.937500

In [33]:
df.columns

Index(['consumer_id', 'test_name', 'metric_success_Answer Relevancy',
       'metric_success_Contextual Relevancy', 'metric_success_Hallucination',
       'score_Answer Relevancy', 'score_Contextual Relevancy',
       'score_Hallucination', 'success_Answer Relevancy',
       'success_Contextual Relevancy', 'success_Hallucination',
       'threshold_Answer Relevancy', 'threshold_Contextual Relevancy',
       'threshold_Hallucination', 'threshold_compliance_Answer Relevancy',
       'threshold_compliance_Contextual Relevancy',
       'threshold_compliance_Hallucination', 'question', 'model',
       'search_type', 'true_consumer_id', 'hops'],
      dtype='object')

## By model

In [34]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["model", "search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_12401/913412050.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["model", "search_type"]).apply(analyze_metrics).reset_index()

,model,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,DeepSeek-R1-Distill-Llama-70B-FP8,L0,0.884845,0.276843,0.621622,0.918919,0.744244,0.262226,0.621622,0.810811,0.270270,0.450225,0.621622,0.729730
1,DeepSeek-R1-Distill-Llama-70B-FP8,L1,0.876315,0.257049,0.410256,0.923077,0.677159,0.285567,0.571429,0.821429,0.275862,0.454859,0.551724,0.724138
2,anthropic.claude-v3-opus,L0,0.834101,0.302956,0.666667,0.900000,0.681738,0.183267,0.666667,0.866667,0.233333,0.430183,0.666667,0.766667
3,anthropic.claude-v3-opus,L1,0.950422,0.057317,0.406250,1.000000,0.786816,0.171785,0.464286,0.964286,0.518519,0.509175,0.481481,0.481481
4,gemini-1.5-pro,L0,0.967513,0.093971,0.735294,1.000000,0.788304,0.322525,0.757576,0.787879,0.058824,0.238833,0.735294,0.941176
5,gemini-1.5-pro,L1,0.962759,0.115268,0.527778,0.972222,0.844190,0.271847,0.740741,0.851852,0.088235,0.287902,0.588235,0.911765
6,gpt-4o-2024-08-06,L0,0.915176,0.215178,0.675676,0.945946,0.733156,0.242131,0.694444,0.861111,0.170139,0.376962,0.694444,0.833333
7,gpt-4o-2024-08-06,L1,0.919753,0.152253,0.432432,0.972973,0.764319,0.210661,0.571429,0.892857,0.310345,0.470824,0.551724,0.689655
8,llama-3-70b-instruct-awq,L0,0.907068,0.231294,0.621622,0.945946,0.712286,0.283731,0.638889,0.805556,0.243243,0.434959,0.621622,0.756757
9,llama-3-70b-instruct-awq,L1,0.898183,0.206496,0.315789,0.947368,0.638983,0.262896,0.428571,0.714286,0.321429,0.475595,0.428571,0.678571

In [35]:
grouped_df["ARS"] = grouped_df['avg_score_Answer Relevancy'].round(2).astype(str) + "±" + grouped_df['std_score_Answer Relevancy'].round(2).astype(str)

In [36]:
grouped_df["CRS"] = grouped_df['avg_score_Contextual Relevancy'].round(2).astype(str) + "±" + grouped_df['std_score_Contextual Relevancy'].round(2).astype(str)

In [37]:
grouped_df["HALS"] = grouped_df['avg_score_Hallucination'].round(2).astype(str) + "±" + grouped_df['std_score_Hallucination'].round(2).astype(str)

In [38]:
grouped_df[
    [
        "model",
        "search_type",
        "ARS",
        "CRS",
        "HALS"
    ]
].sort_values(by=["model", 'search_type'])

,model,search_type,ARS,CRS,HALS
0,DeepSeek-R1-Distill-Llama-70B-FP8,L0,0.88±0.28,0.74±0.26,0.27±0.45
1,DeepSeek-R1-Distill-Llama-70B-FP8,L1,0.88±0.26,0.68±0.29,0.28±0.45
2,anthropic.claude-v3-opus,L0,0.83±0.3,0.68±0.18,0.23±0.43
3,anthropic.claude-v3-opus,L1,0.95±0.06,0.79±0.17,0.52±0.51
4,gemini-1.5-pro,L0,0.97±0.09,0.79±0.32,0.06±0.24
5,gemini-1.5-pro,L1,0.96±0.12,0.84±0.27,0.09±0.29
6,gpt-4o-2024-08-06,L0,0.92±0.22,0.73±0.24,0.17±0.38
7,gpt-4o-2024-08-06,L1,0.92±0.15,0.76±0.21,0.31±0.47
8,llama-3-70b-instruct-awq,L0,0.91±0.23,0.71±0.28,0.24±0.43
9,llama-3-70b-instruct-awq,L1,0.9±0.21,0.64±0.26,0.32±0.48

In [39]:
grouped_df[
    [
        "model",
        "search_type",
        "ARS",
        "CRS",
        "HALS"
    ]
].sort_values(by=["model", 'search_type']).to_dict()

{'model': {0: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  1: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  2: 'anthropic.claude-v3-opus',
  3: 'anthropic.claude-v3-opus',
  4: 'gemini-1.5-pro',
  5: 'gemini-1.5-pro',
  6: 'gpt-4o-2024-08-06',
  7: 'gpt-4o-2024-08-06',
  8: 'llama-3-70b-instruct-awq',
  9: 'llama-3-70b-instruct-awq'},
 'search_type': {0: 'L0',
  1: 'L1',
  2: 'L0',
  3: 'L1',
  4: 'L0',
  5: 'L1',
  6: 'L0',
  7: 'L1',
  8: 'L0',
  9: 'L1'},
 'ARS': {0: '0.88±0.28',
  1: '0.88±0.26',
  2: '0.83±0.3',
  3: '0.95±0.06',
  4: '0.97±0.09',
  5: '0.96±0.12',
  6: '0.92±0.22',
  7: '0.92±0.15',
  8: '0.91±0.23',
  9: '0.9±0.21'},
 'CRS': {0: '0.74±0.26',
  1: '0.68±0.29',
  2: '0.68±0.18',
  3: '0.79±0.17',
  4: '0.79±0.32',
  5: '0.84±0.27',
  6: '0.73±0.24',
  7: '0.76±0.21',
  8: '0.71±0.28',
  9: '0.64±0.26'},
 'HALS': {0: '0.27±0.45',
  1: '0.28±0.45',
  2: '0.23±0.43',
  3: '0.52±0.51',
  4: '0.06±0.24',
  5: '0.09±0.29',
  6: '0.17±0.38',
  7: '0.31±0.47',
  8: '0.24±0.43',
  9: '0.32±0.48'}}

In [40]:
## PARAR AQUI

## By question

In [41]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["question", "search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_12401/3056670344.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["question", "search_type"]).apply(analyze_metrics).reset_index()

,question,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Q1,L0,0.664736,0.362792,0.304348,0.782609,0.402021,0.224742,0.304348,0.391304,0.173913,0.387553,0.304348,0.826087
1,Q1,L1,0.794550,0.218102,0.280000,0.920000,0.474964,0.251188,0.318182,0.409091,0.160000,0.374166,0.280000,0.840000
2,Q2,L0,0.982302,0.022491,1.000000,1.000000,0.933622,0.090856,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000
3,Q2,L1,0.766300,0.417530,0.785714,0.785714,0.870370,0.291416,0.916667,0.916667,0.083333,0.288675,0.916667,0.916667
4,Q3,L0,0.911018,0.090512,0.791667,1.000000,0.672374,0.218866,0.791667,0.791667,0.046875,0.204609,0.791667,0.958333
5,Q3,L1,0.892706,0.163654,0.291667,0.916667,0.807406,0.166420,0.538462,1.000000,0.428571,0.513553,0.500000,0.571429
6,Q4,L0,0.827143,0.339611,0.173913,0.869565,0.621505,0.257993,0.190476,0.714286,0.590909,0.503236,0.181818,0.409091
7,Q4,L1,0.985582,0.039642,0.083333,1.000000,0.618618,0.178406,0.117647,0.882353,0.705882,0.469668,0.117647,0.294118
8,Q5,L0,0.946292,0.212027,0.913043,0.956522,0.898727,0.192520,0.875000,0.958333,0.043478,0.208514,0.913043,0.956522
9,Q5,L1,0.993364,0.023117,0.826087,1.000000,0.757673,0.255818,0.826087,0.869565,0.043478,0.208514,0.826087,0.956522
10,Q6,L0,0.987907,0.044838,0.458333,1.000000,0.638366,0.178381,0.500000,0.863636,0.500000,0.510754,0.458333,0.500000
11,Q6,L1,0.996854,0.010660,0.125000,1.000000,0.739456,0.171120,0.285714,0.928571,0.625000,0.500000,0.250000,0.375000
12,Q7,L0,0.950166,0.207844,0.826087,0.956522,0.841449,0.190895,0.826087,0.956522,0.130435,0.344350,0.826087,0.869565
13,Q7,L1,0.951579,0.079602,0.375000,1.000000,0.878081,0.183478,0.529412,0.941176,0.375000,0.500000,0.562500,0.625000
14,Q8,L0,0.990397,0.039380,1.000000,1.000000,0.931976,0.148917,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000
15,Q8,L1,0.922097,0.118469,0.750000,1.000000,0.879248,0.157237,0.857143,1.000000,0.125000,0.337832,0.750000,0.875000

In [42]:
grouped_df["ARS"] = grouped_df['avg_score_Answer Relevancy'].round(2).astype(str) + "±" + grouped_df['std_score_Answer Relevancy'].round(2).astype(str)

In [43]:
grouped_df["CRS"] = grouped_df['avg_score_Contextual Relevancy'].round(2).astype(str) + "±" + grouped_df['std_score_Contextual Relevancy'].round(2).astype(str)

In [44]:
grouped_df["HALS"] = grouped_df['avg_score_Hallucination'].round(2).astype(str) + "±" + grouped_df['std_score_Hallucination'].round(2).astype(str)

In [45]:
grouped_df[
    [
        "question",
        "search_type",
        "ARS",
        "CRS",
        "HALS"
    ]
].sort_values(by=["question", 'search_type'])

   question search_type        ARS        CRS       HALS
0        Q1          L0  0.66±0.36   0.4±0.22  0.17±0.39
1        Q1          L1  0.79±0.22  0.47±0.25  0.16±0.37
2        Q2          L0  0.98±0.02  0.93±0.09    0.0±0.0
3        Q2          L1  0.77±0.42  0.87±0.29  0.08±0.29
4        Q3          L0  0.91±0.09  0.67±0.22   0.05±0.2
5        Q3          L1  0.89±0.16  0.81±0.17  0.43±0.51
6        Q4          L0  0.83±0.34  0.62±0.26   0.59±0.5
7        Q4          L1  0.99±0.04  0.62±0.18  0.71±0.47
8        Q5          L0  0.95±0.21   0.9±0.19  0.04±0.21
9        Q5          L1  0.99±0.02  0.76±0.26  0.04±0.21
10       Q6          L0  0.99±0.04  0.64±0.18   0.5±0.51
11       Q6          L1   1.0±0.01  0.74±0.17   0.62±0.5
12       Q7          L0  0.95±0.21  0.84±0.19  0.13±0.34
13       Q7          L1  0.95±0.08  0.88±0.18   0.38±0.5
14       Q8          L0  0.99±0.04  0.93±0.15    0.0±0.0
15       Q8          L1  0.92±0.12  0.88±0.16  0.12±0.34

In [46]:
grouped_df[
    [
        "question",
        "search_type",
        "ARS",
        "CRS",
        "HALS"
    ]
].sort_values(by=["question", 'search_type']).to_dict()

{'question': {0: 'Q1',
  1: 'Q1',
  2: 'Q2',
  3: 'Q2',
  4: 'Q3',
  5: 'Q3',
  6: 'Q4',
  7: 'Q4',
  8: 'Q5',
  9: 'Q5',
  10: 'Q6',
  11: 'Q6',
  12: 'Q7',
  13: 'Q7',
  14: 'Q8',
  15: 'Q8'},
 'search_type': {0: 'L0',
  1: 'L1',
  2: 'L0',
  3: 'L1',
  4: 'L0',
  5: 'L1',
  6: 'L0',
  7: 'L1',
  8: 'L0',
  9: 'L1',
  10: 'L0',
  11: 'L1',
  12: 'L0',
  13: 'L1',
  14: 'L0',
  15: 'L1'},
 'ARS': {0: '0.66±0.36',
  1: '0.79±0.22',
  2: '0.98±0.02',
  3: '0.77±0.42',
  4: '0.91±0.09',
  5: '0.89±0.16',
  6: '0.83±0.34',
  7: '0.99±0.04',
  8: '0.95±0.21',
  9: '0.99±0.02',
  10: '0.99±0.04',
  11: '1.0±0.01',
  12: '0.95±0.21',
  13: '0.95±0.08',
  14: '0.99±0.04',
  15: '0.92±0.12'},
 'CRS': {0: '0.4±0.22',
  1: '0.47±0.25',
  2: '0.93±0.09',
  3: '0.87±0.29',
  4: '0.67±0.22',
  5: '0.81±0.17',
  6: '0.62±0.26',
  7: '0.62±0.18',
  8: '0.9±0.19',
  9: '0.76±0.26',
  10: '0.64±0.18',
  11: '0.74±0.17',
  12: '0.84±0.19',
  13: '0.88±0.18',
  14: '0.93±0.15',
  15: '0.88±0.16'},
 'HALS': {0: '0.17±0.39',
  1: '0.16±0.37',
  2: '0.0±0.0',
  3: '0.08±0.29',
  4: '0.05±0.2',
  5: '0.43±0.51',
  6: '0.59±0.5',
  7: '0.71±0.47',
  8: '0.04±0.21',
  9: '0.04±0.21',
  10: '0.5±0.51',
  11: '0.62±0.5',
  12: '0.13±0.34',
  13: '0.38±0.5',
  14: '0.0±0.0',
  15: '0.12±0.34'}}

## By Patient

In [47]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["true_consumer_id", "search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_12401/3800553430.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["true_consumer_id", "search_type"]).apply(analyze_metrics).reset_index()

,true_consumer_id,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528,L0,0.928487,0.177532,0.700000,0.975000,0.697053,0.274389,0.700000,0.775000,0.178125,0.383856,0.700000,0.825000
1,Allen322_Ferry570_ad134528,L1,0.973256,0.052175,0.425000,1.000000,0.787458,0.230180,0.562500,0.843750,0.303030,0.466694,0.545455,0.696970
2,Beatris270_Bogan287_5b3645de,L0,0.876597,0.295112,0.791667,0.895833,0.848572,0.203089,0.808511,0.936170,0.104167,0.308709,0.791667,0.895833
3,Beatris270_Bogan287_5b3645de,L1,0.941290,0.129879,0.583333,0.979167,0.771404,0.231810,0.636364,0.886364,0.195652,0.401085,0.608696,0.804348
4,Edythe31_Morar593_9c3df38a,L0,0.888429,0.245102,0.514286,0.942857,0.650904,0.285405,0.545455,0.696970,0.228571,0.426043,0.514286,0.771429
5,Edythe31_Morar593_9c3df38a,L1,0.877598,0.223878,0.444444,0.944444,0.709966,0.284910,0.484848,0.818182,0.388889,0.494413,0.444444,0.611111
6,Jacklyn830_Veum823_e0e1f21a,L0,0.957203,0.093014,0.678571,1.000000,0.732607,0.222832,0.703704,0.888889,0.259259,0.446576,0.703704,0.740741
7,Jacklyn830_Veum823_e0e1f21a,L1,0.922458,0.203309,0.241379,0.965517,0.751722,0.263944,0.636364,0.818182,0.166667,0.389249,0.583333,0.833333
8,Milton509_Ortiz186_d66b5418,L0,0.873664,0.282748,0.541667,0.916667,0.680556,0.299014,0.520000,0.800000,0.291667,0.464306,0.541667,0.708333
9,Milton509_Ortiz186_d66b5418,L1,0.860482,0.236374,0.275862,0.896552,0.644140,0.256358,0.421053,0.842105,0.400000,0.502625,0.400000,0.600000

In [48]:
grouped_df["ARS"] = grouped_df['avg_score_Answer Relevancy'].round(2).astype(str) + "±" + grouped_df['std_score_Answer Relevancy'].round(2).astype(str)

In [49]:
grouped_df["CRS"] = grouped_df['avg_score_Contextual Relevancy'].round(2).astype(str) + "±" + grouped_df['std_score_Contextual Relevancy'].round(2).astype(str)

In [50]:
grouped_df["HALS"] = grouped_df['avg_score_Hallucination'].round(2).astype(str) + "±" + grouped_df['std_score_Hallucination'].round(2).astype(str)

In [51]:
grouped_df[
    [
        "true_consumer_id",
        "search_type",
        "ARS",
        "CRS",
        "HALS"
    ]
].sort_values(by=["true_consumer_id", 'search_type'])

               true_consumer_id search_type        ARS        CRS       HALS
0    Allen322_Ferry570_ad134528          L0  0.93±0.18   0.7±0.27  0.18±0.38
1    Allen322_Ferry570_ad134528          L1  0.97±0.05  0.79±0.23   0.3±0.47
2  Beatris270_Bogan287_5b3645de          L0   0.88±0.3   0.85±0.2   0.1±0.31
3  Beatris270_Bogan287_5b3645de          L1  0.94±0.13  0.77±0.23    0.2±0.4
4    Edythe31_Morar593_9c3df38a          L0  0.89±0.25  0.65±0.29  0.23±0.43
5    Edythe31_Morar593_9c3df38a          L1  0.88±0.22  0.71±0.28  0.39±0.49
6   Jacklyn830_Veum823_e0e1f21a          L0  0.96±0.09  0.73±0.22  0.26±0.45
7   Jacklyn830_Veum823_e0e1f21a          L1   0.92±0.2  0.75±0.26  0.17±0.39
8   Milton509_Ortiz186_d66b5418          L0  0.87±0.28   0.68±0.3  0.29±0.46
9   Milton509_Ortiz186_d66b5418          L1  0.86±0.24  0.64±0.26    0.4±0.5

In [52]:
grouped_df[
    [
        "true_consumer_id",
        "search_type",
        "ARS",
        "CRS",
        "HALS"
    ]
].sort_values(by=["true_consumer_id", 'search_type']).to_dict()

{'true_consumer_id': {0: 'Allen322_Ferry570_ad134528',
  1: 'Allen322_Ferry570_ad134528',
  2: 'Beatris270_Bogan287_5b3645de',
  3: 'Beatris270_Bogan287_5b3645de',
  4: 'Edythe31_Morar593_9c3df38a',
  5: 'Edythe31_Morar593_9c3df38a',
  6: 'Jacklyn830_Veum823_e0e1f21a',
  7: 'Jacklyn830_Veum823_e0e1f21a',
  8: 'Milton509_Ortiz186_d66b5418',
  9: 'Milton509_Ortiz186_d66b5418'},
 'search_type': {0: 'L0',
  1: 'L1',
  2: 'L0',
  3: 'L1',
  4: 'L0',
  5: 'L1',
  6: 'L0',
  7: 'L1',
  8: 'L0',
  9: 'L1'},
 'ARS': {0: '0.93±0.18',
  1: '0.97±0.05',
  2: '0.88±0.3',
  3: '0.94±0.13',
  4: '0.89±0.25',
  5: '0.88±0.22',
  6: '0.96±0.09',
  7: '0.92±0.2',
  8: '0.87±0.28',
  9: '0.86±0.24'},
 'CRS': {0: '0.7±0.27',
  1: '0.79±0.23',
  2: '0.85±0.2',
  3: '0.77±0.23',
  4: '0.65±0.29',
  5: '0.71±0.28',
  6: '0.73±0.22',
  7: '0.75±0.26',
  8: '0.68±0.3',
  9: '0.64±0.26'},
 'HALS': {0: '0.18±0.38',
  1: '0.3±0.47',
  2: '0.1±0.31',
  3: '0.2±0.4',
  4: '0.23±0.43',
  5: '0.39±0.49',
  6: '0.26±0.45',
  7: '0.17±0.39',
  8: '0.29±0.46',
  9: '0.4±0.5'}}

In [44]:
grouped_df[
    [
        "model",
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].sort_values(by=["model", 'search_type'])

,model,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination
0,DeepSeek-R1-Distill-Llama-70B-FP8,L0,0.884845,0.276843,0.744244,0.262226,0.270270,0.450225
1,DeepSeek-R1-Distill-Llama-70B-FP8,L1,0.876315,0.257049,0.677159,0.285567,0.275862,0.454859
2,anthropic.claude-v3-opus,L0,0.834101,0.302956,0.681738,0.183267,0.233333,0.430183
3,anthropic.claude-v3-opus,L1,0.950422,0.057317,0.786816,0.171785,0.518519,0.509175
4,gemini-1.5-pro,L0,0.967513,0.093971,0.788304,0.322525,0.058824,0.238833
5,gemini-1.5-pro,L1,0.962759,0.115268,0.844190,0.271847,0.088235,0.287902
6,gpt-4o-2024-08-06,L0,0.915176,0.215178,0.733156,0.242131,0.170139,0.376962
7,gpt-4o-2024-08-06,L1,0.919753,0.152253,0.764319,0.210661,0.310345,0.470824
8,llama-3-70b-instruct-awq,L0,0.907068,0.231294,0.712286,0.283731,0.243243,0.434959
9,llama-3-70b-instruct-awq,L1,0.898183,0.206496,0.638983,0.262896,0.321429,0.475595

In [45]:
grouped_df[
    [
        "search_type",
        "model",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].sort_values(by=['search_type', "model"])

,search_type,model,avg_score_Answer Relevancy,std_score_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination
0,L0,DeepSeek-R1-Distill-Llama-70B-FP8,0.884845,0.276843,0.744244,0.262226,0.270270,0.450225
2,L0,anthropic.claude-v3-opus,0.834101,0.302956,0.681738,0.183267,0.233333,0.430183
4,L0,gemini-1.5-pro,0.967513,0.093971,0.788304,0.322525,0.058824,0.238833
6,L0,gpt-4o-2024-08-06,0.915176,0.215178,0.733156,0.242131,0.170139,0.376962
8,L0,llama-3-70b-instruct-awq,0.907068,0.231294,0.712286,0.283731,0.243243,0.434959
1,L1,DeepSeek-R1-Distill-Llama-70B-FP8,0.876315,0.257049,0.677159,0.285567,0.275862,0.454859
3,L1,anthropic.claude-v3-opus,0.950422,0.057317,0.786816,0.171785,0.518519,0.509175
5,L1,gemini-1.5-pro,0.962759,0.115268,0.844190,0.271847,0.088235,0.287902
7,L1,gpt-4o-2024-08-06,0.919753,0.152253,0.764319,0.210661,0.310345,0.470824
9,L1,llama-3-70b-instruct-awq,0.898183,0.206496,0.638983,0.262896,0.321429,0.475595

In [46]:
grouped_df[
    [
        "model",
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].to_dict()

{'model': {0: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  1: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  2: 'anthropic.claude-v3-opus',
  3: 'anthropic.claude-v3-opus',
  4: 'gemini-1.5-pro',
  5: 'gemini-1.5-pro',
  6: 'gpt-4o-2024-08-06',
  7: 'gpt-4o-2024-08-06',
  8: 'llama-3-70b-instruct-awq',
  9: 'llama-3-70b-instruct-awq'},
 'search_type': {0: 'L0',
  1: 'L1',
  2: 'L0',
  3: 'L1',
  4: 'L0',
  5: 'L1',
  6: 'L0',
  7: 'L1',
  8: 'L0',
  9: 'L1'},
 'avg_score_Answer Relevancy': {0: 0.884844670933103,
  1: 0.8763150212902858,
  2: 0.8341011140088219,
  3: 0.9504222299542489,
  4: 0.9675133689839571,
  5: 0.9627593097237265,
  6: 0.9151762705824492,
  7: 0.9197534375180828,
  8: 0.9070680817611532,
  9: 0.8981828722416488},
 'std_score_Answer Relevancy': {0: 0.2768425501153924,
  1: 0.25704880536204594,
  2: 0.302955989963187,
  3: 0.05731718345423768,
  4: 0.09397137343079162,
  5: 0.11526766847637666,
  6: 0.21517805171815468,
  7: 0.1522533261997558,
  8: 0.23129377628122835,
  9: 0.20649626424320608},
 'avg_score_Contextual Relevancy': {0: 0.7442436493907083,
  1: 0.6771588131809806,
  2: 0.6817382154882154,
  3: 0.7868164573521715,
  4: 0.7883042883042882,
  5: 0.8441895336632178,
  6: 0.7331563498230165,
  7: 0.7643189152117723,
  8: 0.7122862091612092,
  9: 0.6389833711262283},
 'std_score_Contextual Relevancy': {0: 0.26222626878837746,
  1: 0.2855674762187864,
  2: 0.1832670959065373,
  3: 0.17178515378250703,
  4: 0.3225248738846611,
  5: 0.27184727921423085,
  6: 0.2421310571643378,
  7: 0.21066080401804246,
  8: 0.2837306116427444,
  9: 0.2628961240749081},
 'avg_score_Hallucination': {0: 0.2702702702702703,
  1: 0.27586206896551724,
  2: 0.23333333333333334,
  3: 0.5185185185185185,
  4: 0.058823529411764705,
  5: 0.08823529411764706,
  6: 0.1701388888888889,
  7: 0.3103448275862069,
  8: 0.24324324324324326,
  9: 0.32142857142857145},
 'std_score_Hallucination': {0: 0.4502251688907482,
  1: 0.454858826147342,
  2: 0.4301830671520762,
  3: 0.5091750772173156,
  4: 0.23883257361061289,
  5: 0.28790224128123654,
  6: 0.3769624576061182,
  7: 0.4708236154307584,
  8: 0.43495883620084,
  9: 0.47559486560567094}}

In [47]:
markdown_table = """| Model                   | Search Type               | Avg Score Answer Relevancy (%) | Std Score Answer Relevancy (%) | Avg Score Contextual Relevancy (%) | Std Score Contextual Relevancy (%) | Avg Score Hallucination (%) | Std Score Hallucination (%) |
|-------------------------|---------------------------|--------------------------------|--------------------------------|------------------------------------|------------------------------------|-----------------------------|-----------------------------|
| anthropic.claude-v3-opus | lexical_search_0_hop      | 83.47                          | 29.32                          | 63.91                              | 24.40                              | 21.88                       | 42.00                       |
| anthropic.claude-v3-opus | lexical_search_1_hop      | 94.50                          | 6.15                           | 73.44                              | 25.95                              | 48.28                       | 50.85                       |
| anthropic.claude-v3-opus | similarity_search_0_hop   | 90.24                          | 23.85                          | 63.58                              | 22.52                              | 30.30                       | 46.67                       |
| anthropic.claude-v3-opus | similarity_search_1_hop   | 83.48                          | 32.54                          | 70.21                              | 23.63                              | 40.63                       | 49.90                       |
| gemini-1.5-pro           | lexical_search_0_hop      | 98.73                          | 5.54                           | 86.17                              | 33.04                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | lexical_search_1_hop      | 98.93                          | 5.52                           | 84.06                              | 33.70                              | 2.50                        | 15.81                       |
| gemini-1.5-pro           | similarity_search_0_hop   | 99.43                          | 2.70                           | 86.00                              | 30.65                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | similarity_search_1_hop   | 94.36                          | 17.64                          | 83.39                              | 31.94                              | 7.50                        | 26.67                       |
| gpt-4o-2024-08-06        | lexical_search_0_hop      | 89.65                          | 25.34                          | 67.68                              | 30.52                              | 15.71                       | 36.47                       |
| gpt-4o-2024-08-06        | lexical_search_1_hop      | 92.58                          | 14.78                          | 69.04                              | 30.45                              | 34.38                       | 48.26                       |
| gpt-4o-2024-08-06        | similarity_search_0_hop   | 90.23                          | 23.83                          | 57.91                              | 30.79                              | 14.29                       | 35.50                       |
| gpt-4o-2024-08-06        | similarity_search_1_hop   | 87.78                          | 27.64                          | 61.89                              | 27.69                              | 34.29                       | 48.16                       |"""

In [48]:
from IPython.display import display, Markdown

display(Markdown(markdown_table))

| Model                   | Search Type               | Avg Score Answer Relevancy (%) | Std Score Answer Relevancy (%) | Avg Score Contextual Relevancy (%) | Std Score Contextual Relevancy (%) | Avg Score Hallucination (%) | Std Score Hallucination (%) |
|-------------------------|---------------------------|--------------------------------|--------------------------------|------------------------------------|------------------------------------|-----------------------------|-----------------------------|
| anthropic.claude-v3-opus | lexical_search_0_hop      | 83.47                          | 29.32                          | 63.91                              | 24.40                              | 21.88                       | 42.00                       |
| anthropic.claude-v3-opus | lexical_search_1_hop      | 94.50                          | 6.15                           | 73.44                              | 25.95                              | 48.28                       | 50.85                       |
| anthropic.claude-v3-opus | similarity_search_0_hop   | 90.24                          | 23.85                          | 63.58                              | 22.52                              | 30.30                       | 46.67                       |
| anthropic.claude-v3-opus | similarity_search_1_hop   | 83.48                          | 32.54                          | 70.21                              | 23.63                              | 40.63                       | 49.90                       |
| gemini-1.5-pro           | lexical_search_0_hop      | 98.73                          | 5.54                           | 86.17                              | 33.04                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | lexical_search_1_hop      | 98.93                          | 5.52                           | 84.06                              | 33.70                              | 2.50                        | 15.81                       |
| gemini-1.5-pro           | similarity_search_0_hop   | 99.43                          | 2.70                           | 86.00                              | 30.65                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | similarity_search_1_hop   | 94.36                          | 17.64                          | 83.39                              | 31.94                              | 7.50                        | 26.67                       |
| gpt-4o-2024-08-06        | lexical_search_0_hop      | 89.65                          | 25.34                          | 67.68                              | 30.52                              | 15.71                       | 36.47                       |
| gpt-4o-2024-08-06        | lexical_search_1_hop      | 92.58                          | 14.78                          | 69.04                              | 30.45                              | 34.38                       | 48.26                       |
| gpt-4o-2024-08-06        | similarity_search_0_hop   | 90.23                          | 23.83                          | 57.91                              | 30.79                              | 14.29                       | 35.50                       |
| gpt-4o-2024-08-06        | similarity_search_1_hop   | 87.78                          | 27.64                          | 61.89                              | 27.69                              | 34.29                       | 48.16                       |

In [49]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_38812/1164691038.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()

,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,L0,0.903319,0.234975,0.662857,0.942857,0.732786,0.263219,0.674419,0.825581,0.196121,0.397412,0.666667,0.804598
1,L1,0.919840,0.177114,0.417582,0.961538,0.741560,0.251824,0.553957,0.848921,0.292517,0.456474,0.523810,0.707483

In [50]:
grouped_df.columns

Index(['search_type', 'avg_score_Answer Relevancy',
       'std_score_Answer Relevancy', 'success_rate_Answer Relevancy',
       'metric_success_rate_Answer Relevancy',
       'avg_score_Contextual Relevancy', 'std_score_Contextual Relevancy',
       'success_rate_Contextual Relevancy',
       'metric_success_rate_Contextual Relevancy', 'avg_score_Hallucination',
       'std_score_Hallucination', 'success_rate_Hallucination',
       'metric_success_rate_Hallucination'],
      dtype='object')

In [51]:
grouped_df[
    [
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].to_dict()

{'search_type': {0: 'L0', 1: 'L1'},
 'avg_score_Answer Relevancy': {0: 0.9033187532968989, 1: 0.9198404322651812},
 'std_score_Answer Relevancy': {0: 0.23497542288534112, 1: 0.1771141382655022},
 'avg_score_Contextual Relevancy': {0: 0.7327856693580018,
  1: 0.741560352527332},
 'std_score_Contextual Relevancy': {0: 0.2632193387868581,
  1: 0.25182366091885444},
 'avg_score_Hallucination': {0: 0.1961206896551724, 1: 0.2925170068027211},
 'std_score_Hallucination': {0: 0.39741219603568173, 1: 0.45647374384336353}}

In [52]:
df.groupby("test_name").count()

,consumer_id,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,success_Hallucination,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination,threshold_compliance_Answer Relevancy,threshold_compliance_Contextual Relevancy,threshold_compliance_Hallucination,question,model,search_type,hops
test_name,,,,,,,,,,,,,,,,,,,,
Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_0_hop,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_1_hop,5,5,4,5,5,4,5,5,4,5,5,4,5,5,5,5,5,5,5,5
Q1:anthropic.claude-v3-opus:lexical_search_0_hop,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Q1:anthropic.claude-v3-opus:lexical_search_1_hop,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Q1:gemini-1.5-pro:lexical_search_0_hop,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q8:gemini-1.5-pro:lexical_search_1_hop,5,5,2,5,5,2,5,5,2,5,5,2,5,5,5,5,5,5,5,5
Q8:gpt-4o-2024-08-06:lexical_search_0_hop,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Q8:gpt-4o-2024-08-06:lexical_search_1_hop,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Q8:llama-3-70b-instruct-awq:lexical_search_0_hop,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Q8:llama-3-70b-instruct-awq:lexical_search_1_hop,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5

In [53]:
df[(df["consumer_id"].isin(["Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv", "Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro-preview-0409_deepeval.csv"])) & (df["test_name"] == "Q7:gemini-1.5-pro:similarity_search_0_hop")]

Empty DataFrame
Columns: [consumer_id, test_name, metric_success_Answer Relevancy, metric_success_Contextual Relevancy, metric_success_Hallucination, score_Answer Relevancy, score_Contextual Relevancy, score_Hallucination, success_Answer Relevancy, success_Contextual Relevancy, success_Hallucination, threshold_Answer Relevancy, threshold_Contextual Relevancy, threshold_Hallucination, threshold_compliance_Answer Relevancy, threshold_compliance_Contextual Relevancy, threshold_compliance_Hallucination, question, model, search_type, hops]
Index: []

[0 rows x 21 columns]

In [54]:
test = df[(df["consumer_id"].isin(["Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv", "Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro-preview-0409_deepeval.csv"])) & (df["test_name"] == "Q7:gemini-1.5-pro:similarity_search_0_hop")].to_dict()

In [55]:
teste = df[(df["consumer_id"].isin(["Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv", "Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro-preview-0409_deepeval.csv"])) & (df["test_name"] == "Q7:gemini-1.5-pro:similarity_search_0_hop")]

In [56]:
teste[["consumer_id", "score_Answer Relevancy", "score_Contextual Relevancy", "score_Hallucination"]]

Empty DataFrame
Columns: [consumer_id, score_Answer Relevancy, score_Contextual Relevancy, score_Hallucination]
Index: []