# Create evaluation strategy

In [1]:
import os

def list_folders(relative_path):
    """Lists all folders in the specified directory given by a relative path.
    
    Args:
        relative_path (str): The relative path to the directory.
        
    Returns:
        list: A list of folder names in the specified directory.
    """
    
    # Get the absolute path from the relative path
    absolute_path = os.path.abspath(relative_path)
    
    # List all folders in the directory
    try:
        folder_list = [
            name for name in os.listdir(absolute_path)
            if os.path.isdir(os.path.join(absolute_path, name))
        ]
        return folder_list
    except FileNotFoundError:
        print(f"Directory '{relative_path}' does not exist.")
        return []
    except Exception as e:
        print(f"An error occurred: {e}")
        return []

# Example usage:
# Suppose you want to list folders in the 'example_directory' relative to the script location
# folders = list_folders('example_directory')
# print(folders)

In [2]:
!pwd

/home/baptvit/Documents/mestrado/master-experiments/evaluations

In [3]:
logs_dir_path = "/home/baptvit/Documents/mestrado/master-experiments/logs"
list_consumers_id = list_folders(logs_dir_path)

In [4]:
list_consumers_id

['Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625',
 'Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9153d023d',
 'Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-85685b6ac939',
 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32']

In [15]:
list_consumers_id = ['Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32']

In [16]:
logs_dir_path = f"/home/baptvit/Documents/mestrado/master-experiments/logs/{list_consumers_id[0]}"
list_models = list_folders(logs_dir_path)
list_models

['gemini-1.5-pro']

In [17]:
logs_dir_path = f"/home/baptvit/Documents/mestrado/master-experiments/logs/{list_consumers_id[0]}/{list_models[0]}"
list_experiments = list_folders(logs_dir_path)
list_experiments

['lexical_search_1_hop',
 'similarity_search_0_hop',
 'lexical_search_0_hop',
 'similarity_search_1_hop']

In [18]:
list_questions = []
for experiment in list_experiments:
    logs_dir_path = f"/home/baptvit/Documents/mestrado/master-experiments/logs/{list_consumers_id[0]}/{list_models[0]}/{experiment}"
    list_questions_experiment = list_folders(logs_dir_path)
    list_questions.extend(list_questions_experiment)

list_questions

['Q6:gemini-1.5-pro:lexical_search_1_hop',
 'Q8:gemini-1.5-pro:lexical_search_1_hop',
 'Q7:gemini-1.5-pro:lexical_search_1_hop',
 'Q5:gemini-1.5-pro:lexical_search_1_hop',
 'Q1:gemini-1.5-pro:lexical_search_1_hop',
 'Q4:gemini-1.5-pro:lexical_search_1_hop',
 'Q2:gemini-1.5-pro:lexical_search_1_hop',
 'Q3:gemini-1.5-pro:lexical_search_1_hop',
 'Q8:gemini-1.5-pro:similarity_search_0_hop',
 'Q5:gemini-1.5-pro:similarity_search_0_hop',
 'Q3:gemini-1.5-pro:similarity_search_0_hop',
 'Q7:gemini-1.5-pro:similarity_search_0_hop',
 'Q4:gemini-1.5-pro:similarity_search_0_hop',
 'Q1:gemini-1.5-pro:similarity_search_0_hop',
 'Q6:gemini-1.5-pro:similarity_search_0_hop',
 'Q2:gemini-1.5-pro:similarity_search_0_hop',
 'Q4:gemini-1.5-pro:lexical_search_0_hop',
 'Q1:gemini-1.5-pro:lexical_search_0_hop',
 'Q2:gemini-1.5-pro:lexical_search_0_hop',
 'Q6:gemini-1.5-pro:lexical_search_0_hop',
 'Q7:gemini-1.5-pro:lexical_search_0_hop',
 'Q3:gemini-1.5-pro:lexical_search_0_hop',
 'Q5:gemini-1.5-pro:lexical_search_0_hop',
 'Q8:gemini-1.5-pro:lexical_search_0_hop',
 'Q7:gemini-1.5-pro:similarity_search_1_hop',
 'Q5:gemini-1.5-pro:similarity_search_1_hop',
 'Q3:gemini-1.5-pro:similarity_search_1_hop',
 'Q6:gemini-1.5-pro:similarity_search_1_hop',
 'Q4:gemini-1.5-pro:similarity_search_1_hop',
 'Q2:gemini-1.5-pro:similarity_search_1_hop',
 'Q8:gemini-1.5-pro:similarity_search_1_hop',
 'Q1:gemini-1.5-pro:similarity_search_1_hop']

In [19]:
list_questions.sort()
list_questions

['Q1:gemini-1.5-pro:lexical_search_0_hop',
 'Q1:gemini-1.5-pro:lexical_search_1_hop',
 'Q1:gemini-1.5-pro:similarity_search_0_hop',
 'Q1:gemini-1.5-pro:similarity_search_1_hop',
 'Q2:gemini-1.5-pro:lexical_search_0_hop',
 'Q2:gemini-1.5-pro:lexical_search_1_hop',
 'Q2:gemini-1.5-pro:similarity_search_0_hop',
 'Q2:gemini-1.5-pro:similarity_search_1_hop',
 'Q3:gemini-1.5-pro:lexical_search_0_hop',
 'Q3:gemini-1.5-pro:lexical_search_1_hop',
 'Q3:gemini-1.5-pro:similarity_search_0_hop',
 'Q3:gemini-1.5-pro:similarity_search_1_hop',
 'Q4:gemini-1.5-pro:lexical_search_0_hop',
 'Q4:gemini-1.5-pro:lexical_search_1_hop',
 'Q4:gemini-1.5-pro:similarity_search_0_hop',
 'Q4:gemini-1.5-pro:similarity_search_1_hop',
 'Q5:gemini-1.5-pro:lexical_search_0_hop',
 'Q5:gemini-1.5-pro:lexical_search_1_hop',
 'Q5:gemini-1.5-pro:similarity_search_0_hop',
 'Q5:gemini-1.5-pro:similarity_search_1_hop',
 'Q6:gemini-1.5-pro:lexical_search_0_hop',
 'Q6:gemini-1.5-pro:lexical_search_1_hop',
 'Q6:gemini-1.5-pro:similarity_search_0_hop',
 'Q6:gemini-1.5-pro:similarity_search_1_hop',
 'Q7:gemini-1.5-pro:lexical_search_0_hop',
 'Q7:gemini-1.5-pro:lexical_search_1_hop',
 'Q7:gemini-1.5-pro:similarity_search_0_hop',
 'Q7:gemini-1.5-pro:similarity_search_1_hop',
 'Q8:gemini-1.5-pro:lexical_search_0_hop',
 'Q8:gemini-1.5-pro:lexical_search_1_hop',
 'Q8:gemini-1.5-pro:similarity_search_0_hop',
 'Q8:gemini-1.5-pro:similarity_search_1_hop']

In [20]:
logs_dir_path = f"/home/baptvit/Documents/mestrado/master-experiments/logs/{list_consumers_id[0]}/{list_models[0]}/{list_experiments[0]}/{list_questions[0]}"
list_exp = list_folders(logs_dir_path)
list_exp

Directory '/home/baptvit/Documents/mestrado/master-experiments/logs/Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32/gemini-1.5-pro/lexical_search_1_hop/Q1:gemini-1.5-pro:lexical_search_0_hop' does not exist.

[]

## Read each step as a dataframe

In [ ]:
BASE_DIR = "/home/baptvit/repositories/graphrag-on-fhir/logs"

OUTPUT_STEP = '{base_dir}/{consumer_id}/{experiment_number}/output_step.json'
SEARCH_STEP = '{base_dir}/{consumer_id}/{experiment_number}/search_step.json'
TOKEN_STEP = '{base_dir}/{consumer_id}/{experiment_number}/tokens_step.json'
TOOL_STEP = '{base_dir}/{consumer_id}/{experiment_number}/tool_step.json'

SAVE_INTERMEDIATE_DF = "/home/baptvit/repositories/graphrag-on-fhir/evaluations/data/silver/{consumer_id}.csv"

In [38]:
import pandas as pd

def generate_intermediate_dataframes(experiment_number, consumer_id, base_dir=BASE_DIR):
    df_output_step = pd.read_json(OUTPUT_STEP.format(base_dir=base_dir ,consumer_id=consumer_id, experiment_number=experiment_number))
    df_search_step = pd.read_json(SEARCH_STEP.format(base_dir=base_dir, consumer_id=consumer_id, experiment_number=experiment_number))
    df_token_step = pd.read_json(TOKEN_STEP.format(base_dir=base_dir, consumer_id=consumer_id, experiment_number=experiment_number))
    df_tool_step = pd.read_json(TOOL_STEP.format(base_dir=base_dir, consumer_id=consumer_id, experiment_number=experiment_number))

    df_1 = df_output_step.merge(df_search_step, on='experiment_id', suffixes=('_output_step', '_search_step'))
    df_2 = df_token_step.merge(df_tool_step, on='experiment_id', suffixes=('_token_step', '_tool_step'))
    df_final = df_1.merge(df_2, on='experiment_id')  
    return df_final

In [8]:
import pandas as pd

In [9]:
df_output_step = pd.read_json('/home/baptvit/repositories/master-experiments/logs/123456/output_step.json')
df_output_step

,experiment_id,timestamp,full_response,system_promt,input,output
0,123456,2024-12-07 14:47:32,{'input': 'Whats my current medication and how...,You are a dedicated and highly skilled FHIR Sp...,Whats my current medication and how should I t...,Here are your current active medications and i...

In [10]:
df_search_step = pd.read_json('/home/baptvit/repositories/master-experiments/logs/123456/search_step.json')
df_search_step

,experiment_id,timestamp,latency_s,query,similarity_threshold,k,embedding_model
0,123456,2024-12-07 14:47:28,0.074214,\n MATCH (n)\n W...,0.85,20,BAAI/bge-small-en-v1.5

In [11]:
df_token_step = pd.read_json('/home/baptvit/repositories/master-experiments/logs/123456/tokens_step.json')
df_token_step

,experiment_id,timestamp,total_cost,total_tokens,successful_requests,completion_tokens,prompt_tokens,total_time
0,123456,2024-12-07 14:47:32,0.010095,3084,2,318,2766,11.495523

In [12]:
df_tool_step = pd.read_json('/home/baptvit/repositories/master-experiments/logs/123456/tool_step.json')
df_tool_step

,experiment_id,timestamp,records,caracteres_count,pass_map_reduce,resource_type,main_keys,user_query,character_limit,strategy_name
0,123456,2024-12-07 14:47:28,"{""resourceType"": ""MedicationRequest"", ""id"": ""a...",7026,False,MedicationRequest,,current medication and instructions for usage,120000,LexicalSearch0HopStrategy

In [13]:
df_1 = df_output_step.merge(df_search_step, on='experiment_id', suffixes=('_output_step', '_search_step'))
df_1

,experiment_id,timestamp_output_step,full_response,system_promt,input,output,timestamp_search_step,latency_s,query,similarity_threshold,k,embedding_model
0,123456,2024-12-07 14:47:32,{'input': 'Whats my current medication and how...,You are a dedicated and highly skilled FHIR Sp...,Whats my current medication and how should I t...,Here are your current active medications and i...,2024-12-07 14:47:28,0.074214,\n MATCH (n)\n W...,0.85,20,BAAI/bge-small-en-v1.5

In [14]:
df_2 = df_token_step.merge(df_tool_step, on='experiment_id', suffixes=('_token_step', '_tool_step'))
df_2

,experiment_id,timestamp_token_step,total_cost,total_tokens,successful_requests,completion_tokens,prompt_tokens,total_time,timestamp_tool_step,records,caracteres_count,pass_map_reduce,resource_type,main_keys,user_query,character_limit,strategy_name
0,123456,2024-12-07 14:47:32,0.010095,3084,2,318,2766,11.495523,2024-12-07 14:47:28,"{""resourceType"": ""MedicationRequest"", ""id"": ""a...",7026,False,MedicationRequest,,current medication and instructions for usage,120000,LexicalSearch0HopStrategy

In [15]:
df_final = df_1.merge(df_2, on='experiment_id')
df_final.

SyntaxError: invalid syntax (2924964799.py, line 2)

In [ ]:
evalutions/data/silver

In [80]:
df_final.to_csv("/home/baptvit/repositories/master-experiments/evalutions/data/silver/123456.csv")

# Run functions

In [39]:
import pandas as pd

In [40]:
list_experiment_dataframes = []
for experiment in list_experiments:
    list_experiment_dataframes.append(generate_intermediate_dataframes(experiment, list_consumers_id[0]))

In [41]:
df_final = pd.concat(list_experiment_dataframes)
df_final

,experiment_id,timestamp_output_step,full_response,system_promt,input,output,timestamp_search_step,latency_s,query,similarity_threshold,...,total_time,timestamp_tool_step,records,caracteres_count,pass_map_reduce,resource_type,main_keys,user_query,character_limit,strategy_name
0,Q8:gemini-1.5-pro:similarity_search_0_hop,2024-12-13 20:11:02,{'input': 'Can you summarize my immunization h...,\nYou are an aplication that interprets Eletro...,Can you summarize my immunization history ?,You received the following immunizations at BL...,2024-12-13 20:10:52,0.022357,Similarity Search 0-Hop,0.83,...,13.069803,2024-12-13 20:10:52,A completed immunization was recorded for a pa...,24317,False,,immunization,,300000,SimilaritySearch0HopStrategy
0,Q6:gemini-1.5-pro:lexical_search_1_hop,2024-12-13 19:31:19,{'input': 'Can you provide a breakdown of my m...,\nYou are an aplication that interprets Eletro...,Can you provide a breakdown of my medical bills ?,"You have had a number of medical bills, let's ...",2024-12-13 19:30:32,0.008161,MATCH (n)\n WHERE toLower(n.nam...,0.82,...,50.260111,2024-12-13 19:30:32,{'Main health record': 'This is an active prof...,81864,False,Claim,,,300000,LexicalSearch1HopStrategy
0,Q4:gemini-1.5-pro:lexical_search_0_hop,2024-12-13 19:34:02,{'input': 'What are my recent laboratory value...,\nYou are an aplication that interprets Eletro...,"What are my recent laboratory values, what do ...",I can see that you have had several diagnostic...,2024-12-13 19:33:59,0.006905,\n MATCH (n)\n W...,0.82,...,6.700896,2024-12-13 19:33:59,Final diagnostic report: History and physical ...,19764,False,DiagnosticReport,,,300000,LexicalSearch0HopStrategy
0,Q7:gemini-1.5-pro:similarity_search_1_hop,2024-12-13 20:02:52,{'input': 'What procedures have I undergone re...,\nYou are an aplication that interprets Eletro...,"What procedures have I undergone recently, and...",You have undergone several procedures recently...,2024-12-13 20:02:46,0.018764,Similarity Search 1-Hop,0.83,...,9.716451,2024-12-13 20:02:46,{'Main health record': 'This was an outpatient...,9451,False,,"procedures, surgeries",,300000,SimilaritySearch1HopStrategy
0,Q1:gemini-1.5-pro:lexical_search_0_hop,2024-12-13 19:33:33,"{'input': ""What's my current medications and h...",\nYou are an aplication that interprets Eletro...,What's my current medications and how should I...,"Currently, you have an active medication: Fexo...",2024-12-13 19:33:26,0.020736,\n MATCH (n)\n W...,0.82,...,12.664573,2024-12-13 19:33:26,This is a stopped medication request for Penic...,2047,False,MedicationRequest,,,300000,LexicalSearch0HopStrategy
0,Q8:gemini-1.5-pro:lexical_search_1_hop,2024-12-13 19:32:01,{'input': 'Can you summarize my immunization h...,\nYou are an aplication that interprets Eletro...,Can you summarize my immunization history ?,You have received the following immunizations:...,2024-12-13 19:31:50,0.018011,MATCH (n)\n WHERE toLower(n.nam...,0.82,...,14.515450,2024-12-13 19:31:50,{'Main health record': 'DTaP immunization was ...,43791,False,Immunization,,,300000,LexicalSearch1HopStrategy
0,Q5:gemini-1.5-pro:similarity_search_1_hop,2024-12-13 20:01:28,{'input': 'Can you summarize my care plan hist...,\nYou are an aplication that interprets Eletro...,Can you summarize my care plan history ?,Here is a summary of your care plan history:\n...,2024-12-13 20:01:20,0.022017,Similarity Search 1-Hop,0.83,...,12.631990,2024-12-13 20:01:20,{'Main health record': 'This is a superseded c...,6879,False,,care plan history,,300000,SimilaritySearch1HopStrategy
0,Q5:gemini-1.5-pro:similarity_search_0_hop,2024-12-13 20:10:27,{'input': 'Can you summarize my care plan hist...,\nYou are an aplication that interprets Eletro...,Can you summarize my care plan history ?,I see three care plans in your records. \n\nTh...,2024-12-13 20:10:21,0.018145,Similarity Search 0-Hop,0.83,...,8.844445,2024-12-13 20:10:21,This is a superseded clinical note documenting...,2384,False,,care plan history,,300000,SimilaritySearch0HopStrategy
0,Q3:gemini-1.5-pro:similarity_search_1_hop,2024-12-13 20:00:56,{'input': 'Can you summarize my current medica...,\nYou are an aplication that interprets Eletro...,Can you summarize my current medical conditions ?,"Based on your electronic health records, here'...",2024-12-13 20:00:50,0.022205,Similarity Search 1-Hop,0.83,...,9.748612,2024-12-13 20:00:50,{'Main health record': 'The observation is a f...,5443,False,,"Conditions, observations",,300000,SimilaritySearch1HopStrategy
0,Q3:gemini-1.5-pro:similarity_search_0_hop,2024-12-13 20:09:52,{'input': 'Can you summarize my current medica...,\nYou are an aplication that interprets Eletro...,Can you summarize my current medical conditions ?,"Based on your medical records, here's a summar...",2024-12-13 20:09:47,0.024836,Similarity Search 0-Hop,0.83,...,8.127272,2024-12-13 20:09:47,The observation is a final blood pressure pane...,846,False,,"Conditions, observations",,300000,SimilaritySearch0HopStrategy
0,Q6:gemini-1.5-pro:similarity_search_1_hop,2024-12-13 20:02:40,{'input': 'Can you provide a breakdown of my m...,\nYou are an aplication that interprets Eletro...,Can you provide a breakdown of my medical bills ?,I can see you've had a range of medical encoun...,2024-12-13 20:01:34,0.022658,Similarity Search 1-Hop,0.83,...,69.472959,2024-12-13 20:02:37,This collection of health records details medi...,7214,True,,medical bills,,300000,SimilaritySearch1HopStrategy
0,Q7:gemini-1.5-pro:lexical_search_1_hop,2024-12-13 19:31:44,{'input': 'What procedures have I undergone re...,\nYou are an aplication that interprets Eletro...,"What procedures have I undergone recently, and...",You have undergone several procedures recently...,2024-12-13 19:31:24,0.003228,MATCH (n)\n WHERE toLower(n.nam...,0.82,...,23.548513,2024-12-13 19:31:24,{'Main health record': 'A Transthoracic echoca...,24554,False,Procedure,,,300000,LexicalSearch1HopStrategy
0,Q7:gemini-1.5-pro:similarity_search_0_hop,2024-12-13 20:10:47,{'input': 'What procedures have I undergone re...,\nYou are an aplication that interprets Eletro...,"What procedures have I undergone recently, and...",You have undergone several procedures recently...,2024-12-13 20:10:42,0.021097,Similarity Search 0-Hop,0.83,...,8.683884,2024-12-13 20:10:42,This was an outpatient encounter for problem (...,1491,False,,"procedures, surgeries",,300000,SimilaritySearch0HopStrategy
0,Q2:gemini-1.5-pro:lexical_search_0_hop,2024-12-13 19:33:44,"{'input': 'What are my documented allergies, a...",\nYou are an aplication that interprets Eletro...,"What are my documented allergies, and how seve...","You have several documented allergies, all rec...",2024-12-13 19:33:39,0.008931,\n MATCH (n)\n W...,0.82,...,9.360646,2024-12-13 19:33:39,"The patient has an active, confirmed allergy t...",1759,False,AllergyIntolerance,,,300000,LexicalSearch0HopStrategy
0,Q5:gemini-1.5-pro:lexical_search_1_hop,2024-12-13 19:30:27,{'input': 'Can you summarize my care plan hist...,\nYou are an aplication that interprets Eletro...,Can you summarize my care plan history ?,You have two care plans documented in your med...,2024-12-13 19:30:23,0.004877,MATCH (n)\n WHERE toLower(n.nam...,0.82,...,7.083942,2024-12-13 19:30:23,{'Main health record': 'Care Plan for Skin con...,2832,False,CarePlan,,,300000,LexicalSearch1HopStrategy
0,Q1:gemini-1.5-pro:lexical_search_1_hop,2024-12-13 19:29:40,"{'input': ""What's my current medications and h...",\nYou are an aplication that interprets Eletro...,What's my current medications and how should I...,You are currently taking Fexofenadine hydrochl...,2024-12-13 19:29:36,0.005109,MATCH (n)\n WHERE toLower(n.nam...,0.82,...,9.961788,2024-12-13 19:29:36,{'Main health record': 'This is a stopped medi...,7782,False,MedicationRequest,,,300000,LexicalSearch1HopStrategy
0,Q4:gemini-1.5-pro:similarity_search_1_hop,2024-12-13 20:01:14,{'input': 'What are my recent laboratory value...,\nYou are an aplication that interprets Eletro...,"What are my recent laboratory values, what do ...",You had a CBC (Complete Blood Count) panel don...,2024-12-13 20:01:01,0.024555,Similarity Search 1-Hop,0.83,...,15.641761,2024-12-13 20:01:01,"{'Main health record': 'The observation, perfo...",40663,False,,Lab Results,,300000,SimilaritySearch1HopStrategy
0,Q4:gemini-1.5-pro:lexical_search_1_hop,2024-12-13 19:30:17,{'input': 'What are my recent laboratory value...,\nYou are an aplication that interprets Eletro...,"What are my recent laboratory values, what do ...","Your laboratory report dated February 28, 2021...",2024-12-13 19:30:10,0.006770,MATCH (n)\n WHERE toLower(n.nam...,0.82,...,10.692760,2024-12-13 19:30:10,{'Main health record': 'Final diagnostic repor...,37991,False,DiagnosticReport,,,300000,LexicalSearch1HopStrategy
0,Q2:gemini-1.5-pro:similarity_search_1_hop,2024-12-13 20:00:44,"{'input': 'What are my documented allergies, a...",\nYou are an aplication that interprets Eletro...,"What are my documented allergies, and how seve...","You have the following documented allergies, a...",2024-12-13 20:00:36,0.054833,Similarity Search 1-Hop,0.83,...,12.134726,2024-12-13 20:00:36,{'Main health record': 'The patient has an act...,99388,False,,allergies,,300000,SimilaritySearch1HopStrategy
0,Q4:gemini-1.5-pro:similarity_search_0_hop,2024-12-13 20:10:16,{'input': 'What are my recent laboratory value...,\nYou are an aplication that interprets Eletro...,"What are my recent laboratory values, what do ...",Your laboratory results show a variety of valu...,2024-12-13 20:09:57,0.019532,Similarity Search 0-Hop,0.83,...,21.693372,2024-12-13 20:09:57,"The observation, performed in a laboratory set...",5800,False,,Lab Results,,300000,SimilaritySearch0HopStrategy
0,Q8:gemini-1.5-pro:similarity_search_1_hop,2024-12-13 20:03:04,{'input': 'Can you summarize my immunization h...,\nYou are an aplication that interprets Eletro...,Can you summarize my immunization history ?,You received the following immunizations: Hib ...,2024-12-13 20:02:57,0.019892,Similarity Search 1-Hop,0.83,...,10.541687,2024-12-13 20:02:57,{'Main health record': 'A completed immunizati...,92930,False,,immunization,,300000,SimilaritySearch1HopStrategy
0,Q1:gemini-1.5-pro:similarity_search_0_hop,2024-12-13 20:09:29,"{'input': ""What's my current medications and h...",\nYou are an aplication that interprets Eletro...,What's my current medications and how should I...,The provided medical records mention these med...,2024-12-13 20:09:26,0.042972,Similarity Search 0-Hop,0.83,...,12.145475,2024-12-13 20:09:26,Final diagnostic report for a 7-year-old Hispa...,38697,False,,medications,,300000,SimilaritySearch0HopStrategy
0,Q2:gemini-1.5-pro:lexical_search_1_hop,2024-12-13 19:29:48,"{'input': 'What are my documented allergies, a...",\nYou are an aplication that interprets Eletro...,"What are my documented allergies, and how seve...","You have several documented allergies, all rec...",2024-12-13 19:29:45,0.004295,MATCH (n)\n WHERE toLower(n.nam...,0.82,...,6.266042,2024-12-13 19:29:45,{'Main health record': 'The patient has an act...,2272,False,AllergyIntolerance,,,300000,LexicalSearch1HopStrategy
0,Q6:gemini-1.5-pro:similarity_search_0_hop,2024-12-13 20:10:36,{'input': 'Can you provide a breakdown of my m...,\nYou are an aplication that interprets Eletro...,Can you provide a breakdown of my medical bills ?,You have had several medical encounters that r...,2024-12-13 20:10:32,0.025358,Similarity Search 0-Hop,0.83,...,7.835416,2024-12-13 20:10:32,This is a professional claim for medical care ...,68797,False,,medical bills,,300000,SimilaritySearch0HopStrategy
0,Q6:gemini-1.5-pro:lexical_search_0_hop,2024-12-13 19:34:24,{'input': 'Can you provide a breakdown of my m...,\nYou are an aplication that interprets Eletro...,Can you provide a breakdown of my medical bills ?,Here's a summary of your medical bills based o...,2024-12-13 19:34:15,0.008088,\n MATCH (n)\n W...,0.82,...,12.025005,2024-12-13 19:34:15,This is an active professional claim for Beatr...,19938,False,Claim,,,300000,LexicalSearch0HopStrategy
0,Q1:gemini-1.5-pro:similarity_search_1_hop,2024-12-13 20:00:30,"{'input': ""What's my current medications and h...",\nYou are an aplication that interprets Eletro...,What's my current medications and how should I...,You are currently taking penicillin V potassiu...,2024-12-13 20:00:27,0.040763,Similarity Search 1-Hop,0.83,...,11.067180,2024-12-13 20:00:27,{'Main health record': 'Final diagnostic repor...,95403,False,,medications,,300000,SimilaritySearch1HopStrategy
0,Q2:gemini-1.5-pro:similarity_search_0_hop,2024-12-13 20:09:42,"{'input': 'What are my documented allergies, a...",\nYou are an aplication that interprets Eletro...,"What are my documented allergies, and how seve...","You have the following documented allergies, a...",2024-12-13 20:09:35,0.038962,Similarity Search 0-Hop,0.83,...,10.493358,2024-12-13 20:09:35,"The patient has an active, confirmed allergy t...",38129,False,,allergies,,300000,SimilaritySearch0HopStrategy
0,Q3:gemini-1.5-pro:lexical_search_1_hop,2024-12-13 19:30:05,{'input': 'Can you summarize my current medica...,\nYou are an aplication that interprets Eletro...,Can you summarize my current medical conditions ?,You have a history of several medical conditio...,2024-12-13 19:29:53,0.003531,MATCH (n)\n WHERE toLower(n.nam...,0.82,...,14.882003,2024-12-13 19:29:53,{'Main health record': 'The patient has an act...,33451,False,Condition,,,300000,LexicalSearch1HopStrategy
0,Q7:gemini-1.5-pro:lexical_search_0_hop,2024-12-13 19:34:37,{'input': 'What procedures have I undergone re...,\nYou are an aplication that interprets Eletro...,"What procedures have I undergone recently, and...",You have undergone several procedures recently...,2024-12-13 19:34:30,0.009110,\n MATCH (n)\n W...,0.82,...,10.590203,2024-12-13 19:34:30,A Transthoracic echocardiography procedure was...,3217,False,Procedure,,,300000,LexicalSearch0HopStrategy
0,Q3:gemini-1.5-pro:lexical_search_0_hop,2024-12-13 19:33:53,{'input': 'Can you summarize my current medica...,\nYou are an aplication that interprets Eletro...,Can you summarize my current medical conditions ?,You currently have the following active medica...,2024-12-13 19:33:49,0.013496,\n MATCH (n)\n W...,0.82,...,7.202590,2024-12-13 19:33:49,"The patient has an active, confirmed diagnosis...",3336,False,Condition,,,300000,LexicalSearch0HopStrategy
0,Q5:gemini-1.5-pro:lexical_search_0_hop,2024-12-13 19:34:10,{'input': 'Can you summarize my care plan hist...,\nYou are an aplication that interprets Eletro...,Can you summarize my care plan history ?,You have two care plans on file. \n\nThe first...,2024-12-13 19:34:07,0.006888,\n MATCH (n)\n W...,0.82,...,6.187727,2024-12-13 19:34:07,Care Plan for Skin condition care. Care plan i...,680,False,CarePlan,,,300000,LexicalSearch0HopStrategy
0,Q8:gemini-1.5-pro:lexical_search_0_hop,2024-12-13 19:34:53,{'input': 'Can you summarize my immunization h...,\nYou are an aplication that interprets Eletro...,Can you summarize my immunization history ?,Your immunization records indicate that you ha...,2024-12-13 19:34:42,0.006974,\n MATCH (n)\n W...,0.82,...,14.380065,2024-12-13 19:34:42,"DTaP immunization was given on October 9, 2016...",6412,False,Immunization,,,300000,LexicalSearch0HopStrategy

In [42]:
df_final.to_csv(SAVE_INTERMEDIATE_DF.format(consumer_id=list_consumers_id[0]))

# Full version

In [21]:
import pandas as pd
import os

BASE_DIR = "/home/baptvit/Documents/mestrado/master-experiments/logs"
EVAL_DIR = "/home/baptvit/Documents/mestrado/master-experiments/evaluations/data/silver"

OUTPUT_STEP = '{base_dir}/{consumer_id}/{model_id}/{experiment_id}/{question_id}/output_step.json'
SEARCH_STEP = '{base_dir}/{consumer_id}/{model_id}/{experiment_id}/{question_id}/search_step.json'
TOKEN_STEP = '{base_dir}/{consumer_id}/{model_id}/{experiment_id}/{question_id}/tokens_step.json'
TOOL_STEP = '{base_dir}/{consumer_id}/{model_id}/{experiment_id}/{question_id}/tool_step.json'

SAVE_INTERMEDIATE_DF = os.path.join(EVAL_DIR, "{consumer_id}.csv")

In [22]:
def generate_intermediate_dataframes(list_consumers_id, list_models, list_experiments, list_questions, base_dir=BASE_DIR):
    all_dfs = []
    for consumer_id in list_consumers_id:
        for model_id in list_models:
            for experiment_id in list_experiments:
                for question_id in list_questions:
                    if experiment_id in question_id and model_id in question_id:
                        try:
                            output_path = OUTPUT_STEP.format(base_dir=base_dir, consumer_id=consumer_id, model_id=model_id, experiment_id=experiment_id, question_id=question_id)
                            search_path = SEARCH_STEP.format(base_dir=base_dir, consumer_id=consumer_id, model_id=model_id, experiment_id=experiment_id, question_id=question_id)
                            token_path = TOKEN_STEP.format(base_dir=base_dir, consumer_id=consumer_id, model_id=model_id, experiment_id=experiment_id, question_id=question_id)
                            tool_path = TOOL_STEP.format(base_dir=base_dir, consumer_id=consumer_id, model_id=model_id, experiment_id=experiment_id, question_id=question_id)
    
                            df_output_step = pd.read_json(output_path)
                            df_search_step = pd.read_json(search_path)
                            df_token_step = pd.read_json(token_path)
                            df_tool_step = pd.read_json(tool_path)
    
                            df_1 = df_output_step.merge(df_search_step, on='experiment_id', suffixes=('_output_step', '_search_step'))
                            df_2 = df_token_step.merge(df_tool_step, on='experiment_id', suffixes=('_token_step', '_tool_step'))
                            df_final = df_1.merge(df_2, on='experiment_id')
                            all_dfs.append(df_final)
    
                        except FileNotFoundError:
                            print(f"Files not found for: {output_path}, {search_path}, {token_path} e {tool_path}")
                            continue # Skip to the next combination if files are missing
                        except pd.errors.EmptyDataError:
                            print(f"Empty JSON files for: Consumer: {consumer_id}, Model: {model_id}, Experiment: {experiment_id}, Question: {question_id}")
                            continue
                        except KeyError as e:
                            print(f"KeyError: {e} in files for: Consumer: {consumer_id}, Model: {model_id}, Experiment: {experiment_id}, Question: {question_id}. Check if 'experiment_id' exists in all dataframes.")
                            continue
                        except Exception as e:
                            print(e)
    if all_dfs:
        final_df = pd.concat(all_dfs, ignore_index=True)
        return final_df
    else:
      return pd.DataFrame() # Return empty dataframe if no data was processed

In [23]:
# Example usage (assuming you have your lists defined):
# list_consumers_id = ["consumer1", "consumer2"]
# list_models = ["modelA", "modelB"]
# list_experiments = ["exp1", "exp2"]
# list_questions = ["q1", "q2"]

final_df = generate_intermediate_dataframes(list_consumers_id, list_models, list_experiments, list_questions)

# if not final_df.empty:
#     for consumer_id in list_consumers_id:
#         consumer_df = final_df[final_df['consumer_id'].astype(str).str.contains(consumer_id, case=False, na=False)]

#         if not consumer_df.empty:
#             save_path = SAVE_INTERMEDIATE_DF.format(consumer_id=consumer_id)
#             os.makedirs(EVAL_DIR, exist_ok=True) # Create directory if it doesn't exist
#             consumer_df.to_csv(save_path, index=False)
#             print(f"Saved CSV for {consumer_id} to {save_path}")
#         else:
#             print(f"No data found for consumer {consumer_id}")
# else:
#     print("No data was processed. Check your input lists and file paths.")

In [24]:
final_df.to_csv(SAVE_INTERMEDIATE_DF.format(consumer_id=list_consumers_id[0]))