# Remove fail evalutions

In [1]:
PATH = "/home/baptvit/repositories/graphrag-on-fhir/evaluations/data/gold/**gemini-1.5-pro-preview-0409_deepeval.csv"

In [144]:
import glob

taget_files = glob.glob(PATH)

In [145]:
taget_files

['/home/baptvit/repositories/graphrag-on-fhir/evaluations/data/gold/Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-gemini-1.5-pro-preview-0409_deepeval.csv',
 '/home/baptvit/repositories/graphrag-on-fhir/evaluations/data/gold/Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-gemini-1.5-pro-preview-0409_deepeval.csv',
 '/home/baptvit/repositories/graphrag-on-fhir/evaluations/data/gold/Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9153d023d-gemini-1.5-pro-preview-0409_deepeval.csv',
 '/home/baptvit/repositories/graphrag-on-fhir/evaluations/data/gold/Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro-preview-0409_deepeval.csv']

## Run here

In [4]:
import pandas as pd

for file in taget_files:
    df = pd.read_csv(file)  
    final_df = df[(df["error"].isna()) | (df["error"] == "Request body is too large")] 
    final_df['retrieval_context'] = ""
    final_df.to_csv(file, header=True)

## Testing here

In [166]:
file_path = taget_files[0]
file_path

'/home/baptvit/repositories/graphrag-on-fhir/evaluations/data/gold/Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-gemini-1.5-pro-preview-0409_deepeval.csv'

In [167]:
import pandas as pd

df = pd.read_csv(file_path)

In [168]:
df["error"].unique()

array([nan])

In [169]:
df["test_name"].unique()

array(['Q1:gemini-1.5-pro:similarity_search_0_hop',
       'Q6:gemini-1.5-pro:similarity_search_0_hop',
       'Q5:gemini-1.5-pro:similarity_search_0_hop',
       'Q8:gemini-1.5-pro:similarity_search_0_hop',
       'Q2:gemini-1.5-pro:lexical_search_2_hop',
       'Q4:gemini-1.5-pro:lexical_search_2_hop',
       'Q8:gemini-1.5-pro:lexical_search_2_hop',
       'Q4:gemini-1.5-pro:lexical_search_1_hop',
       'Q5:gemini-1.5-pro:lexical_search_1_hop',
       'Q7:gemini-1.5-pro:lexical_search_1_hop'], dtype=object)

In [170]:
final_df = df[(df["error"].isna()) | (df["error"] == "Request body is too large")]

In [171]:
#final_df.to_csv("/home/baptvit/repositories/graphrag-on-fhir/evaluations/data/gold/test_Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-gemini-1.5-pro-preview-0409_deepeval.csv", header=True)

In [172]:
test = pd.read_csv(file_path)

In [173]:
test.columns

Index(['Unnamed: 0', 'consumer_id', 'test_name', 'success', 'metric_name',
       'threshold', 'metric_success', 'score', 'reason', 'strict_mode',
       'evaluation_model', 'error', 'evaluation_cost', 'verbose_logs',
       'conversational', 'multimodal', 'input', 'actual_output',
       'expected_output', 'context', 'retrieval_context'],
      dtype='object')

In [174]:
test = test[['consumer_id', 'test_name', 'success', 'metric_name',
       'threshold', 'metric_success', 'score', 'reason', 'strict_mode',
       'evaluation_model', 'error', 'evaluation_cost', 'verbose_logs',
       'conversational', 'multimodal', 'input', 'actual_output',
       'expected_output', 'context', 'retrieval_context']]
test

,consumer_id,test_name,success,metric_name,threshold,metric_success,score,reason,strict_mode,evaluation_model,error,evaluation_cost,verbose_logs,conversational,multimodal,input,actual_output,expected_output,context,retrieval_context
0,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q1:gemini-1.5-pro:similarity_search_0_hop,True,Hallucination,0.5,True,0.000000,The score is 0.00 because the actual output al...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,What's my current medications and how should I...,I found 38 records of medication requests in y...,NaN,NaN,NaN
1,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q1:gemini-1.5-pro:similarity_search_0_hop,True,Answer Relevancy,0.5,True,1.000000,The score is 1.00 because the response appropr...,False,Custom Azure OpenAI Model,NaN,NaN,"Statements:\n[\n ""I found 38 records of med...",False,False,What's my current medications and how should I...,I found 38 records of medication requests in y...,NaN,NaN,NaN
2,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q1:gemini-1.5-pro:similarity_search_0_hop,True,Contextual Relevancy,0.5,True,0.900000,The score is 0.90 because while the retrieved ...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdicts"": [\n ...",False,False,What's my current medications and how should I...,I found 38 records of medication requests in y...,NaN,NaN,NaN
3,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q6:gemini-1.5-pro:similarity_search_0_hop,False,Hallucination,0.5,True,0.000000,The score is 0.00 because the actual output al...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,Can you provide a breakdown of my medical bills ?,I can tell you about some of your medical bill...,NaN,NaN,NaN
4,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q6:gemini-1.5-pro:similarity_search_0_hop,False,Answer Relevancy,0.5,True,1.000000,The score is 1.00 because the response is rele...,False,Custom Azure OpenAI Model,NaN,NaN,"Statements:\n[\n ""I can tell you about some...",False,False,Can you provide a breakdown of my medical bills ?,I can tell you about some of your medical bill...,NaN,NaN,NaN
5,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:gemini-1.5-pro:similarity_search_0_hop,False,Hallucination,0.5,True,0.000000,The score is 0.00 because the actual output al...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,Can you summarize my care plan history ?,Your care plan history includes several instan...,NaN,NaN,NaN
6,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:gemini-1.5-pro:similarity_search_0_hop,False,Answer Relevancy,0.5,True,1.000000,The score is 1.00 because the response is rele...,False,Custom Azure OpenAI Model,NaN,NaN,"Statements:\n[\n ""Your care plan history in...",False,False,Can you summarize my care plan history ?,Your care plan history includes several instan...,NaN,NaN,NaN
7,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:gemini-1.5-pro:similarity_search_0_hop,False,Contextual Relevancy,0.5,False,0.400000,The score is 0.40 because while the context in...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdicts"": [\n ...",False,False,Can you summarize my care plan history ?,Your care plan history includes several instan...,NaN,NaN,NaN
8,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q8:gemini-1.5-pro:similarity_search_0_hop,True,Hallucination,0.5,True,0.000000,The score is 0.00 because the output correctly...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,Can you summarize my immunization history ?,Your immunization history shows you received t...,NaN,NaN,NaN
9,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q8:gemini-1.5-pro:similarity_search_0_hop,True,Answer Relevancy,0.5,True,1.000000,The score is 1.00 because the response provide...,False,Custom Azure OpenAI Model,NaN,NaN,"Statements:\n[\n ""Your immunization history...",False,False,Can you summarize my immunization history ?,Your immunization history shows you received t...,NaN,NaN,NaN
10,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q8:gemini-1.5-pro:similarity_search_0_hop,True,Contextual Relevancy,0.5,True,0.823529,The score is 0.82 because while a substantial ...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdicts"": [\n ...",False,False,Can you summarize my immunization history ?,Your immunization history shows you received t...,NaN,NaN,NaN
11,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q2:gemini-1.5-pro:lexical_search_2_hop,False,Hallucination,0.5,True,0.000000,The score is 0.00 because the actual output co...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,"What are my documented allergies, and how seve...",I did not find any documented allergies for yo...,NaN,NaN,NaN
12,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q2:gemini-1.5-pro:lexical_search_2_hop,False,Answer Relevancy,0.5,True,1.000000,The score is 1.00 because the response effecti...,False,Custom Azure OpenAI Model,NaN,NaN,"Statements:\n[\n ""I did not find any docume...",False,False,"What are my documented allergies, and how seve...",I did not find any documented allergies for yo...,NaN,NaN,NaN
13,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q2:gemini-1.5-pro:lexical_search_2_hop,False,Contextual Relevancy,0.5,False,0.000000,The score is 0.00 because none of the retrieve...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdicts"": [\n ...",False,False,"What are my documented allergies, and how seve...",I did not find any documented allergies for yo...,NaN,NaN,NaN
14,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q4:gemini-1.5-pro:lexical_search_2_hop,False,Answer Relevancy,0.5,True,1.000000,The score is 1.00 because the response effecti...,False,Custom Azure OpenAI Model,NaN,NaN,"Statements:\n[\n ""I'm sorry, I cannot find ...",False,False,"What are my recent laboratory values, what do ...","I'm sorry, I cannot find any laboratory values...",NaN,NaN,NaN
15,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q8:gemini-1.5-pro:lexical_search_2_hop,False,Answer Relevancy,0.5,True,1.000000,The score is 1.00 because the response is rele...,False,Custom Azure OpenAI Model,NaN,NaN,"Statements:\n[\n ""You received the seasonal...",False,False,Can you summarize my immunization history ?,You received the seasonal influenza vaccine on...,NaN,NaN,NaN
16,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q4:gemini-1.5-pro:lexical_search_1_hop,False,Hallucination,0.5,True,0.000000,The score is 0.00 because the output aligns wi...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,"What are my recent laboratory values, what do ...",Please provide me your recent laboratory repor...,NaN,NaN,NaN
17,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q4:gemini-1.5-pro:lexical_search_1_hop,False,Answer Relevancy,0.5,True,1.000000,The score is 1.00 because there are no irrelev...,False,Custom Azure OpenAI Model,NaN,NaN,"Statements:\n[\n ""Please provide me your re...",False,False,"What are my recent laboratory values, what do ...",Please provide me your recent laboratory repor...,NaN,NaN,NaN
18,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:gemini-1.5-pro:lexical_search_1_hop,True,Hallucination,0.5,True,0.000000,The score is 0.00 because the actual output fu...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,Can you summarize my care plan history ?,You have three care plans in your record. \n\n...,NaN,NaN,NaN
19,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:gemini-1.5-pro:lexical_search_1_hop,True,Answer Relevancy,0.5,True,1.000000,"The score is 1.00, indicating a perfect releva...",False,Custom Azure OpenAI Model,NaN,NaN,"Statements:\n[\n ""You have three care plans...",False,False,Can you summarize my care plan history ?,You have three care plans in your record. \n\n...,NaN,NaN,NaN
20,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:gemini-1.5-pro:lexical_search_1_hop,True,Contextual Relevancy,0.5,True,1.000000,The score is 1.00 because the retrieval contex...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdicts"": [\n ...",False,False,Can you summarize my care plan history ?,You have three care plans in your record. \n\n...,NaN,NaN,NaN
21,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q7:gemini-1.5-pro:lexical_search_1_hop,False,Hallucination,0.5,True,0.000000,The score is 0.00 because the actual output fu...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,"What procedures have I undergone recently, and...",You have undergone several procedures recently...,NaN,NaN,NaN
22,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q7:gemini-1.5-pro:lexical_search_1_hop,False,Answer Relevancy,0.5,True,1.000000,It appears there is no irrelevant information ...,False,Custom Azure OpenAI Model,NaN,NaN,"Statements:\n[\n ""You have undergone severa...",False,False,"What procedures have I undergone recently, and...",You have undergone several procedures recently...,NaN,NaN,NaN

In [175]:
test["consumer_id"].unique()

array(['Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32'],
      dtype=object)

In [154]:
df_renamed = test[test["consumer_id"] != "Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625"]

In [155]:
df_renamed.columns

Index(['consumer_id', 'test_name', 'success', 'metric_name', 'threshold',
       'metric_success', 'score', 'reason', 'strict_mode', 'evaluation_model',
       'error', 'evaluation_cost', 'verbose_logs', 'conversational',
       'multimodal', 'input', 'actual_output', 'expected_output', 'context',
       'retrieval_context'],
      dtype='object')

In [157]:
df_renamed.columns = ['test_name', 'success', 'metric_name', 'threshold',
       'metric_success', 'score', 'reason', 'strict_mode', 'evaluation_model',
       'error', 'evaluation_cost', 'verbose_logs', 'conversational',
       'multimodal', 'input', 'actual_output', 'expected_output', 'context',
       'retrieval_context', 'exclude columns']

In [158]:
df_1 = df_renamed[['test_name', 'success', 'metric_name', 'threshold',
       'metric_success', 'score', 'reason', 'strict_mode', 'evaluation_model',
       'error', 'evaluation_cost', 'verbose_logs', 'conversational',
       'multimodal', 'input', 'actual_output', 'expected_output', 'context',
       'retrieval_context']]

In [160]:
df_1['consumer_id'] = "Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625"

In [161]:
df_2 = test[test["consumer_id"] == "Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625"]

In [162]:
frames = [df_1, df_2]

In [163]:
df_final = pd.concat(frames)

In [164]:
df_final["test_name"].unique()

array(['Q6:gemini-1.5-pro:similarity_search_0_hop',
       'Q5:gemini-1.5-pro:similarity_search_0_hop',
       'Q8:gemini-1.5-pro:similarity_search_0_hop',
       'Q7:gemini-1.5-pro:similarity_search_0_hop',
       'Q3:gemini-1.5-pro:similarity_search_0_hop',
       'Q4:gemini-1.5-pro:similarity_search_0_hop',
       'Q2:gemini-1.5-pro:similarity_search_0_hop',
       'Q1:gemini-1.5-pro:similarity_search_0_hop',
       'Q4:gemini-1.5-pro:lexical_search_1_hop',
       'Q5:gemini-1.5-pro:lexical_search_1_hop',
       'Q7:gemini-1.5-pro:lexical_search_1_hop',
       'Q2:gemini-1.5-pro:lexical_search_1_hop',
       'Q8:gemini-1.5-pro:lexical_search_1_hop',
       'Q3:gemini-1.5-pro:lexical_search_1_hop',
       'Q1:gemini-1.5-pro:lexical_search_1_hop',
       'Q6:gemini-1.5-pro:lexical_search_1_hop',
       'Q8:gemini-1.5-pro:lexical_search_0_hop',
       'Q3:gemini-1.5-pro:lexical_search_0_hop',
       'Q2:gemini-1.5-pro:lexical_search_0_hop',
       'Q6:gemini-1.5-pro:lexical_search_0_hop',
       'Q5:gemini-1.5-pro:lexical_search_0_hop',
       'Q7:gemini-1.5-pro:lexical_search_0_hop',
       'Q4:gemini-1.5-pro:lexical_search_0_hop',
       'Q1:gemini-1.5-pro:lexical_search_0_hop',
       'Q2:gemini-1.5-pro:similarity_search_1_hop',
       'Q5:gemini-1.5-pro:similarity_search_1_hop',
       'Q8:gemini-1.5-pro:similarity_search_1_hop',
       'Q7:gemini-1.5-pro:similarity_search_1_hop',
       'Q1:gemini-1.5-pro:similarity_search_1_hop'], dtype=object)

In [125]:
df_false = test[test["test_name"] == "False"]
df_false.columns

Index(['consumer_id', 'test_name', 'success', 'metric_name', 'threshold',
       'metric_success', 'score', 'reason', 'strict_mode', 'evaluation_model',
       'error', 'evaluation_cost', 'verbose_logs', 'conversational',
       'multimodal', 'input', 'actual_output', 'expected_output', 'context',
       'retrieval_context'],
      dtype='object')

In [128]:
df_false.columns = ['test_name', 'success', 'metric_name', 'threshold',
       'metric_success', 'score', 'reason', 'strict_mode', 'evaluation_model',
       'error', 'evaluation_cost', 'verbose_logs', 'conversational',
       'multimodal', 'input', 'actual_output', 'expected_output', 'context',
       'retrieval_context', 'delete']
df_false.head()

,test_name,success,metric_name,threshold,metric_success,score,reason,strict_mode,evaluation_model,error,evaluation_cost,verbose_logs,conversational,multimodal,input,actual_output,expected_output,context,retrieval_context,delete
33,Q8:gemini-1.5-pro:lexical_search_1_hop,False,Hallucination,0.5,True,0.0,The score is 0.00 because all information prov...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,Can you summarize my immunization history ?,You have received the following immunizations:...,NaN,{'Main health record': 'Resource Type: Immuniz...,{'Main health record': 'Resource Type: Immuniz...,NaN
34,Q8:gemini-1.5-pro:lexical_search_1_hop,False,Answer Relevancy,0.5,True,1.0,"The score is 1.00, indicating a perfectly rele...",False,Custom Azure OpenAI Model,NaN,NaN,"Statements:\n[\n ""You have received the fol...",False,False,Can you summarize my immunization history ?,You have received the following immunizations:...,NaN,{'Main health record': 'Resource Type: Immuniz...,{'Main health record': 'Resource Type: Immuniz...,NaN
35,Q8:gemini-1.5-pro:lexical_search_1_hop,False,Contextual Relevancy,0.5,False,NaN,NaN,False,Custom Azure OpenAI Model,Evaluation LLM outputted an invalid JSON. Plea...,NaN,NaN,False,False,Can you summarize my immunization history ?,You have received the following immunizations:...,NaN,{'Main health record': 'Resource Type: Immuniz...,{'Main health record': 'Resource Type: Immuniz...,NaN
36,Q3:gemini-1.5-pro:lexical_search_1_hop,False,Hallucination,0.5,True,0.0,The score is 0.00 because the actual output al...,False,Custom Azure OpenAI Model,NaN,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,Can you summarize my current medical conditions ?,This is a summary of your medical conditions:\...,NaN,{'Main health record': 'Clinical Status: Resol...,{'Main health record': 'Clinical Status: Resol...,NaN
37,Q3:gemini-1.5-pro:lexical_search_1_hop,False,Answer Relevancy,0.5,True,0.9464285714285714,The score is 0.95 because while the response i...,False,Custom Azure OpenAI Model,NaN,NaN,"Statements:\n[\n ""This is a summary of your...",False,False,Can you summarize my current medical conditions ?,This is a summary of your medical conditions:\...,NaN,{'Main health record': 'Clinical Status: Resol...,{'Main health record': 'Clinical Status: Resol...,NaN

In [131]:
df_true = test[test["test_name"] == "True"]
df_true.columns = ['test_name', 'success', 'metric_name', 'threshold',
       'metric_success', 'score', 'reason', 'strict_mode', 'evaluation_model',
       'error', 'evaluation_cost', 'verbose_logs', 'conversational',
       'multimodal', 'input', 'actual_output', 'expected_output', 'context',
       'retrieval_context', 'delete']

In [132]:
frames = [df_1, df_2, df_false, df_true]

In [133]:
df_final_2 = pd.concat(frames)

In [134]:
df_final_2["test_name"].unique()

array(['Q8:gemini-1.5-pro:lexical_search_1_hop',
       'Q3:gemini-1.5-pro:lexical_search_1_hop',
       'Q1:gemini-1.5-pro:lexical_search_1_hop',
       'Q6:gemini-1.5-pro:lexical_search_1_hop',
       'Q8:gemini-1.5-pro:lexical_search_0_hop',
       'Q3:gemini-1.5-pro:lexical_search_0_hop',
       'Q2:gemini-1.5-pro:lexical_search_0_hop',
       'Q6:gemini-1.5-pro:lexical_search_0_hop',
       'Q5:gemini-1.5-pro:lexical_search_0_hop',
       'Q7:gemini-1.5-pro:lexical_search_0_hop',
       'Q4:gemini-1.5-pro:lexical_search_0_hop',
       'Q1:gemini-1.5-pro:lexical_search_0_hop',
       'Q2:gemini-1.5-pro:similarity_search_1_hop',
       'Q5:gemini-1.5-pro:similarity_search_1_hop',
       'Q8:gemini-1.5-pro:similarity_search_1_hop',
       'Q7:gemini-1.5-pro:similarity_search_1_hop',
       'Q1:gemini-1.5-pro:similarity_search_1_hop',
       'Q3:gemini-1.5-pro:similarity_search_1_hop',
       'Q4:gemini-1.5-pro:similarity_search_1_hop',
       'Q6:gemini-1.5-pro:similarity_search_1_hop',
       'Q7:gemini-1.5-pro:similarity_search_0_hop',
       'Q3:gemini-1.5-pro:similarity_search_0_hop',
       'Q4:gemini-1.5-pro:similarity_search_0_hop',
       'Q2:gemini-1.5-pro:similarity_search_0_hop',
       'Q1:gemini-1.5-pro:similarity_search_0_hop',
       'Q6:gemini-1.5-pro:similarity_search_0_hop',
       'Q5:gemini-1.5-pro:similarity_search_0_hop',
       'Q8:gemini-1.5-pro:similarity_search_0_hop',
       'Q4:gemini-1.5-pro:lexical_search_1_hop',
       'Q5:gemini-1.5-pro:lexical_search_1_hop',
       'Q7:gemini-1.5-pro:lexical_search_1_hop',
       'Q2:gemini-1.5-pro:lexical_search_1_hop'], dtype=object)

In [135]:
df_final_2.head()

,test_name,success,metric_name,threshold,metric_success,score,reason,strict_mode,evaluation_model,error,...,verbose_logs,conversational,multimodal,input,actual_output,expected_output,context,retrieval_context,consumer_id,delete
33,Q8:gemini-1.5-pro:lexical_search_1_hop,False,Hallucination,0.5,True,0.0,The score is 0.00 because all information prov...,False,Custom Azure OpenAI Model,NaN,...,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,Can you summarize my immunization history ?,You have received the following immunizations:...,NaN,{'Main health record': 'Resource Type: Immuniz...,{'Main health record': 'Resource Type: Immuniz...,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,NaN
34,Q8:gemini-1.5-pro:lexical_search_1_hop,False,Answer Relevancy,0.5,True,1.0,"The score is 1.00, indicating a perfectly rele...",False,Custom Azure OpenAI Model,NaN,...,"Statements:\n[\n ""You have received the fol...",False,False,Can you summarize my immunization history ?,You have received the following immunizations:...,NaN,{'Main health record': 'Resource Type: Immuniz...,{'Main health record': 'Resource Type: Immuniz...,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,NaN
35,Q8:gemini-1.5-pro:lexical_search_1_hop,False,Contextual Relevancy,0.5,False,NaN,NaN,False,Custom Azure OpenAI Model,Evaluation LLM outputted an invalid JSON. Plea...,...,NaN,False,False,Can you summarize my immunization history ?,You have received the following immunizations:...,NaN,{'Main health record': 'Resource Type: Immuniz...,{'Main health record': 'Resource Type: Immuniz...,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,NaN
36,Q3:gemini-1.5-pro:lexical_search_1_hop,False,Hallucination,0.5,True,0.0,The score is 0.00 because the actual output al...,False,Custom Azure OpenAI Model,NaN,...,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,Can you summarize my current medical conditions ?,This is a summary of your medical conditions:\...,NaN,{'Main health record': 'Clinical Status: Resol...,{'Main health record': 'Clinical Status: Resol...,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,NaN
37,Q3:gemini-1.5-pro:lexical_search_1_hop,False,Answer Relevancy,0.5,True,0.9464285714285714,The score is 0.95 because while the response i...,False,Custom Azure OpenAI Model,NaN,...,"Statements:\n[\n ""This is a summary of your...",False,False,Can you summarize my current medical conditions ?,This is a summary of your medical conditions:\...,NaN,{'Main health record': 'Clinical Status: Resol...,{'Main health record': 'Clinical Status: Resol...,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,NaN

In [165]:
df_final.to_csv(file_path, header=True)

In [52]:
file_path = "/home/baptvit/repositories/graphrag-on-fhir/evaluations/data/gold/Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c62563f6bbce1a32-gemini-1.5-pro-preview-0409_deepeval.csv"

In [53]:
test_1 = pd.read_csv(file_path)

In [56]:
test_1 = test_1[['consumer_id', 'test_name', 'success', 'metric_name',
       'threshold', 'metric_success', 'score', 'reason', 'strict_mode',
       'evaluation_model', 'error', 'evaluation_cost', 'verbose_logs',
       'conversational', 'multimodal', 'input', 'actual_output',
       'expected_output', 'context', 'retrieval_context']]

In [55]:
test_1["test_name"].unique()

array(['Q7:gemini-1.5-pro:similarity_search_0_hop',
       'Q3:gemini-1.5-pro:similarity_search_0_hop',
       'Q4:gemini-1.5-pro:similarity_search_0_hop',
       'Q2:gemini-1.5-pro:similarity_search_0_hop',
       'Q1:gemini-1.5-pro:similarity_search_0_hop',
       'Q3:gemini-1.5-pro:lexical_search_1_hop',
       'Q1:gemini-1.5-pro:lexical_search_1_hop',
       'Q6:gemini-1.5-pro:lexical_search_1_hop',
       'Q8:gemini-1.5-pro:lexical_search_0_hop',
       'Q3:gemini-1.5-pro:lexical_search_0_hop',
       'Q2:gemini-1.5-pro:lexical_search_0_hop',
       'Q6:gemini-1.5-pro:lexical_search_0_hop',
       'Q5:gemini-1.5-pro:lexical_search_0_hop',
       'Q7:gemini-1.5-pro:lexical_search_0_hop',
       'Q4:gemini-1.5-pro:lexical_search_0_hop',
       'Q1:gemini-1.5-pro:lexical_search_0_hop',
       'Q2:gemini-1.5-pro:similarity_search_1_hop',
       'Q5:gemini-1.5-pro:similarity_search_1_hop',
       'Q8:gemini-1.5-pro:similarity_search_1_hop',
       'Q7:gemini-1.5-pro:similarity_search_1_hop',
       'Q1:gemini-1.5-pro:similarity_search_1_hop', 'False', 'True'],
      dtype=object)

In [60]:
frames = [test, test_1]

In [61]:
df_final = pd.concat(frames)

In [63]:
df_final["test_name"].sort_values().unique()

array(['False', 'Q1:gemini-1.5-pro:lexical_search_0_hop',
       'Q1:gemini-1.5-pro:lexical_search_1_hop',
       'Q1:gemini-1.5-pro:similarity_search_0_hop',
       'Q1:gemini-1.5-pro:similarity_search_1_hop',
       'Q2:gemini-1.5-pro:lexical_search_0_hop',
       'Q2:gemini-1.5-pro:lexical_search_1_hop',
       'Q2:gemini-1.5-pro:similarity_search_0_hop',
       'Q2:gemini-1.5-pro:similarity_search_1_hop',
       'Q3:gemini-1.5-pro:lexical_search_0_hop',
       'Q3:gemini-1.5-pro:lexical_search_1_hop',
       'Q3:gemini-1.5-pro:similarity_search_0_hop',
       'Q4:gemini-1.5-pro:lexical_search_0_hop',
       'Q4:gemini-1.5-pro:lexical_search_1_hop',
       'Q4:gemini-1.5-pro:similarity_search_0_hop',
       'Q5:gemini-1.5-pro:lexical_search_0_hop',
       'Q5:gemini-1.5-pro:lexical_search_1_hop',
       'Q5:gemini-1.5-pro:similarity_search_0_hop',
       'Q5:gemini-1.5-pro:similarity_search_1_hop',
       'Q6:gemini-1.5-pro:lexical_search_0_hop',
       'Q6:gemini-1.5-pro:lexical_search_1_hop',
       'Q6:gemini-1.5-pro:similarity_search_0_hop',
       'Q7:gemini-1.5-pro:lexical_search_0_hop',
       'Q7:gemini-1.5-pro:lexical_search_1_hop',
       'Q7:gemini-1.5-pro:similarity_search_0_hop',
       'Q7:gemini-1.5-pro:similarity_search_1_hop',
       'Q8:gemini-1.5-pro:lexical_search_0_hop',
       'Q8:gemini-1.5-pro:lexical_search_1_hop',
       'Q8:gemini-1.5-pro:similarity_search_0_hop',
       'Q8:gemini-1.5-pro:similarity_search_1_hop', 'True'], dtype=object)

In [64]:
taget_files[2]

'/home/baptvit/repositories/graphrag-on-fhir/evaluations/data/gold/Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-gemini-1.5-pro-preview-0409_deepeval.csv'

In [65]:
df_final.to_csv(taget_files[2], header=True)

In [44]:
df_final.to_csv(taget_files[2], header=True)