# Analysis for the deepeval metrics

In [54]:
gold_source = (
    "/home/baptvit/Documents/github/graphrag-on-fhir/evaluations/data/gold/deepeval/"
)

In [55]:
import glob
import os

import pandas as pd

all_files = glob.glob(os.path.join(gold_source, "*.csv"))

all_dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df["consumer_id"] = file.split("/")[-1]
    all_dfs.append(df)


df_gold = pd.concat(all_dfs, ignore_index=True)

In [56]:
df_gold.columns

Index(['Unnamed: 0', 'test_name', 'success', 'metric_name', 'threshold',
       'metric_success', 'score', 'reason', 'strict_mode', 'evaluation_model',
       'error', 'evaluation_cost', 'verbose_logs', 'conversational',
       'multimodal', 'input', 'actual_output', 'expected_output', 'context',
       'retrieval_context', 'consumer_id'],
      dtype='object')

In [57]:
df_5 = df_gold[
    [
        "consumer_id",
        "test_name",
        "success",
        "metric_name",
        "threshold",
        "metric_success",
        "score",
        "reason",
    ]
].head()

In [58]:
df_5.to_dict()

{'consumer_id': {0: 'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv',
  1: 'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv',
  2: 'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv',
  3: 'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv',
  4: 'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv'},
 'test_name': {0: 'Q6:gemini-1.5-pro:lexical_search_1_hop',
  1: 'Q6:gemini-1.5-pro:lexical_search_1_hop',
  2: 'Q6:gemini-1.5-pro:lexical_search_1_hop',
  3: 'Q8:gemini-1.5-pro:lexical_search_1_hop',
  4: 'Q8:gemini-1.5-pro:lexical_search_1_hop'},
 'success': {0: True, 1: True, 2: True, 3: True, 4: True},
 'metric_name': {0: 'Hallucination',
  1: 'Answer Relevancy',
  2: 'Contextual Relevancy',
  3: 'Hallucination',
  4: 'Answer Relevancy'},
 'threshold': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'metric_success': {0: True, 1: True, 2: True, 3: True, 4: True},
 'score': {0: 0.0, 1: 1.0, 2: 1.0, 3: 0.0, 4: 1.0},
 'reason': {0: 'The score is 0.00 because the actual output accurately summarizes the key information from each medical bill, aligning perfectly with the provided contexts and containing no contradictions.',
  1: "The score is 1.00 because, given the lack of context/information, the response appropriately asks clarifying questions to better address the user's request to break down medical bills.  There were no irrelevant statements made, and the response stays focused and on-topic, which maintains the high score.",
  2: 'The score is 1.00 because the retrieval context contains statements directly related to medical claims and bills, which is exactly what the user is asking for. The context includes various claim details, such as claim IDs, dates, amounts, types, statuses, and descriptions of services. Perfect match!',
  3: 'The score is 0.00 because the output correctly summarizes the immunization records provided in the context, aligning with all factual information and presenting no contradictions.',
  4: "The score is 1.00 because there were no irrelevant statements made and the response was relevant and concise, addressing all parts of the user's prompt/question."}}

In [59]:
# Create DataFrame
df = df_gold

# Create the pivot table
pivot = pd.pivot_table(
    df,
    values=["success", "threshold", "metric_success", "score"],
    index=["consumer_id", "test_name"],
    columns=["metric_name"],
    aggfunc="first",  # Use 'first' to get the value as is since duplicates are unlikely
)

# Optional: Flatten the column multi-index for cleaner display
pivot.columns = ["_".join(col).strip() for col in pivot.columns.values]
pivot.reset_index(inplace=True)

# Display the pivot table
pivot

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,success_Hallucination,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:lexical_search_0_hop,False,True,True,0.000000,0.500000,0.0,False,False,False,0.5,0.5,0.5
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:lexical_search_1_hop,True,False,False,0.964286,0.400000,1.0,False,False,False,0.5,0.5,0.5
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:similarity_search_...,True,False,False,1.000000,0.333333,1.0,False,False,False,0.5,0.5,0.5
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:similarity_search_...,True,False,False,0.931034,0.333333,1.0,False,False,False,0.5,0.5,0.5
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:anthropic.claude-v3-opus:lexical_search_0_hop,True,True,True,0.960000,0.714286,0.0,True,True,True,0.5,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:gpt-4o-2024-08-06:similarity_search_1_hop,True,True,False,0.781250,0.700000,1.0,False,False,False,0.5,0.5,0.5
444,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
445,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:lexical_search_1_hop,True,True,True,0.961538,0.933333,0.0,True,True,True,0.5,0.5,0.5
446,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:similarity_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
447,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:similarity_search_1_hop,True,True,True,0.714286,0.875000,0.0,True,True,True,0.5,0.5,0.5

In [60]:
pivot.to_csv(
    "/home/baptvit/Documents/mestrado/master-experiments/evaluations/data/gold/Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58_deepeval_results.csv"
)

In [61]:
pivot.head().to_dict()

{'consumer_id': {0: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-anthropic.claude-v3-opus_deepeval.csv',
  1: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-anthropic.claude-v3-opus_deepeval.csv',
  2: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-anthropic.claude-v3-opus_deepeval.csv',
  3: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-anthropic.claude-v3-opus_deepeval.csv',
  4: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-anthropic.claude-v3-opus_deepeval.csv'},
 'test_name': {0: 'Q1:anthropic.claude-v3-opus:lexical_search_0_hop',
  1: 'Q1:anthropic.claude-v3-opus:lexical_search_1_hop',
  2: 'Q1:anthropic.claude-v3-opus:similarity_search_0_hop',
  3: 'Q1:anthropic.claude-v3-opus:similarity_search_1_hop',
  4: 'Q2:anthropic.claude-v3-opus:lexical_search_0_hop'},
 'metric_success_Answer Relevancy': {0: False,
  1: True,
  2: True,
  3: True,
  4: True},
 'metric_success_Contextual Relevancy': {0: True,
  1: False,
  2: False,
  3: False,
  4: True},
 'metric_success_Hallucination': {0: True,
  1: False,
  2: False,
  3: False,
  4: True},
 'score_Answer Relevancy': {0: 0.0,
  1: 0.9642857142857144,
  2: 1.0,
  3: 0.9310344827586208,
  4: 0.96},
 'score_Contextual Relevancy': {0: 0.5,
  1: 0.4,
  2: 0.3333333333333333,
  3: 0.3333333333333333,
  4: 0.7142857142857143},
 'score_Hallucination': {0: 0.0, 1: 1.0, 2: 1.0, 3: 1.0, 4: 0.0},
 'success_Answer Relevancy': {0: False, 1: False, 2: False, 3: False, 4: True},
 'success_Contextual Relevancy': {0: False,
  1: False,
  2: False,
  3: False,
  4: True},
 'success_Hallucination': {0: False, 1: False, 2: False, 3: False, 4: True},
 'threshold_Answer Relevancy': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'threshold_Contextual Relevancy': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'threshold_Hallucination': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5}}

In [62]:
df = pivot
# Analysis 1: Overall success rates by metric
success_rates = (
    df[
        [
            "metric_success_Answer Relevancy",
            "metric_success_Contextual Relevancy",
            "metric_success_Hallucination",
        ]
    ].mean()
    * 100
)

print("Overall Success Rates by Metric (%):")
print(success_rates)

# Analysis 2: Average scores by metric
average_scores = df[
    ["score_Answer Relevancy", "score_Contextual Relevancy", "score_Hallucination"]
].mean()

print("\nAverage Scores by Metric:")
print(average_scores)


# Analysis 3: Threshold compliance (scores >= threshold)
def threshold_compliance(row, metric):
    return row[f"score_{metric}"] >= row[f"threshold_{metric}"]


for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
    df[f"threshold_compliance_{metric}"] = df.apply(
        threshold_compliance, axis=1, metric=metric
    )

threshold_compliance_rates = (
    df[
        [
            "threshold_compliance_Answer Relevancy",
            "threshold_compliance_Contextual Relevancy",
            "threshold_compliance_Hallucination",
        ]
    ].mean()
    * 100
)

print("\nThreshold Compliance Rates by Metric (%):")
print(threshold_compliance_rates)

# Analysis 4: Breakdown by test_name
breakdown = df.groupby(["consumer_id", "test_name"]).mean()

print("\nBreakdown by Test Name:")
print(breakdown)

Overall Success Rates by Metric (%):
metric_success_Answer Relevancy        94.419643
metric_success_Contextual Relevancy    77.678571
metric_success_Hallucination           76.339286
dtype: float64

Average Scores by Metric:
score_Answer Relevancy        0.921893
score_Contextual Relevancy    0.728764
score_Hallucination           0.189870
dtype: float64

Threshold Compliance Rates by Metric (%):
threshold_compliance_Answer Relevancy        94.419643
threshold_compliance_Contextual Relevancy    77.678571
threshold_compliance_Hallucination           17.857143
dtype: float64

Breakdown by Test Name:
                                                                                                       metric_success_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                                0.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                                1.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                              1.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                              1.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                                1.0
...                                                                                                                                ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                                    1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                       1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                       1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                                    1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                                    1.0

                                                                                                       metric_success_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                                    1.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                                    0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                                  0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                                  0.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                                    1.0
...                                                                                                                                    ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                                        1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                           1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                           1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                                        1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                                        1.0

                                                                                                       metric_success_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                             1.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                             0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                           0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                           0.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                             1.0
...                                                                                                                             ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                                 0.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                    1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                    1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                                 1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                                 1.0

                                                                                                       score_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                  0.000000
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                  0.964286
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                1.000000
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                0.931034
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                  0.960000
...                                                                                                                       ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                      0.781250
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                         1.000000
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                         0.961538
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                      1.000000
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                      0.714286

                                                                                                       score_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                      0.500000
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                      0.400000
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                    0.333333
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                    0.333333
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                      0.714286
...                                                                                                                           ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                          0.700000
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                             1.000000
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                             0.933333
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                          1.000000
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                          0.875000

                                                                                                       score_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                    0.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                    1.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                  1.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                  1.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                    0.0
...                                                                                                                    ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                        1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                           0.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                           0.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                        0.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                        0.0

                                                                                                       success_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                         0.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                         0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                       0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                       0.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                         1.0
...                                                                                                                         ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                             0.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                             1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                             1.0

                                                                                                       success_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                             0.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                             0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                           0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                           0.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                             1.0
...                                                                                                                             ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                                 0.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                    1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                    1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                                 1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                                 1.0

                                                                                                       success_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                      0.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                      0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                    0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                    0.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                      1.0
...                                                                                                                      ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                          0.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                             1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                             1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                          1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                          1.0

                                                                                                       threshold_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                           0.5
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                           0.5
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                         0.5
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                         0.5
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                           0.5
...                                                                                                                           ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                               0.5
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                  0.5
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                  0.5
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                               0.5
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                               0.5

                                                                                                       threshold_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                               0.5
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                               0.5
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                             0.5
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                             0.5
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                               0.5
...                                                                                                                               ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                                   0.5
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                      0.5
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                      0.5
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                                   0.5
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                                   0.5

                                                                                                       threshold_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                        0.5
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                        0.5
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                      0.5
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                      0.5
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                        0.5
...                                                                                                                        ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                            0.5
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                               0.5
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                               0.5
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                            0.5

In [63]:
df = pivot

df[["question", "model", "search_type"]] = df["test_name"].str.split(":", expand=True)

In [64]:
df["hops"] = df["test_name"].str[-5:]

In [65]:
df["hops"] = df["hops"].str.replace("_hop", "", regex=False).astype(int)

In [66]:
df = df.replace("anthropic.claude-v3-5-sonnet-v2", "anthropic.claude-v3-opus")
df = df.replace("gpt-4o-2024-11-20", "gpt-4o-2024-08-06")

In [67]:
df

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,...,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination,threshold_compliance_Answer Relevancy,threshold_compliance_Contextual Relevancy,threshold_compliance_Hallucination,question,model,search_type,hops
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:lexical_search_0_hop,False,True,True,0.000000,0.500000,0.0,False,False,...,0.5,0.5,0.5,False,True,False,Q1,anthropic.claude-v3-opus,lexical_search_0_hop,0
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:lexical_search_1_hop,True,False,False,0.964286,0.400000,1.0,False,False,...,0.5,0.5,0.5,True,False,True,Q1,anthropic.claude-v3-opus,lexical_search_1_hop,1
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:similarity_search_...,True,False,False,1.000000,0.333333,1.0,False,False,...,0.5,0.5,0.5,True,False,True,Q1,anthropic.claude-v3-opus,similarity_search_0_hop,0
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:similarity_search_...,True,False,False,0.931034,0.333333,1.0,False,False,...,0.5,0.5,0.5,True,False,True,Q1,anthropic.claude-v3-opus,similarity_search_1_hop,1
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:anthropic.claude-v3-opus:lexical_search_0_hop,True,True,True,0.960000,0.714286,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q2,anthropic.claude-v3-opus,lexical_search_0_hop,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:gpt-4o-2024-08-06:similarity_search_1_hop,True,True,False,0.781250,0.700000,1.0,False,False,...,0.5,0.5,0.5,True,True,True,Q7,gpt-4o-2024-08-06,similarity_search_1_hop,1
444,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,gpt-4o-2024-08-06,lexical_search_0_hop,0
445,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:lexical_search_1_hop,True,True,True,0.961538,0.933333,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,gpt-4o-2024-08-06,lexical_search_1_hop,1
446,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:similarity_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,gpt-4o-2024-08-06,similarity_search_0_hop,0
447,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:similarity_search_1_hop,True,True,True,0.714286,0.875000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,gpt-4o-2024-08-06,similarity_search_1_hop,1

In [68]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = (
    df.groupby(["consumer_id", "question", "search_type", "hops"])
    .apply(analyze_metrics)
    .reset_index()
)
grouped_df

/tmp/ipykernel_37154/833737725.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(analyze_metrics)

,consumer_id,question,search_type,hops,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,lexical_search_0_hop,0,0.000000,0.0,0.0,0.500000,0.0,1.0,0.0,0.0,1.0
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,lexical_search_1_hop,1,0.964286,0.0,1.0,0.400000,0.0,0.0,1.0,0.0,0.0
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,similarity_search_0_hop,0,1.000000,0.0,1.0,0.333333,0.0,0.0,1.0,0.0,0.0
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,similarity_search_1_hop,1,0.931034,0.0,1.0,0.333333,0.0,0.0,1.0,0.0,0.0
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2,lexical_search_0_hop,0,0.960000,1.0,1.0,0.714286,1.0,1.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
443,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7,similarity_search_1_hop,1,0.781250,0.0,1.0,0.700000,0.0,1.0,1.0,0.0,0.0
444,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,lexical_search_0_hop,0,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
445,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,lexical_search_1_hop,1,0.961538,1.0,1.0,0.933333,1.0,1.0,0.0,1.0,1.0
446,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,similarity_search_0_hop,0,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
447,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,similarity_search_1_hop,1,0.714286,1.0,1.0,0.875000,1.0,1.0,0.0,1.0,1.0

In [69]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = (
    df.groupby(["consumer_id", "search_type"]).apply(analyze_metrics).reset_index()
)
grouped_df

/tmp/ipykernel_37154/1437396366.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(["consumer_id", "search_type"]).apply(analyze_metrics).reset_index()

,consumer_id,search_type,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_0_hop,0.771987,0.625,0.875,0.681324,0.625,0.875,0.125000,0.625,0.875
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_1_hop,0.973637,0.125,1.000,0.773810,0.125,0.750,0.857143,0.125,0.125
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_0_hop,0.986392,0.500,1.000,0.678175,0.500,0.875,0.500000,0.500,0.500
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_1_hop,0.852109,0.250,0.875,0.663889,0.250,0.875,0.750000,0.250,0.250
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_0_hop,1.000000,0.750,1.000,0.712897,0.750,0.750,0.000000,0.750,1.000
5,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_1_hop,1.000000,0.875,1.000,0.822674,0.875,0.875,0.000000,0.875,1.000
6,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_0_hop,0.995787,1.000,1.000,0.995748,1.000,1.000,0.000000,1.000,1.000
7,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_1_hop,1.000000,1.000,1.000,1.000000,1.000,1.000,0.000000,1.000,1.000
8,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_0_hop,0.921972,0.875,1.000,0.711837,0.875,0.875,0.140625,0.875,0.875
9,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_1_hop,0.939804,0.500,1.000,0.737408,0.500,0.625,0.166667,0.500,0.625
10,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_0_hop,0.932692,0.250,0.500,0.690476,0.250,0.375,0.250000,0.250,0.375
11,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_1_hop,0.841071,0.375,0.875,0.674576,0.375,0.875,0.625000,0.375,0.375
12,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_0_hop,0.792707,0.750,0.875,0.747069,0.750,1.000,0.250000,0.750,0.750
13,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_1_hop,0.912143,0.875,1.000,0.744731,0.875,1.000,0.125000,0.875,0.875
14,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_0_hop,0.889891,0.875,1.000,0.654167,0.875,0.875,0.000000,0.875,1.000
15,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_1_hop,0.773897,0.875,0.875,0.799206,0.875,1.000,0.000000,0.875,1.000
16,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_0_hop,0.977273,1.000,1.000,1.000000,1.000,1.000,0.000000,1.000,1.000
17,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_1_hop,1.000000,1.000,1.000,1.000000,1.000,1.000,0.000000,1.000,1.000
18,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_0_hop,1.000000,1.000,1.000,0.992647,1.000,1.000,0.000000,1.000,1.000
19,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_1_hop,0.806066,0.875,0.875,0.992647,0.875,1.000,0.000000,0.875,1.000
20,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_0_hop,0.914583,0.875,0.875,0.906944,0.875,1.000,0.000000,0.875,1.000
21,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_1_hop,0.869744,0.625,0.875,0.752232,0.625,0.875,0.250000,0.625,0.750
22,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_0_hop,0.773659,0.500,0.750,0.470062,0.500,0.625,0.000000,0.500,1.000
23,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_1_hop,0.912768,0.500,0.875,0.665307,0.500,0.875,0.285714,0.500,0.625
24,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_0_hop,0.819048,0.500,0.875,0.558333,0.500,0.625,0.250000,0.500,0.750
25,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_1_hop,0.934402,0.500,1.000,0.708532,0.500,0.875,0.375000,0.500,0.625
26,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_0_hop,0.864120,0.625,0.875,0.604911,0.625,0.875,0.250000,0.625,0.750
27,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_1_hop,0.817632,0.375,0.875,0.662392,0.375,0.875,0.500000,0.375,0.500
28,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_0_hop,0.961957,0.875,1.000,0.845588,0.875,0.875,0.000000,0.875,1.000
29,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_1_hop,0.997283,0.625,1.000,0.776786,0.625,0.750,0.125000,0.625,0.875
30,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_0_hop,0.979167,0.750,1.000,0.770115,0.750,0.750,0.000000,0.750,1.000
31,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_1_hop,0.973611,0.625,1.000,0.663690,0.625,0.625,0.125000,0.625,0.875
32,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_0_hop,1.000000,0.500,1.000,0.562500,0.500,0.750,0.250000,0.500,0.750
33,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_1_hop,0.978571,0.375,1.000,0.760169,0.375,0.875,0.500000,0.375,0.500
34,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_0_hop,0.973214,0.625,1.000,0.599702,0.625,0.750,0.125000,0.625,0.875
35,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_1_hop,0.989358,0.625,1.000,0.700000,0.625,0.875,0.250000,0.625,0.750
36,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_0_hop,0.955249,0.625,1.000,0.569792,0.625,0.750,0.250000,0.625,0.750
37,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_1_hop,0.956971,0.125,1.000,0.645833,0.125,0.375,0.500000,0.125,0.250
38,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_0_hop,0.856908,0.250,0.875,0.605975,0.250,0.750,0.500000,0.250,0.500
39,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_1_hop,0.875000,0.250,0.875,0.672123,0.250,0.625,0.500000,0.250,0.375
40,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_0_hop,1.000000,0.875,1.000,0.875000,0.875,0.875,0.000000,0.875,1.000
41,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_1_hop,0.949145,0.500,1.000,0.746377,0.500,0.500,0.000000,0.500,1.000
42,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_0_hop,1.000000,1.000,1.000,0.937500,1.000,1.000,0.000000,1.000,1.000
43,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_1_hop,0.940448,0.750,1.000,0.845307,0.750,0.875,0.250000,0.750,0.750
44,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_0_hop,0.943421,0.500,1.000,0.644841,0.500,0.625,0.142857,0.500,0.750
45,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_1_hop,0.949811,0.250,1.000,0.575758,0.250,0.250,0.250000,0.250,0.375
46,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_0_hop,0.985119,0.375,1.000,0.521357,0.375,0.500,0.285714,0.375,0.625
47,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_1_hop,0.853532,0.125,0.875,0.404611,0.125,0.250,0.200000,0.125,0.500
48,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_0_hop,0.997191,0.875,1.000,0.875000,0.875,0.875,0.000000,0.875,1.000
49,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_1_hop,1.000000,0.875,1.000,0.833703,0.875,0.875,0.000000,0.875,1.000
50,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_0_hop,0.996324,0.625,1.000,0.603808,0.625,0.625,0.000000,0.625,1.000
51,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_1_hop,0.998077,0.750,1.000,0.667724,0.750,0.750,0.000000,0.750,1.000
52,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_0_hop,0.702714,0.375,0.750,0.553686,0.375,0.625,0.250000,0.375,0.750
53,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_1_hop,0.890930,0.250,1.000,0.525000,0.250,0.500,0.500000,0.250,0.375
54,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_0_hop,0.861842,0.750,0.875,0.662504,0.750,0.750,0.125000,0.750,0.875
55,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_1_hop,0.792205,0.375,0.875,0.569384,0.375,0.625,0.285714,0.375,0.625

In [70]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_37154/3565463073.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()

,search_type,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,lexical_search_0_hop,0.911293,0.714286,0.946429,0.732555,0.714286,0.821429,0.118243,0.714286,0.875000
1,lexical_search_1_hop,0.953746,0.535714,0.991071,0.760110,0.535714,0.723214,0.242424,0.535714,0.669643
2,similarity_search_0_hop,0.935464,0.651786,0.919643,0.701065,0.651786,0.767857,0.140187,0.651786,0.821429
3,similarity_search_1_hop,0.887555,0.553571,0.919643,0.724325,0.553571,0.794643,0.266667,0.553571,0.687500

In [71]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["question"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_37154/1271303342.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["question"]).apply(analyze_metrics).reset_index()

,question,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Q1,0.844000,0.500000,0.875000,0.667007,0.500000,0.678571,0.236364,0.500000,0.750000
1,Q2,0.818040,0.428571,0.839286,0.394498,0.428571,0.446429,0.071429,0.428571,0.928571
2,Q3,0.906605,0.535714,0.964286,0.703784,0.535714,0.767857,0.233173,0.535714,0.714286
3,Q4,0.953109,0.535714,0.964286,0.723635,0.535714,0.750000,0.270833,0.535714,0.625000
4,Q5,0.988770,0.714286,0.982143,0.787787,0.714286,0.821429,0.132075,0.714286,0.821429
5,Q6,0.988343,0.535714,1.000000,0.796316,0.535714,0.857143,0.360000,0.535714,0.571429
6,Q7,0.919741,0.750000,0.946429,0.876438,0.750000,0.910714,0.169811,0.750000,0.785714
7,Q8,0.957537,0.910714,0.982143,0.902326,0.910714,0.982143,0.072727,0.910714,0.910714

In [72]:
df.columns

Index(['consumer_id', 'test_name', 'metric_success_Answer Relevancy',
       'metric_success_Contextual Relevancy', 'metric_success_Hallucination',
       'score_Answer Relevancy', 'score_Contextual Relevancy',
       'score_Hallucination', 'success_Answer Relevancy',
       'success_Contextual Relevancy', 'success_Hallucination',
       'threshold_Answer Relevancy', 'threshold_Contextual Relevancy',
       'threshold_Hallucination', 'threshold_compliance_Answer Relevancy',
       'threshold_compliance_Contextual Relevancy',
       'threshold_compliance_Hallucination', 'question', 'model',
       'search_type', 'hops'],
      dtype='object')

In [73]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["model", "search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_37154/913412050.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["model", "search_type"]).apply(analyze_metrics).reset_index()

,model,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,anthropic.claude-v3-opus,lexical_search_0_hop,0.834748,0.293249,0.62500,0.90625,0.639130,0.243989,0.62500,0.81250,0.218750,0.420013,0.62500,0.78125
1,anthropic.claude-v3-opus,lexical_search_1_hop,0.944288,0.063309,0.40625,1.00000,0.726893,0.266312,0.40625,0.75000,0.444444,0.506370,0.40625,0.46875
2,anthropic.claude-v3-opus,similarity_search_0_hop,0.899328,0.241642,0.56250,0.93750,0.635807,0.225213,0.56250,0.84375,0.312500,0.470929,0.56250,0.68750
3,anthropic.claude-v3-opus,similarity_search_1_hop,0.829659,0.329184,0.43750,0.87500,0.701221,0.240343,0.43750,0.84375,0.433333,0.504007,0.43750,0.53125
4,gemini-1.5-pro,lexical_search_0_hop,0.987284,0.055406,0.87500,1.00000,0.861697,0.330413,0.87500,0.87500,0.000000,0.000000,0.87500,1.00000
5,gemini-1.5-pro,lexical_search_1_hop,0.989285,0.055153,0.77500,1.00000,0.840620,0.336954,0.77500,0.80000,0.025000,0.158114,0.77500,0.97500
6,gemini-1.5-pro,similarity_search_0_hop,0.994255,0.027013,0.87500,1.00000,0.859964,0.306490,0.87500,0.87500,0.000000,0.000000,0.87500,1.00000
7,gemini-1.5-pro,similarity_search_1_hop,0.943641,0.176364,0.80000,0.97500,0.833874,0.319440,0.80000,0.85000,0.075000,0.266747,0.80000,0.92500
8,gpt-4o-2024-08-06,lexical_search_0_hop,0.896538,0.253433,0.62500,0.92500,0.676760,0.305238,0.62500,0.77500,0.157051,0.364680,0.62500,0.82500
9,gpt-4o-2024-08-06,lexical_search_1_hop,0.925772,0.147838,0.40000,0.97500,0.690353,0.304475,0.40000,0.62500,0.343750,0.482559,0.40000,0.52500
10,gpt-4o-2024-08-06,similarity_search_0_hop,0.902262,0.238283,0.50000,0.82500,0.579130,0.307893,0.50000,0.60000,0.142857,0.355036,0.50000,0.75000
11,gpt-4o-2024-08-06,similarity_search_1_hop,0.877787,0.276411,0.40000,0.90000,0.618929,0.276919,0.40000,0.70000,0.342857,0.481594,0.40000,0.57500

In [74]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_37154/1164691038.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()

,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,lexical_search_0_hop,0.911293,0.226959,0.714286,0.946429,0.732555,0.312053,0.714286,0.821429,0.118243,0.322824,0.714286,0.875000
1,lexical_search_1_hop,0.953746,0.103103,0.535714,0.991071,0.760110,0.312090,0.535714,0.723214,0.242424,0.430730,0.535714,0.669643
2,similarity_search_0_hop,0.935464,0.194445,0.651786,0.919643,0.701065,0.309070,0.651786,0.767857,0.140187,0.348815,0.651786,0.821429
3,similarity_search_1_hop,0.887555,0.264897,0.553571,0.919643,0.724325,0.296566,0.553571,0.794643,0.266667,0.444338,0.553571,0.687500

In [75]:
grouped_df.columns

Index(['search_type', 'avg_score_Answer Relevancy',
       'std_score_Answer Relevancy', 'success_rate_Answer Relevancy',
       'metric_success_rate_Answer Relevancy',
       'avg_score_Contextual Relevancy', 'std_score_Contextual Relevancy',
       'success_rate_Contextual Relevancy',
       'metric_success_rate_Contextual Relevancy', 'avg_score_Hallucination',
       'std_score_Hallucination', 'success_rate_Hallucination',
       'metric_success_rate_Hallucination'],
      dtype='object')

In [76]:
grouped_df[
    [
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].to_dict()

{'search_type': {0: 'lexical_search_0_hop',
  1: 'lexical_search_1_hop',
  2: 'similarity_search_0_hop',
  3: 'similarity_search_1_hop'},
 'avg_score_Answer Relevancy': {0: 0.9112929143097023,
  1: 0.9537456252668848,
  2: 0.9354644043070182,
  3: 0.887555303642846},
 'std_score_Answer Relevancy': {0: 0.22695893328153824,
  1: 0.10310299146538908,
  2: 0.19444520253657346,
  3: 0.2648968492740055},
 'avg_score_Contextual Relevancy': {0: 0.7325554553495729,
  1: 0.7601103491623294,
  2: 0.7010646654813596,
  3: 0.7243246464429465},
 'std_score_Contextual Relevancy': {0: 0.31205299217417126,
  1: 0.3120895071175935,
  2: 0.309070361509755,
  3: 0.2965655391627874},
 'avg_score_Hallucination': {0: 0.11824324324324324,
  1: 0.24242424242424243,
  2: 0.14018691588785046,
  3: 0.26666666666666666},
 'std_score_Hallucination': {0: 0.3228239378365471,
  1: 0.430730492253948,
  2: 0.3488146540013176,
  3: 0.4443375939934607}}