# Analysis for the deepeval metrics

In [1]:
gold_source = (
    "/home/baptvit/Documents/mestrado/master-experiments/evaluations/data/gold/deepeval/"
)

In [2]:
import glob
import os

import pandas as pd

all_files = glob.glob(os.path.join(gold_source, "*.csv"))

all_dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df["consumer_id"] = file.split("/")[-1]
    all_dfs.append(df)


df_gold = pd.concat(all_dfs, ignore_index=True)

In [3]:
df_gold.columns

Index(['Unnamed: 0', 'consumer_id', 'test_name', 'success', 'metric_name',
       'threshold', 'metric_success', 'score', 'reason', 'strict_mode',
       'evaluation_model', 'error', 'evaluation_cost', 'verbose_logs',
       'conversational', 'multimodal', 'input', 'actual_output',
       'expected_output', 'context', 'retrieval_context'],
      dtype='object')

In [4]:
df_5 = df_gold[
    [
        "consumer_id",
        "test_name",
        "success",
        "metric_name",
        "threshold",
        "metric_success",
        "score",
        "reason",
    ]
].head()

In [5]:
df_5.to_dict()

{'consumer_id': {0: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32_deepeval copy.csv',
  1: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32_deepeval copy.csv',
  2: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32_deepeval copy.csv',
  3: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32_deepeval copy.csv',
  4: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32_deepeval copy.csv'},
 'test_name': {0: 'Q1:gemini-1.5-pro:lexical_search_1_hop',
  1: 'Q1:gemini-1.5-pro:lexical_search_1_hop',
  2: 'Q1:gemini-1.5-pro:lexical_search_1_hop',
  3: 'Q2:gemini-1.5-pro:lexical_search_1_hop',
  4: 'Q2:gemini-1.5-pro:lexical_search_1_hop'},
 'success': {0: True, 1: True, 2: True, 3: False, 4: False},
 'metric_name': {0: 'Hallucination',
  1: 'Answer Relevancy',
  2: 'Contextual Relevancy',
  3: 'Hallucination',
  4: 'Answer Relevancy'},
 'threshold': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'metric_success': {0: True, 1: True, 2: True, 3: True, 4: True},
 'score': {0: 0.0, 1: 0.6551724137931034, 2: 1.0, 3: 0.0, 4: 1.0},
 'reason': {0: 'The score is 0.00 because the output accurately reflects the information present in the provided context, summarizing the medication history without introducing any contradictory or hallucinated details.  The output also appropriately advises consulting with a healthcare professional, aligning with responsible information handling practices.',
  1: "The score is 0.66 because while the response attempts to address the user's request for current medications, it falls short by primarily focusing on past medications and including irrelevant disclaimers and advice to consult a doctor.  The repeated mentions of dosage information being absent further detract from the score.  However, the attempt to address the core request, even if misguided, prevents the score from being lower.",
  2: "The score is 1.00 because the retrieved context directly answers the user's question about their current medications and dosage instructions. The context lists medications such as 'Hydrochlorothiazide', 'Simvastatin', and others with clear instructions like 'Take 1 tablet by mouth, 1 time daily'. This perfectly addresses the user's inquiry, making the context highly relevant.",
  3: 'The score is 0.00 because the output correctly aligns with the context, stating no documented allergies based on the absence of available data.',
  4: "The score is 1.00 because the response is a perfect match for the input.  It directly answers the query about documented allergies and their severity, which is exactly what was asked.  Since there are no irrelevant statements, there's nothing keeping the score from being any higher. Keep up the great work!"}}

In [6]:
# Create DataFrame
df = df_gold

# Create the pivot table
pivot = pd.pivot_table(
    df,
    values=["success", "threshold", "metric_success", "score"],
    index=["consumer_id", "test_name"],
    columns=["metric_name"],
    aggfunc="first",  # Use 'first' to get the value as is since duplicates are unlikely
)

# Optional: Flatten the column multi-index for cleaner display
pivot.columns = ["_".join(col).strip() for col in pivot.columns.values]
pivot.reset_index(inplace=True)

# Display the pivot table
pivot

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,success_Hallucination,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:gemini-1.5-pro:lexical_search_0_hop,True,False,True,1.000000,0.100000,0.0,False,False,False,0.5,0.5,0.5
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:gemini-1.5-pro:lexical_search_1_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:gemini-1.5-pro:similarity_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:gemini-1.5-pro:similarity_search_1_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:gemini-1.5-pro:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:gemini-1.5-pro:similarity_search_1_hop,True,True,True,0.984615,1.000000,0.0,True,True,True,0.5,0.5,0.5
156,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gemini-1.5-pro:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
157,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gemini-1.5-pro:lexical_search_1_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
158,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gemini-1.5-pro:similarity_search_0_hop,True,True,True,1.000000,0.888889,0.0,True,True,True,0.5,0.5,0.5
159,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gemini-1.5-pro:similarity_search_1_hop,True,True,True,1.000000,0.941176,0.0,True,True,True,0.5,0.5,0.5

In [7]:
pivot.to_csv(
    "/home/baptvit/Documents/mestrado/master-experiments/evaluations/data/gold/Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58_deepeval_results.csv"
)

In [7]:
pivot.head().to_dict()

{'consumer_id': {0: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625_deepeval-Copy1.csv',
  1: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625_deepeval-Copy1.csv',
  2: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625_deepeval-Copy1.csv',
  3: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625_deepeval-Copy1.csv',
  4: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625_deepeval-Copy1.csv'},
 'test_name': {0: 'Q1:gemini-1.5-pro:lexical_search_0_hop',
  1: 'Q1:gemini-1.5-pro:lexical_search_1_hop',
  2: 'Q1:gemini-1.5-pro:similarity_search_0_hop',
  3: 'Q1:gemini-1.5-pro:similarity_search_1_hop',
  4: 'Q2:gemini-1.5-pro:lexical_search_0_hop'},
 'metric_success_Answer Relevancy': {0: True,
  1: True,
  2: True,
  3: True,
  4: True},
 'metric_success_Contextual Relevancy': {0: False,
  1: True,
  2: True,
  3: True,
  4: True},
 'metric_success_Hallucination': {0: True, 1: True, 2: True, 3: True, 4: True},
 'score_Answer Relevancy': {0: 1.0, 1: 1.0, 2: 1.0, 3: 1.0, 4: 1.0},
 'score_Contextual Relevancy': {0: 0.1, 1: 1.0, 2: 1.0, 3: 1.0, 4: 1.0},
 'score_Hallucination': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0},
 'success_Answer Relevancy': {0: False, 1: True, 2: True, 3: True, 4: True},
 'success_Contextual Relevancy': {0: False,
  1: True,
  2: True,
  3: True,
  4: True},
 'success_Hallucination': {0: False, 1: True, 2: True, 3: True, 4: True},
 'threshold_Answer Relevancy': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'threshold_Contextual Relevancy': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'threshold_Hallucination': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5}}

In [8]:
df = pivot
# Analysis 1: Overall success rates by metric
success_rates = (
    df[
        [
            "metric_success_Answer Relevancy",
            "metric_success_Contextual Relevancy",
            "metric_success_Hallucination",
        ]
    ].mean()
    * 100
)

print("Overall Success Rates by Metric (%):")
print(success_rates)

# Analysis 2: Average scores by metric
average_scores = df[
    ["score_Answer Relevancy", "score_Contextual Relevancy", "score_Hallucination"]
].mean()

print("\nAverage Scores by Metric:")
print(average_scores)


# Analysis 3: Threshold compliance (scores >= threshold)
def threshold_compliance(row, metric):
    return row[f"score_{metric}"] >= row[f"threshold_{metric}"]


for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
    df[f"threshold_compliance_{metric}"] = df.apply(
        threshold_compliance, axis=1, metric=metric
    )

threshold_compliance_rates = (
    df[
        [
            "threshold_compliance_Answer Relevancy",
            "threshold_compliance_Contextual Relevancy",
            "threshold_compliance_Hallucination",
        ]
    ].mean()
    * 100
)

print("\nThreshold Compliance Rates by Metric (%):")
print(threshold_compliance_rates)

# Analysis 4: Breakdown by test_name
breakdown = df.groupby(["consumer_id", "test_name"]).mean()

print("\nBreakdown by Test Name:")
print(breakdown)

Overall Success Rates by Metric (%):
metric_success_Answer Relevancy        99.375
metric_success_Contextual Relevancy    85.000
metric_success_Hallucination           97.500
dtype: float64

Average Scores by Metric:
score_Answer Relevancy        0.978616
score_Contextual Relevancy    0.849145
score_Hallucination           0.025000
dtype: float64

Threshold Compliance Rates by Metric (%):
threshold_compliance_Answer Relevancy        99.375
threshold_compliance_Contextual Relevancy    85.000
threshold_compliance_Hallucination            2.500
dtype: float64

Breakdown by Test Name:
                                                                                              metric_success_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                                 1.0
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                                 1.0
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                              1.0
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                              1.0
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                                 1.0
...                                                                                                                       ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                              1.0
                                                   Q8:gemini-1.5-pro:lexical_search_0_hop                                 1.0
                                                   Q8:gemini-1.5-pro:lexical_search_1_hop                                 1.0
                                                   Q8:gemini-1.5-pro:similarity_search_0_hop                              1.0
                                                   Q8:gemini-1.5-pro:similarity_search_1_hop                              1.0

                                                                                              metric_success_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                                     0.0
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                                     1.0
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                                  1.0
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                                  1.0
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                                     1.0
...                                                                                                                           ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                                  1.0
                                                   Q8:gemini-1.5-pro:lexical_search_0_hop                                     1.0
                                                   Q8:gemini-1.5-pro:lexical_search_1_hop                                     1.0
                                                   Q8:gemini-1.5-pro:similarity_search_0_hop                                  1.0
                                                   Q8:gemini-1.5-pro:similarity_search_1_hop                                  1.0

                                                                                              metric_success_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                              1.0
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                              1.0
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                           1.0
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                           1.0
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                              1.0
...                                                                                                                    ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                           1.0
                                                   Q8:gemini-1.5-pro:lexical_search_0_hop                              1.0
                                                   Q8:gemini-1.5-pro:lexical_search_1_hop                              1.0
                                                   Q8:gemini-1.5-pro:similarity_search_0_hop                           1.0
                                                   Q8:gemini-1.5-pro:similarity_search_1_hop                           1.0

                                                                                              score_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                   1.000000
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                   1.000000
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                1.000000
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                1.000000
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                   1.000000
...                                                                                                              ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                0.984615
                                                   Q8:gemini-1.5-pro:lexical_search_0_hop                   1.000000
                                                   Q8:gemini-1.5-pro:lexical_search_1_hop                   1.000000
                                                   Q8:gemini-1.5-pro:similarity_search_0_hop                1.000000
                                                   Q8:gemini-1.5-pro:similarity_search_1_hop                1.000000

                                                                                              score_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                       0.100000
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                       1.000000
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                    1.000000
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                    1.000000
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                       1.000000
...                                                                                                                  ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                    1.000000
                                                   Q8:gemini-1.5-pro:lexical_search_0_hop                       1.000000
                                                   Q8:gemini-1.5-pro:lexical_search_1_hop                       1.000000
                                                   Q8:gemini-1.5-pro:similarity_search_0_hop                    0.888889
                                                   Q8:gemini-1.5-pro:similarity_search_1_hop                    0.941176

                                                                                              score_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                     0.0
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                     0.0
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                  0.0
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                  0.0
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                     0.0
...                                                                                                           ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                  0.0
                                                   Q8:gemini-1.5-pro:lexical_search_0_hop                     0.0
                                                   Q8:gemini-1.5-pro:lexical_search_1_hop                     0.0
                                                   Q8:gemini-1.5-pro:similarity_search_0_hop                  0.0
                                                   Q8:gemini-1.5-pro:similarity_search_1_hop                  0.0

                                                                                              success_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                          0.0
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                          1.0
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                       1.0
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                       1.0
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                          1.0
...                                                                                                                ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                       1.0
                                                   Q8:gemini-1.5-pro:lexical_search_0_hop                          1.0
                                                   Q8:gemini-1.5-pro:lexical_search_1_hop                          1.0
                                                   Q8:gemini-1.5-pro:similarity_search_0_hop                       1.0
                                                   Q8:gemini-1.5-pro:similarity_search_1_hop                       1.0

                                                                                              success_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                              0.0
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                              1.0
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                           1.0
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                           1.0
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                              1.0
...                                                                                                                    ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                           1.0
                                                   Q8:gemini-1.5-pro:lexical_search_0_hop                              1.0
                                                   Q8:gemini-1.5-pro:lexical_search_1_hop                              1.0
                                                   Q8:gemini-1.5-pro:similarity_search_0_hop                           1.0
                                                   Q8:gemini-1.5-pro:similarity_search_1_hop                           1.0

                                                                                              success_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                       0.0
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                       1.0
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                    1.0
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                    1.0
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                       1.0
...                                                                                                             ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                    1.0
                                                   Q8:gemini-1.5-pro:lexical_search_0_hop                       1.0
                                                   Q8:gemini-1.5-pro:lexical_search_1_hop                       1.0
                                                   Q8:gemini-1.5-pro:similarity_search_0_hop                    1.0
                                                   Q8:gemini-1.5-pro:similarity_search_1_hop                    1.0

                                                                                              threshold_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                            0.5
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                            0.5
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                         0.5
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                         0.5
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                            0.5
...                                                                                                                  ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                         0.5
                                                   Q8:gemini-1.5-pro:lexical_search_0_hop                            0.5
                                                   Q8:gemini-1.5-pro:lexical_search_1_hop                            0.5
                                                   Q8:gemini-1.5-pro:similarity_search_0_hop                         0.5
                                                   Q8:gemini-1.5-pro:similarity_search_1_hop                         0.5

                                                                                              threshold_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                                0.5
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                                0.5
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                             0.5
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                             0.5
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                                0.5
...                                                                                                                      ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                             0.5
                                                   Q8:gemini-1.5-pro:lexical_search_0_hop                                0.5
                                                   Q8:gemini-1.5-pro:lexical_search_1_hop                                0.5
                                                   Q8:gemini-1.5-pro:similarity_search_0_hop                             0.5
                                                   Q8:gemini-1.5-pro:similarity_search_1_hop                             0.5

                                                                                              threshold_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                         0.5
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                         0.5
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                      0.5
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                      0.5
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                         0.5
...                                                                                                               ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                      0.5
                                                   Q8:gemini-1.5-pro:lexical_search_0_hop                         0.5
                                                   Q8:gemini-1.5-pro:lexical_search_1_hop                         0.5
                                                   Q8:gemini-1.5-pro:similarity_search_0_hop                      0.5
                                                   Q8:gemini-1.5-pro:similarity_search_1_hop                      0.5

                                                                                              threshold_compliance_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:gemini-1.5-pro:lexical_search_0_hop                                       1.0
                                                   Q1:gemini-1.5-pro:lexical_search_1_hop                                       1.0
                                                   Q1:gemini-1.5-pro:similarity_search_0_hop                                    1.0
                                                   Q1:gemini-1.5-pro:similarity_search_1_hop                                    1.0
                                                   Q2:gemini-1.5-pro:lexical_search_0_hop                                       1.0
...                                                                                                                             ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gemini-1.5-pro:similarity_search_1_hop                                    1.0

In [9]:
df = pivot

df[["question", "model", "search_type"]] = df["test_name"].str.split(":", expand=True)

In [10]:
df["hops"] = df["test_name"].str[-5:]

In [11]:
df["hops"] = df["hops"].str.replace("_hop", "", regex=False).astype(int)

In [12]:
df

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,...,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination,threshold_compliance_Answer Relevancy,threshold_compliance_Contextual Relevancy,threshold_compliance_Hallucination,question,model,search_type,hops
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:gemini-1.5-pro:lexical_search_0_hop,True,False,True,1.000000,0.100000,0.0,False,False,...,0.5,0.5,0.5,True,False,False,Q1,gemini-1.5-pro,lexical_search_0_hop,0
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:gemini-1.5-pro:lexical_search_1_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q1,gemini-1.5-pro,lexical_search_1_hop,1
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:gemini-1.5-pro:similarity_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q1,gemini-1.5-pro,similarity_search_0_hop,0
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:gemini-1.5-pro:similarity_search_1_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q1,gemini-1.5-pro,similarity_search_1_hop,1
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:gemini-1.5-pro:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q2,gemini-1.5-pro,lexical_search_0_hop,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:gemini-1.5-pro:similarity_search_1_hop,True,True,True,0.984615,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q7,gemini-1.5-pro,similarity_search_1_hop,1
156,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gemini-1.5-pro:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,gemini-1.5-pro,lexical_search_0_hop,0
157,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gemini-1.5-pro:lexical_search_1_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,gemini-1.5-pro,lexical_search_1_hop,1
158,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gemini-1.5-pro:similarity_search_0_hop,True,True,True,1.000000,0.888889,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,gemini-1.5-pro,similarity_search_0_hop,0
159,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gemini-1.5-pro:similarity_search_1_hop,True,True,True,1.000000,0.941176,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,gemini-1.5-pro,similarity_search_1_hop,1

In [13]:


# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = (
    df.groupby(["consumer_id", "question", "search_type", "hops"])
    .apply(analyze_metrics)
    .reset_index()
)
grouped_df

/tmp/ipykernel_6359/3055100408.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(['consumer_id', 'question', 'search_type', 'hops']).apply(analyze_metrics).reset_index()

,consumer_id,question,search_type,hops,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,lexical_search_0_hop,0,1.000000,0.0,1.0,0.100000,0.0,0.0,0.0,0.0,1.0
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,lexical_search_1_hop,1,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,similarity_search_0_hop,0,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,similarity_search_1_hop,1,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2,lexical_search_0_hop,0,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7,similarity_search_1_hop,1,0.984615,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
156,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,lexical_search_0_hop,0,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
157,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,lexical_search_1_hop,1,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
158,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,similarity_search_0_hop,0,1.000000,1.0,1.0,0.888889,1.0,1.0,0.0,1.0,1.0
159,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,similarity_search_1_hop,1,1.000000,1.0,1.0,0.941176,1.0,1.0,0.0,1.0,1.0

In [14]:


# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = (
    df.groupby(["consumer_id", "search_type"]).apply(analyze_metrics).reset_index()
)
grouped_df

/tmp/ipykernel_6359/1281351638.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(['consumer_id', 'search_type']).apply(analyze_metrics).reset_index()

,consumer_id,search_type,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_0_hop,1.000000,0.750,1.000,0.712897,0.750,0.750,0.000,0.750,1.000
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_1_hop,1.000000,0.875,1.000,0.822674,0.875,0.875,0.000,0.875,1.000
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_0_hop,0.995787,1.000,1.000,0.995748,1.000,1.000,0.000,1.000,1.000
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_1_hop,1.000000,1.000,1.000,1.000000,1.000,1.000,0.000,1.000,1.000
4,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_0_hop,0.977273,1.000,1.000,1.000000,1.000,1.000,0.000,1.000,1.000
5,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_1_hop,1.000000,1.000,1.000,1.000000,1.000,1.000,0.000,1.000,1.000
6,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_0_hop,1.000000,1.000,1.000,0.992647,1.000,1.000,0.000,1.000,1.000
7,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_1_hop,0.806066,0.875,0.875,0.992647,0.875,1.000,0.000,0.875,1.000
8,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_0_hop,0.961957,0.875,1.000,0.845588,0.875,0.875,0.000,0.875,1.000
9,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_1_hop,0.997283,0.625,1.000,0.776786,0.625,0.750,0.125,0.625,0.875
10,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_0_hop,0.979167,0.750,1.000,0.770115,0.750,0.750,0.000,0.750,1.000
11,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_1_hop,0.973611,0.625,1.000,0.663690,0.625,0.625,0.125,0.625,0.875
12,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_0_hop,1.000000,0.875,1.000,0.875000,0.875,0.875,0.000,0.875,1.000
13,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_1_hop,0.949145,0.500,1.000,0.746377,0.500,0.500,0.000,0.500,1.000
14,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_0_hop,1.000000,1.000,1.000,0.937500,1.000,1.000,0.000,1.000,1.000
15,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_1_hop,0.940448,0.750,1.000,0.845307,0.750,0.875,0.250,0.750,0.750
16,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_0_hop,0.997191,0.875,1.000,0.875000,0.875,0.875,0.000,0.875,1.000
17,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_1_hop,1.000000,0.875,1.000,0.833703,0.875,0.875,0.000,0.875,1.000
18,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_0_hop,0.996324,0.625,1.000,0.603808,0.625,0.625,0.000,0.625,1.000
19,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_1_hop,0.998077,0.750,1.000,0.667724,0.750,0.750,0.000,0.750,1.000

In [15]:


# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_6359/3286766692.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(['search_type']).apply(analyze_metrics).reset_index()

,search_type,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,lexical_search_0_hop,0.987284,0.875,1.000,0.861697,0.875,0.875,0.000,0.875,1.000
1,lexical_search_1_hop,0.989285,0.775,1.000,0.840620,0.775,0.800,0.025,0.775,0.975
2,similarity_search_0_hop,0.994255,0.875,1.000,0.859964,0.875,0.875,0.000,0.875,1.000
3,similarity_search_1_hop,0.943641,0.800,0.975,0.833874,0.800,0.850,0.075,0.800,0.925

In [16]:


# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["question"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_6359/4196324731.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(['question']).apply(analyze_metrics).reset_index()

,question,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Q1,0.964009,0.85,1.00,0.921667,0.85,0.95,0.10,0.85,0.90
1,Q2,1.000000,0.45,1.00,0.450000,0.45,0.45,0.05,0.45,0.95
2,Q3,0.915161,0.65,0.95,0.720424,0.65,0.70,0.05,0.65,0.95
3,Q4,0.976250,0.85,1.00,0.816613,0.85,0.85,0.00,0.85,1.00
4,Q5,1.000000,0.95,1.00,0.960000,0.95,0.95,0.00,0.95,1.00
5,Q6,0.990909,0.95,1.00,0.948453,0.95,0.95,0.00,0.95,1.00
6,Q7,0.991425,0.95,1.00,0.996852,0.95,0.95,0.00,0.95,1.00
7,Q8,0.991176,1.00,1.00,0.991503,1.00,1.00,0.00,1.00,1.00

In [17]:


# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_6359/2470915338.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(['search_type']).apply(analyze_metrics).reset_index()

,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,lexical_search_0_hop,0.987284,0.055406,0.875,1.000,0.861697,0.330413,0.875,0.875,0.000,0.000000,0.875,1.000
1,lexical_search_1_hop,0.989285,0.055153,0.775,1.000,0.840620,0.336954,0.775,0.800,0.025,0.158114,0.775,0.975
2,similarity_search_0_hop,0.994255,0.027013,0.875,1.000,0.859964,0.306490,0.875,0.875,0.000,0.000000,0.875,1.000
3,similarity_search_1_hop,0.943641,0.176364,0.800,0.975,0.833874,0.319440,0.800,0.850,0.075,0.266747,0.800,0.925

In [19]:
grouped_df.columns

Index(['search_type', 'avg_score_Answer Relevancy',
       'std_score_Answer Relevancy', 'success_rate_Answer Relevancy',
       'metric_success_rate_Answer Relevancy',
       'avg_score_Contextual Relevancy', 'std_score_Contextual Relevancy',
       'success_rate_Contextual Relevancy',
       'metric_success_rate_Contextual Relevancy', 'avg_score_Hallucination',
       'std_score_Hallucination', 'success_rate_Hallucination',
       'metric_success_rate_Hallucination'],
      dtype='object')

In [21]:
grouped_df[
    [
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].to_dict()

{'search_type': {0: 'lexical_search_0_hop',
  1: 'lexical_search_1_hop',
  2: 'similarity_search_0_hop',
  3: 'similarity_search_1_hop'},
 'avg_score_Answer Relevancy': {0: 0.9872840520495625,
  1: 0.9892854444870588,
  2: 0.9942553425864729,
  3: 0.9436405404629185},
 'std_score_Answer Relevancy': {0: 0.05540587396807781,
  1: 0.05515305248281869,
  2: 0.02701329506627158,
  3: 0.17636415603586583},
 'avg_score_Contextual Relevancy': {0: 0.8616970121381886,
  1: 0.840620131383029,
  2: 0.8599636081993175,
  3: 0.8338737907085161},
 'std_score_Contextual Relevancy': {0: 0.33041252612162114,
  1: 0.33695388599502857,
  2: 0.30649008133202443,
  3: 0.3194402981738698},
 'avg_score_Hallucination': {0: 0.0, 1: 0.025, 2: 0.0, 3: 0.075},
 'std_score_Hallucination': {0: 0.0,
  1: 0.15811388300841897,
  2: 0.0,
  3: 0.2667467828369185}}