# Analysis for the deepeval metrics

In [1]:
gold_source = (
    "/home/baptvit/Documents/github/graphrag-on-fhir/evaluations/data/gold/deepeval/"
)

In [2]:
import glob
import os

import pandas as pd

all_files = glob.glob(os.path.join(gold_source, "*.csv"))

all_dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df["consumer_id"] = file.split("/")[-1]
    all_dfs.append(df)


df_gold = pd.concat(all_dfs, ignore_index=True)

In [3]:
df_gold.columns

Index(['consumer_id', 'test_name', 'success', 'metric_name', 'threshold',
       'metric_success', 'score', 'reason', 'strict_mode', 'evaluation_model',
       'error', 'evaluation_cost', 'verbose_logs', 'conversational',
       'multimodal', 'input', 'actual_output', 'expected_output', 'context',
       'retrieval_context', 'Unnamed: 0'],
      dtype='object')

In [4]:
df_gold.head()

,consumer_id,test_name,success,metric_name,threshold,metric_success,score,reason,strict_mode,evaluation_model,...,evaluation_cost,verbose_logs,conversational,multimodal,input,actual_output,expected_output,context,retrieval_context,Unnamed: 0
0,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:llama-3-70b-instruct-awq:similarity_search_...,True,Hallucination,0.5,True,0.000000,The score is 0.00 because the actual output al...,False,Custom Azure OpenAI Model,...,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,Can you summarize my care plan history ?,"\n\nBased on the retrieved records, I can prov...",NaN,{'Main health record': 'Observation Type: Surv...,{'Main health record': 'Observation Type: Surv...,NaN
1,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:llama-3-70b-instruct-awq:similarity_search_...,True,Answer Relevancy,0.5,True,1.000000,The score is 1.00 because the output perfectly...,False,Custom Azure OpenAI Model,...,NaN,"Statements:\n[\n ""Based on the retrieved re...",False,False,Can you summarize my care plan history ?,"\n\nBased on the retrieved records, I can prov...",NaN,{'Main health record': 'Observation Type: Surv...,{'Main health record': 'Observation Type: Surv...,NaN
2,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:llama-3-70b-instruct-awq:similarity_search_...,True,Contextual Relevancy,0.5,True,0.500000,The score is 0.50 because while there are seve...,False,Custom Azure OpenAI Model,...,NaN,"Verdicts:\n[\n {\n ""verdicts"": [\n ...",False,False,Can you summarize my care plan history ?,"\n\nBased on the retrieved records, I can prov...",NaN,{'Main health record': 'Observation Type: Surv...,{'Main health record': 'Observation Type: Surv...,NaN
3,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q4:llama-3-70b-instruct-awq:similarity_search_...,False,Hallucination,0.5,False,1.000000,The score is 1.00 because the 'actual output' ...,False,Custom Azure OpenAI Model,...,NaN,"Verdicts:\n[\n {\n ""verdict"": ""no"",\...",False,False,"What are my recent laboratory values, what do ...","\n\nBased on the laboratory results retrieved,...",NaN,{'Main health record': 'Resource Type: Observa...,{'Main health record': 'Resource Type: Observa...,NaN
4,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q4:llama-3-70b-instruct-awq:similarity_search_...,False,Answer Relevancy,0.5,True,0.952381,The score is 0.95 because the output is highly...,False,Custom Azure OpenAI Model,...,NaN,"Statements:\n[\n ""Based on the laboratory r...",False,False,"What are my recent laboratory values, what do ...","\n\nBased on the laboratory results retrieved,...",NaN,{'Main health record': 'Resource Type: Observa...,{'Main health record': 'Resource Type: Observa...,NaN

In [5]:
df_gold["error"].unique()

array([nan,
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 2982616 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 2934370 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1179389 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1153253 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1179526 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1156312 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1150255 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1127686 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1177756 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1156322 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 314840 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 304461 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 212669 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 205838 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Evaluation LLM outputted an invalid JSON. Please use a better evaluation model.',
       'Error code: 400 - {\'error\': {\'message\': "Error code: 400 - {\'message\': \'Input is too long for requested model.\'}", \'type\': \'invalid_request_error\', \'code\': \'400\'}}',
       'No route',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1297062 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1272904 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 162230 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\', \'callstack\': \'  File "/usr/local/bin/gunicorn", line 8, in <module>\\n    sys.exit(run())\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 66, in run\\n    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 235, in run\\n    super().run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 71, in run\\n    Arbiter(self).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 201, in run\\n    self.manage_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 570, in manage_workers\\n    self.spawn_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 641, in spawn_workers\\n    self.spawn_worker()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker\\n    worker.init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process\\n    super().init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 143, in init_process\\n    self.run()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 107, in run\\n    return asyncio.run(self._serve())\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run\\n    return runner.run(main)\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run\\n    return self._loop.run_until_complete(task)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro\\n    await self.app(scope, receive_or_disconnect, send_no_error)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__\\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app\\n    await app(scope, receive, sender)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__\\n    await self.middleware_stack(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app\\n    await route.handle(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app\\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 75, in wrapped_app\\n    response = await handler(conn, exc)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 82, in _datadog_error_tracking_wrapper\\n    return await call_next(request, exception)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 112, in create_response_from_api_error\\n    return _create_response(\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 51, in _create_response\\n    problem_response = {"message": message, "type": type, "param": param, "code": code, "callstack": "at ".join(traceback.format_stack())}\\n\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 156982 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 140503 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\', \'callstack\': \'  File "/usr/local/bin/gunicorn", line 8, in <module>\\n    sys.exit(run())\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 66, in run\\n    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 235, in run\\n    super().run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 71, in run\\n    Arbiter(self).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 210, in run\\n    self.manage_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 570, in manage_workers\\n    self.spawn_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 641, in spawn_workers\\n    self.spawn_worker()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker\\n    worker.init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process\\n    super().init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 143, in init_process\\n    self.run()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 107, in run\\n    return asyncio.run(self._serve())\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run\\n    return runner.run(main)\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run\\n    return self._loop.run_until_complete(task)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro\\n    await self.app(scope, receive_or_disconnect, send_no_error)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__\\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app\\n    await app(scope, receive, sender)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__\\n    await self.middleware_stack(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app\\n    await route.handle(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app\\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 75, in wrapped_app\\n    response = await handler(conn, exc)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 82, in _datadog_error_tracking_wrapper\\n    return await call_next(request, exception)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 112, in create_response_from_api_error\\n    return _create_response(\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 51, in _create_response\\n    problem_response = {"message": message, "type": type, "param": param, "code": code, "callstack": "at ".join(traceback.format_stack())}\\n\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 135564 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 145717 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\', \'callstack\': \'  File "/usr/local/bin/gunicorn", line 8, in <module>\\n    sys.exit(run())\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 66, in run\\n    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 235, in run\\n    super().run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 71, in run\\n    Arbiter(self).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 201, in run\\n    self.manage_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 570, in manage_workers\\n    self.spawn_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 641, in spawn_workers\\n    self.spawn_worker()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker\\n    worker.init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process\\n    super().init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 143, in init_process\\n    self.run()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 107, in run\\n    return asyncio.run(self._serve())\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run\\n    return runner.run(main)\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run\\n    return self._loop.run_until_complete(task)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro\\n    await self.app(scope, receive_or_disconnect, send_no_error)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__\\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app\\n    await app(scope, receive, sender)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__\\n    await self.middleware_stack(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app\\n    await route.handle(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app\\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 75, in wrapped_app\\n    response = await handler(conn, exc)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 82, in _datadog_error_tracking_wrapper\\n    return await call_next(request, exception)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 112, in create_response_from_api_error\\n    return _create_response(\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 51, in _create_response\\n    problem_response = {"message": message, "type": type, "param": param, "code": code, "callstack": "at ".join(traceback.format_stack())}\\n\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 135560 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 154731 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',

In [6]:
import numpy as np

df_gold = df_gold[df_gold["error"].isna()]

In [7]:
df_5 = df_gold[
    [
        "consumer_id",
        "test_name",
        "success",
        "metric_name",
        "threshold",
        "metric_success",
        "score",
        "reason",
    ]
].head()

In [8]:
df_5.to_dict()

{'consumer_id': {0: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv',
  1: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv',
  2: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv',
  3: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv',
  4: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv'},
 'test_name': {0: 'Q5:llama-3-70b-instruct-awq:similarity_search_0_hop',
  1: 'Q5:llama-3-70b-instruct-awq:similarity_search_0_hop',
  2: 'Q5:llama-3-70b-instruct-awq:similarity_search_0_hop',
  3: 'Q4:llama-3-70b-instruct-awq:similarity_search_0_hop',
  4: 'Q4:llama-3-70b-instruct-awq:similarity_search_0_hop'},
 'success': {0: True, 1: True, 2: True, 3: False, 4: False},
 'metric_name': {0: 'Hallucination',
  1: 'Answer Relevancy',
  2: 'Contextual Relevancy',
  3: 'Hallucination',
  4: 'Answer Relevancy'},
 'threshold': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'metric_success': {0: True, 1: True, 2: True, 3: False, 4: True},
 'score': {0: 0.0, 1: 1.0, 2: 0.5, 3: 1.0, 4: 0.9523809523809524},
 'reason': {0: 'The score is 0.00 because the actual output aligns perfectly with the provided contexts and there are no contradictions.',
  1: 'The score is 1.00 because the output perfectly addresses the input without any irrelevant statements. Great job staying focused and precise!',
  2: "The score is 0.50 because while there are several relevant care plan details provided, such as 'Care Plan for Lifestyle education regarding hypertension' and 'Care Plan for Physiotherapy care plan,' the majority of the retrieval context is irrelevant, focusing on topics like social determinants of health and insurance claims.",
  3: "The score is 1.00 because the 'actual output' does not align with the context data and fails to reference specific findings or data points explicitly, indicating a complete lack of factual basis from the provided context.",
  4: 'The score is 0.95 because the output is highly relevant and mostly addresses the input, but it includes repeated mentions of specific healthcare facilities that are unnecessary and do not directly address the inquiry about laboratory values, their meanings, or ways to improve them.'}}

In [9]:
# Create DataFrame
df = df_gold

# Create the pivot table
pivot = pd.pivot_table(
    df,
    values=["success", "threshold", "metric_success", "score"],
    index=["consumer_id", "test_name"],
    columns=["metric_name"],
    aggfunc="first",  # Use 'first' to get the value as is since duplicates are unlikely
)

# Optional: Flatten the column multi-index for cleaner display
pivot.columns = ["_".join(col).strip() for col in pivot.columns.values]
pivot.reset_index(inplace=True)

# Display the pivot table
pivot

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,success_Hallucination,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,False,True,1.000000,0.333333,0.0,False,False,False,0.5,0.5,0.5
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.968750,1.000000,0.0,True,True,True,0.5,0.5,0.5
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarit...,True,False,False,0.838710,0.461538,1.0,False,False,False,0.5,0.5,0.5
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarit...,True,True,False,0.833333,0.750000,1.0,False,False,False,0.5,0.5,0.5
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.956522,1.000000,0.0,True,True,True,0.5,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:llama-3-70b-instruct-awq:similarity_search_...,True,True,True,0.666667,0.692308,0.0,True,True,True,0.5,0.5,0.5
767,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
768,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:lexical_search_1_hop,True,True,False,0.740741,0.571429,1.0,False,False,False,0.5,0.5,0.5
769,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:similarity_search_...,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
770,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:similarity_search_...,True,True,True,0.886364,0.500000,0.0,True,True,True,0.5,0.5,0.5

In [10]:
pivot.to_csv(
    "/home/baptvit/Documents/mestrado/master-experiments/evaluations/data/gold/Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58_deepeval_results.csv"
)

In [11]:
pivot.head().to_dict()

{'consumer_id': {0: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv',
  1: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv',
  2: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv',
  3: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv',
  4: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv'},
 'test_name': {0: 'Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_0_hop',
  1: 'Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_1_hop',
  2: 'Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity_search_0_hop',
  3: 'Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity_search_1_hop',
  4: 'Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_0_hop'},
 'metric_success_Answer Relevancy': {0: True,
  1: True,
  2: True,
  3: True,
  4: True},
 'metric_success_Contextual Relevancy': {0: False,
  1: True,
  2: False,
  3: True,
  4: True},
 'metric_success_Hallucination': {0: True,
  1: True,
  2: False,
  3: False,
  4: True},
 'score_Answer Relevancy': {0: 1.0,
  1: 0.96875,
  2: 0.8387096774193549,
  3: 0.8333333333333334,
  4: 0.9565217391304348},
 'score_Contextual Relevancy': {0: 0.3333333333333333,
  1: 1.0,
  2: 0.4615384615384615,
  3: 0.75,
  4: 1.0},
 'score_Hallucination': {0: 0.0, 1: 0.0, 2: 1.0, 3: 1.0, 4: 0.0},
 'success_Answer Relevancy': {0: False, 1: True, 2: False, 3: False, 4: True},
 'success_Contextual Relevancy': {0: False,
  1: True,
  2: False,
  3: False,
  4: True},
 'success_Hallucination': {0: False, 1: True, 2: False, 3: False, 4: True},
 'threshold_Answer Relevancy': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'threshold_Contextual Relevancy': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'threshold_Hallucination': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5}}

In [12]:
df = pivot
# Analysis 1: Overall success rates by metric
success_rates = (
    df[
        [
            "metric_success_Answer Relevancy",
            "metric_success_Contextual Relevancy",
            "metric_success_Hallucination",
        ]
    ].mean()
    * 100
)

print("Overall Success Rates by Metric (%):")
print(success_rates)

# Analysis 2: Average scores by metric
average_scores = df[
    ["score_Answer Relevancy", "score_Contextual Relevancy", "score_Hallucination"]
].mean()

print("\nAverage Scores by Metric:")
print(average_scores)


# Analysis 3: Threshold compliance (scores >= threshold)
def threshold_compliance(row, metric):
    return row[f"score_{metric}"] >= row[f"threshold_{metric}"]


for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
    df[f"threshold_compliance_{metric}"] = df.apply(
        threshold_compliance, axis=1, metric=metric
    )

threshold_compliance_rates = (
    df[
        [
            "threshold_compliance_Answer Relevancy",
            "threshold_compliance_Contextual Relevancy",
            "threshold_compliance_Hallucination",
        ]
    ].mean()
    * 100
)

print("\nThreshold Compliance Rates by Metric (%):")
print(threshold_compliance_rates)

# Analysis 4: Breakdown by test_name
breakdown = df.groupby(["consumer_id", "test_name"]).mean()

print("\nBreakdown by Test Name:")
print(breakdown)

Overall Success Rates by Metric (%):
metric_success_Answer Relevancy        92.950392
metric_success_Contextual Relevancy    79.324895
metric_success_Hallucination           76.005548
dtype: object

Average Scores by Metric:
score_Answer Relevancy        0.895720
score_Contextual Relevancy    0.687707
score_Hallucination           0.241736
dtype: float64

Threshold Compliance Rates by Metric (%):
threshold_compliance_Answer Relevancy        92.347601
threshold_compliance_Contextual Relevancy    73.151751
threshold_compliance_Hallucination           22.697795
dtype: float64

Breakdown by Test Name:
                                                                                                      metric_success_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                             1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                             1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             1.0
...                                                                                                                               ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                             1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                               1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                               1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                             1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                             1.0

                                                                                                      metric_success_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                                 0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                                 1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                                 0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                                 1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                                 1.0
...                                                                                                                                   ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                                 1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                                   1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                                   1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                                 1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                                 1.0

                                                                                                      metric_success_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                          0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                          0.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
...                                                                                                                            ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                          1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                            1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                            0.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                          1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                          1.0

                                                                                                       score_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                1.000000
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                0.968750
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                0.838710
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                0.833333
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                0.956522
...                                                                                                                       ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                0.666667
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                  1.000000
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                  0.740741
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                1.000000
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                0.886364

                                                                                                       score_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                    0.333333
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                    1.000000
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                    0.461538
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                    0.750000
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                    1.000000
...                                                                                                                           ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                    0.692308
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                      1.000000
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                      0.571429
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                    1.000000
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                    0.500000

                                                                                                       score_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                  0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                  0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                  1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                  1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                  0.0
...                                                                                                                    ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                  0.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                    0.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                    1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                  0.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                  0.0

                                                                                                      success_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                      0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                      0.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      1.0
...                                                                                                                        ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                      1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                        1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                        0.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                      1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                      1.0

                                                                                                      success_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                          0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                          0.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
...                                                                                                                            ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                          1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                            1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                            0.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                          1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                          1.0

                                                                                                      success_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                   0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                   1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                   0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                   0.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                   1.0
...                                                                                                                     ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                   1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                     1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                     0.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                   1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                   1.0

                                                                                                       threshold_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                         0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                         0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                         0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                         0.5
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                         0.5
...                                                                                                                           ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                         0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                           0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                           0.5
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                         0.5
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                         0.5

                                                                                                       threshold_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                             0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                             0.5
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             0.5
...                                                                                                                               ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                             0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                               0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                               0.5
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                             0.5
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                             0.5

                                                                                                       threshold_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                      0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                      0.5
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.5
...                                                                                                                        ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                      0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                        0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                        0.5
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                      0.5

In [13]:
df = pivot

df[["question", "model", "search_type"]] = df["test_name"].str.split(":", expand=True)

In [14]:
df["hops"] = df["test_name"].str[-5:]

In [15]:
df["hops"] = df["hops"].str.replace("_hop", "", regex=False).astype(int)

In [16]:
df = df.replace("anthropic.claude-v3-5-sonnet-v2", "anthropic.claude-v3-opus")
df = df.replace("gpt-4o-2024-11-20", "gpt-4o-2024-08-06")

In [17]:
df

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,...,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination,threshold_compliance_Answer Relevancy,threshold_compliance_Contextual Relevancy,threshold_compliance_Hallucination,question,model,search_type,hops
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,False,True,1.000000,0.333333,0.0,False,False,...,0.5,0.5,0.5,True,False,False,Q1,DeepSeek-R1-Distill-Llama-70B-FP8,lexical_search_0_hop,0
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.968750,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q1,DeepSeek-R1-Distill-Llama-70B-FP8,lexical_search_1_hop,1
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarit...,True,False,False,0.838710,0.461538,1.0,False,False,...,0.5,0.5,0.5,True,False,True,Q1,DeepSeek-R1-Distill-Llama-70B-FP8,similarity_search_0_hop,0
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarit...,True,True,False,0.833333,0.750000,1.0,False,False,...,0.5,0.5,0.5,True,True,True,Q1,DeepSeek-R1-Distill-Llama-70B-FP8,similarity_search_1_hop,1
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.956522,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q2,DeepSeek-R1-Distill-Llama-70B-FP8,lexical_search_0_hop,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:llama-3-70b-instruct-awq:similarity_search_...,True,True,True,0.666667,0.692308,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q7,llama-3-70b-instruct-awq,similarity_search_1_hop,1
767,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,llama-3-70b-instruct-awq,lexical_search_0_hop,0
768,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:lexical_search_1_hop,True,True,False,0.740741,0.571429,1.0,False,False,...,0.5,0.5,0.5,True,True,True,Q8,llama-3-70b-instruct-awq,lexical_search_1_hop,1
769,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:similarity_search_...,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,llama-3-70b-instruct-awq,similarity_search_0_hop,0
770,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:similarity_search_...,True,True,True,0.886364,0.500000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,llama-3-70b-instruct-awq,similarity_search_1_hop,1

In [18]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = (
    df.groupby(["consumer_id", "question", "search_type", "hops"])
    .apply(analyze_metrics)
    .reset_index()
)
grouped_df

/tmp/ipykernel_176898/833737725.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(analyze_metrics)

,consumer_id,question,search_type,hops,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,lexical_search_0_hop,0,1.000000,0.0,1.0,0.333333,0.0,0.0,0.0,0.0,1.0
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,lexical_search_1_hop,1,0.968750,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,similarity_search_0_hop,0,0.838710,0.0,1.0,0.461538,0.0,0.0,1.0,0.0,0.0
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,similarity_search_1_hop,1,0.833333,0.0,1.0,0.750000,0.0,1.0,1.0,0.0,0.0
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2,lexical_search_0_hop,0,0.956522,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7,similarity_search_1_hop,1,0.666667,1.0,1.0,0.692308,1.0,1.0,0.0,1.0,1.0
767,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,lexical_search_0_hop,0,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
768,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,lexical_search_1_hop,1,0.740741,0.0,1.0,0.571429,0.0,1.0,1.0,0.0,0.0
769,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,similarity_search_0_hop,0,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
770,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,similarity_search_1_hop,1,0.886364,1.0,1.0,0.500000,1.0,1.0,0.0,1.0,1.0

In [19]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = (
    df.groupby(["consumer_id", "search_type"]).apply(analyze_metrics).reset_index()
)
grouped_df

/tmp/ipykernel_176898/1437396366.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(["consumer_id", "search_type"]).apply(analyze_metrics).reset_index()

,consumer_id,search_type,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_0_hop,0.985945,0.625,1.000,0.682411,0.625000,0.625000,0.250000,0.625000,0.750000
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_1_hop,0.971551,0.500,1.000,0.877381,0.666667,1.000000,0.333333,0.666667,0.666667
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_0_hop,0.974839,0.750,1.000,0.725752,0.750000,0.875000,0.250000,0.750000,0.750000
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_1_hop,0.854167,0.250,0.875,0.756250,0.250000,1.000000,0.812500,0.250000,0.250000
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_0_hop,0.771987,0.625,0.875,0.681324,0.625000,0.875000,0.125000,0.625000,0.875000
...,...,...,...,...,...,...,...,...,...,...,...
94,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_1_hop,0.792205,0.375,0.875,0.569384,0.428571,0.714286,0.285714,0.428571,0.714286
95,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_0_hop,0.840097,0.375,0.875,0.573074,0.375000,0.750000,0.500000,0.375000,0.500000
96,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_1_hop,0.884921,0.125,0.875,0.460952,0.200000,0.600000,0.600000,0.200000,0.400000
97,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_0_hop,0.827083,0.625,0.875,0.586932,0.625000,0.750000,0.125000,0.625000,0.875000
98,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_1_hop,0.760570,0.250,0.875,0.463187,0.285714,0.571429,0.642857,0.285714,0.428571

In [20]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_176898/3565463073.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()

,search_type,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,lexical_search_0_hop,0.890446,0.656250,0.927083,0.707858,0.663158,0.794737,0.194372,0.659686,0.806283
1,lexical_search_1_hop,0.926803,0.455959,0.968912,0.710300,0.556962,0.803797,0.285714,0.546584,0.714286
2,similarity_search_0_hop,0.900798,0.645503,0.920635,0.671442,0.655914,0.779570,0.165780,0.648936,0.835106
3,similarity_search_1_hop,0.864749,0.463542,0.901042,0.663000,0.502825,0.796610,0.331492,0.491713,0.674033

In [21]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["question"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_176898/1271303342.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["question"]).apply(analyze_metrics).reset_index()

,question,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Q1,0.823418,0.416667,0.916667,0.576055,0.434783,0.586957,0.223368,0.412371,0.783505
1,Q2,0.694550,0.421053,0.715789,0.381135,0.425532,0.436170,0.154255,0.425532,0.851064
2,Q3,0.896326,0.531250,0.947917,0.694079,0.586207,0.862069,0.257267,0.593023,0.744186
3,Q4,0.947812,0.378947,0.968421,0.665293,0.439024,0.804878,0.407407,0.444444,0.592593
4,Q5,0.980765,0.684211,0.989474,0.755049,0.730337,0.865169,0.152174,0.706522,0.847826
5,Q6,0.993200,0.406250,1.000000,0.711299,0.469880,0.891566,0.511628,0.453488,0.488372
6,Q7,0.869936,0.663265,0.897959,0.831989,0.730337,0.932584,0.222222,0.722222,0.777778
7,Q8,0.960293,0.936842,1.000000,0.893818,0.936842,0.989474,0.052632,0.936842,0.947368

In [22]:
df.columns

Index(['consumer_id', 'test_name', 'metric_success_Answer Relevancy',
       'metric_success_Contextual Relevancy', 'metric_success_Hallucination',
       'score_Answer Relevancy', 'score_Contextual Relevancy',
       'score_Hallucination', 'success_Answer Relevancy',
       'success_Contextual Relevancy', 'success_Hallucination',
       'threshold_Answer Relevancy', 'threshold_Contextual Relevancy',
       'threshold_Hallucination', 'threshold_compliance_Answer Relevancy',
       'threshold_compliance_Contextual Relevancy',
       'threshold_compliance_Hallucination', 'question', 'model',
       'search_type', 'hops'],
      dtype='object')

In [23]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["model", "search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_176898/913412050.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["model", "search_type"]).apply(analyze_metrics).reset_index()

,model,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,DeepSeek-R1-Distill-Llama-70B-FP8,lexical_search_0_hop,0.865981,0.301335,0.575000,0.900000,0.688425,0.320757,0.575000,0.750000,0.325000,0.474342,0.575000,0.675000
1,DeepSeek-R1-Distill-Llama-70B-FP8,lexical_search_1_hop,0.876315,0.257049,0.410256,0.923077,0.653809,0.307324,0.551724,0.793103,0.300000,0.466092,0.533333,0.700000
2,DeepSeek-R1-Distill-Llama-70B-FP8,similarity_search_0_hop,0.884912,0.301091,0.600000,0.900000,0.639211,0.304725,0.600000,0.700000,0.175000,0.384808,0.600000,0.825000
3,DeepSeek-R1-Distill-Llama-70B-FP8,similarity_search_1_hop,0.843133,0.333365,0.358974,0.871795,0.623026,0.273280,0.400000,0.800000,0.418919,0.493197,0.378378,0.594595
4,anthropic.claude-v3-opus,lexical_search_0_hop,0.834748,0.293249,0.625000,0.906250,0.639130,0.243989,0.625000,0.812500,0.218750,0.420013,0.625000,0.781250
5,anthropic.claude-v3-opus,lexical_search_1_hop,0.945005,0.061450,0.382353,1.000000,0.734362,0.259468,0.433333,0.900000,0.482759,0.508548,0.448276,0.517241
6,anthropic.claude-v3-opus,similarity_search_0_hop,0.902379,0.238481,0.545455,0.939394,0.635807,0.225213,0.562500,0.843750,0.303030,0.466694,0.545455,0.696970
7,anthropic.claude-v3-opus,similarity_search_1_hop,0.834821,0.325354,0.424242,0.878788,0.702062,0.236349,0.451613,0.903226,0.406250,0.498991,0.437500,0.593750
8,gemini-1.5-pro,lexical_search_0_hop,0.987284,0.055406,0.875000,1.000000,0.861697,0.330413,0.875000,0.875000,0.000000,0.000000,0.875000,1.000000
9,gemini-1.5-pro,lexical_search_1_hop,0.989285,0.055153,0.775000,1.000000,0.840620,0.336954,0.815789,0.842105,0.025000,0.158114,0.775000,0.975000
10,gemini-1.5-pro,similarity_search_0_hop,0.994255,0.027013,0.875000,1.000000,0.859964,0.306490,0.875000,0.875000,0.000000,0.000000,0.875000,1.000000
11,gemini-1.5-pro,similarity_search_1_hop,0.943641,0.176364,0.800000,0.975000,0.833874,0.319440,0.800000,0.850000,0.075000,0.266747,0.800000,0.925000
12,gpt-4o-2024-08-06,lexical_search_0_hop,0.896538,0.253433,0.625000,0.925000,0.676760,0.305238,0.641026,0.794872,0.157051,0.364680,0.641026,0.846154
13,gpt-4o-2024-08-06,lexical_search_1_hop,0.925772,0.147838,0.400000,0.975000,0.690353,0.304475,0.516129,0.806452,0.343750,0.482559,0.500000,0.656250
14,gpt-4o-2024-08-06,similarity_search_0_hop,0.902262,0.238283,0.555556,0.916667,0.579130,0.307893,0.571429,0.685714,0.142857,0.355036,0.571429,0.857143
15,gpt-4o-2024-08-06,similarity_search_1_hop,0.877787,0.276411,0.400000,0.900000,0.618929,0.276919,0.457143,0.800000,0.342857,0.481594,0.457143,0.657143
16,llama-3-70b-instruct-awq,lexical_search_0_hop,0.856538,0.300093,0.575000,0.900000,0.657495,0.333347,0.589744,0.743590,0.275000,0.452203,0.575000,0.725000
17,llama-3-70b-instruct-awq,lexical_search_1_hop,0.899107,0.202056,0.300000,0.950000,0.596384,0.301047,0.400000,0.666667,0.366667,0.490133,0.400000,0.633333
18,llama-3-70b-instruct-awq,similarity_search_0_hop,0.820603,0.357086,0.625000,0.850000,0.623229,0.268328,0.641026,0.794872,0.229167,0.421447,0.625000,0.775000
19,llama-3-70b-instruct-awq,similarity_search_1_hop,0.818587,0.333362,0.325000,0.875000,0.521215,0.257881,0.361111,0.638889,0.445946,0.496988,0.351351,0.567568

In [24]:
grouped_df[
    [
        "model",
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
]

,model,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination
0,DeepSeek-R1-Distill-Llama-70B-FP8,lexical_search_0_hop,0.865981,0.301335,0.688425,0.320757,0.325000,0.474342
1,DeepSeek-R1-Distill-Llama-70B-FP8,lexical_search_1_hop,0.876315,0.257049,0.653809,0.307324,0.300000,0.466092
2,DeepSeek-R1-Distill-Llama-70B-FP8,similarity_search_0_hop,0.884912,0.301091,0.639211,0.304725,0.175000,0.384808
3,DeepSeek-R1-Distill-Llama-70B-FP8,similarity_search_1_hop,0.843133,0.333365,0.623026,0.273280,0.418919,0.493197
4,anthropic.claude-v3-opus,lexical_search_0_hop,0.834748,0.293249,0.639130,0.243989,0.218750,0.420013
5,anthropic.claude-v3-opus,lexical_search_1_hop,0.945005,0.061450,0.734362,0.259468,0.482759,0.508548
6,anthropic.claude-v3-opus,similarity_search_0_hop,0.902379,0.238481,0.635807,0.225213,0.303030,0.466694
7,anthropic.claude-v3-opus,similarity_search_1_hop,0.834821,0.325354,0.702062,0.236349,0.406250,0.498991
8,gemini-1.5-pro,lexical_search_0_hop,0.987284,0.055406,0.861697,0.330413,0.000000,0.000000
9,gemini-1.5-pro,lexical_search_1_hop,0.989285,0.055153,0.840620,0.336954,0.025000,0.158114
10,gemini-1.5-pro,similarity_search_0_hop,0.994255,0.027013,0.859964,0.306490,0.000000,0.000000
11,gemini-1.5-pro,similarity_search_1_hop,0.943641,0.176364,0.833874,0.319440,0.075000,0.266747
12,gpt-4o-2024-08-06,lexical_search_0_hop,0.896538,0.253433,0.676760,0.305238,0.157051,0.364680
13,gpt-4o-2024-08-06,lexical_search_1_hop,0.925772,0.147838,0.690353,0.304475,0.343750,0.482559
14,gpt-4o-2024-08-06,similarity_search_0_hop,0.902262,0.238283,0.579130,0.307893,0.142857,0.355036
15,gpt-4o-2024-08-06,similarity_search_1_hop,0.877787,0.276411,0.618929,0.276919,0.342857,0.481594
16,llama-3-70b-instruct-awq,lexical_search_0_hop,0.856538,0.300093,0.657495,0.333347,0.275000,0.452203
17,llama-3-70b-instruct-awq,lexical_search_1_hop,0.899107,0.202056,0.596384,0.301047,0.366667,0.490133
18,llama-3-70b-instruct-awq,similarity_search_0_hop,0.820603,0.357086,0.623229,0.268328,0.229167,0.421447
19,llama-3-70b-instruct-awq,similarity_search_1_hop,0.818587,0.333362,0.521215,0.257881,0.445946,0.496988

In [25]:
grouped_df[
    [
        "model",
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].to_dict()

{'model': {0: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  1: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  2: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  3: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  4: 'anthropic.claude-v3-opus',
  5: 'anthropic.claude-v3-opus',
  6: 'anthropic.claude-v3-opus',
  7: 'anthropic.claude-v3-opus',
  8: 'gemini-1.5-pro',
  9: 'gemini-1.5-pro',
  10: 'gemini-1.5-pro',
  11: 'gemini-1.5-pro',
  12: 'gpt-4o-2024-08-06',
  13: 'gpt-4o-2024-08-06',
  14: 'gpt-4o-2024-08-06',
  15: 'gpt-4o-2024-08-06',
  16: 'llama-3-70b-instruct-awq',
  17: 'llama-3-70b-instruct-awq',
  18: 'llama-3-70b-instruct-awq',
  19: 'llama-3-70b-instruct-awq'},
 'search_type': {0: 'lexical_search_0_hop',
  1: 'lexical_search_1_hop',
  2: 'similarity_search_0_hop',
  3: 'similarity_search_1_hop',
  4: 'lexical_search_0_hop',
  5: 'lexical_search_1_hop',
  6: 'similarity_search_0_hop',
  7: 'similarity_search_1_hop',
  8: 'lexical_search_0_hop',
  9: 'lexical_search_1_hop',
  10: 'similarity_search_0_hop',
  11: 'similarity_search_1_hop',
  12: 'lexical_search_0_hop',
  13: 'lexical_search_1_hop',
  14: 'similarity_search_0_hop',
  15: 'similarity_search_1_hop',
  16: 'lexical_search_0_hop',
  17: 'lexical_search_1_hop',
  18: 'similarity_search_0_hop',
  19: 'similarity_search_1_hop'},
 'avg_score_Answer Relevancy': {0: 0.86598132061312,
  1: 0.8763150212902858,
  2: 0.8849117571759887,
  3: 0.8431330787796785,
  4: 0.8347475721610482,
  5: 0.9450052360353716,
  6: 0.9023786018133044,
  7: 0.8348212656654349,
  8: 0.9872840520495625,
  9: 0.9892854444870588,
  10: 0.9942553425864729,
  11: 0.9436405404629185,
  12: 0.8965380502887654,
  13: 0.9257719297042266,
  14: 0.9022624472738889,
  15: 0.8777867655630665,
  16: 0.8565379756290668,
  17: 0.8991070619628998,
  18: 0.8206026411312519,
  19: 0.8185868224746902},
 'std_score_Answer Relevancy': {0: 0.3013351570473263,
  1: 0.257048805362046,
  2: 0.30109143421469997,
  3: 0.33336454080884137,
  4: 0.29324870194553926,
  5: 0.06145006359545406,
  6: 0.23848137294508234,
  7: 0.3253535646158535,
  8: 0.05540587396807781,
  9: 0.05515305248281869,
  10: 0.02701329506627158,
  11: 0.17636415603586583,
  12: 0.25343283073283834,
  13: 0.14783812653542927,
  14: 0.23828254354780254,
  15: 0.2764109287300937,
  16: 0.3000929654857263,
  17: 0.20205636364909685,
  18: 0.35708631761927767,
  19: 0.3333624897350433},
 'avg_score_Contextual Relevancy': {0: 0.688425375686405,
  1: 0.6538085092781882,
  2: 0.6392109850933381,
  3: 0.6230255458826887,
  4: 0.639129577020202,
  5: 0.7343620268620268,
  6: 0.6358068147130648,
  7: 0.7020615137550621,
  8: 0.8616970121381886,
  9: 0.840620131383029,
  10: 0.8599636081993175,
  11: 0.8338737907085161,
  12: 0.6767597075289382,
  13: 0.6903525685783751,
  14: 0.5791301945061343,
  15: 0.6189286299724159,
  16: 0.6574949623026546,
  17: 0.596384479717813,
  18: 0.6232292561239929,
  19: 0.521214612820005},
 'std_score_Contextual Relevancy': {0: 0.32075722984190824,
  1: 0.30732424408034525,
  2: 0.30472511776164124,
  3: 0.27327981277959706,
  4: 0.2439894325729546,
  5: 0.25946828996352156,
  6: 0.22521250868897127,
  7: 0.23634933875689074,
  8: 0.33041252612162114,
  9: 0.33695388599502857,
  10: 0.30649008133202443,
  11: 0.3194402981738698,
  12: 0.3052381615515825,
  13: 0.30447517065850166,
  14: 0.30789293226286224,
  15: 0.2769187522375345,
  16: 0.333347490660795,
  17: 0.301046884658918,
  18: 0.2683278927884652,
  19: 0.2578810951466921},
 'avg_score_Hallucination': {0: 0.325,
  1: 0.3,
  2: 0.175,
  3: 0.4189189189189189,
  4: 0.21875,
  5: 0.4827586206896552,
  6: 0.30303030303030304,
  7: 0.40625,
  8: 0.0,
  9: 0.025,
  10: 0.0,
  11: 0.075,
  12: 0.15705128205128205,
  13: 0.34375,
  14: 0.14285714285714285,
  15: 0.34285714285714286,
  16: 0.275,
  17: 0.36666666666666664,
  18: 0.22916666666666666,
  19: 0.44594594594594594},
 'std_score_Hallucination': {0: 0.4743416490252569,
  1: 0.466091599699399,
  2: 0.38480764425479264,
  3: 0.4931969619160719,
  4: 0.42001344064515445,
  5: 0.5085476277156078,
  6: 0.4666937221594376,
  7: 0.49899091723584604,
  8: 0.0,
  9: 0.15811388300841897,
  10: 0.0,
  11: 0.2667467828369185,
  12: 0.36468031773465637,
  13: 0.48255870443481425,
  14: 0.3550358012483632,
  15: 0.4815939919779354,
  16: 0.45220258677630265,
  17: 0.49013251785356093,
  18: 0.4214469377840126,
  19: 0.4969879243975622}}

In [26]:
markdown_table = """| Model                   | Search Type               | Avg Score Answer Relevancy (%) | Std Score Answer Relevancy (%) | Avg Score Contextual Relevancy (%) | Std Score Contextual Relevancy (%) | Avg Score Hallucination (%) | Std Score Hallucination (%) |
|-------------------------|---------------------------|--------------------------------|--------------------------------|------------------------------------|------------------------------------|-----------------------------|-----------------------------|
| anthropic.claude-v3-opus | lexical_search_0_hop      | 83.47                          | 29.32                          | 63.91                              | 24.40                              | 21.88                       | 42.00                       |
| anthropic.claude-v3-opus | lexical_search_1_hop      | 94.50                          | 6.15                           | 73.44                              | 25.95                              | 48.28                       | 50.85                       |
| anthropic.claude-v3-opus | similarity_search_0_hop   | 90.24                          | 23.85                          | 63.58                              | 22.52                              | 30.30                       | 46.67                       |
| anthropic.claude-v3-opus | similarity_search_1_hop   | 83.48                          | 32.54                          | 70.21                              | 23.63                              | 40.63                       | 49.90                       |
| gemini-1.5-pro           | lexical_search_0_hop      | 98.73                          | 5.54                           | 86.17                              | 33.04                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | lexical_search_1_hop      | 98.93                          | 5.52                           | 84.06                              | 33.70                              | 2.50                        | 15.81                       |
| gemini-1.5-pro           | similarity_search_0_hop   | 99.43                          | 2.70                           | 86.00                              | 30.65                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | similarity_search_1_hop   | 94.36                          | 17.64                          | 83.39                              | 31.94                              | 7.50                        | 26.67                       |
| gpt-4o-2024-08-06        | lexical_search_0_hop      | 89.65                          | 25.34                          | 67.68                              | 30.52                              | 15.71                       | 36.47                       |
| gpt-4o-2024-08-06        | lexical_search_1_hop      | 92.58                          | 14.78                          | 69.04                              | 30.45                              | 34.38                       | 48.26                       |
| gpt-4o-2024-08-06        | similarity_search_0_hop   | 90.23                          | 23.83                          | 57.91                              | 30.79                              | 14.29                       | 35.50                       |
| gpt-4o-2024-08-06        | similarity_search_1_hop   | 87.78                          | 27.64                          | 61.89                              | 27.69                              | 34.29                       | 48.16                       |"""

In [27]:
from IPython.display import display, Markdown

display(Markdown(markdown_table))

| Model                   | Search Type               | Avg Score Answer Relevancy (%) | Std Score Answer Relevancy (%) | Avg Score Contextual Relevancy (%) | Std Score Contextual Relevancy (%) | Avg Score Hallucination (%) | Std Score Hallucination (%) |
|-------------------------|---------------------------|--------------------------------|--------------------------------|------------------------------------|------------------------------------|-----------------------------|-----------------------------|
| anthropic.claude-v3-opus | lexical_search_0_hop      | 83.47                          | 29.32                          | 63.91                              | 24.40                              | 21.88                       | 42.00                       |
| anthropic.claude-v3-opus | lexical_search_1_hop      | 94.50                          | 6.15                           | 73.44                              | 25.95                              | 48.28                       | 50.85                       |
| anthropic.claude-v3-opus | similarity_search_0_hop   | 90.24                          | 23.85                          | 63.58                              | 22.52                              | 30.30                       | 46.67                       |
| anthropic.claude-v3-opus | similarity_search_1_hop   | 83.48                          | 32.54                          | 70.21                              | 23.63                              | 40.63                       | 49.90                       |
| gemini-1.5-pro           | lexical_search_0_hop      | 98.73                          | 5.54                           | 86.17                              | 33.04                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | lexical_search_1_hop      | 98.93                          | 5.52                           | 84.06                              | 33.70                              | 2.50                        | 15.81                       |
| gemini-1.5-pro           | similarity_search_0_hop   | 99.43                          | 2.70                           | 86.00                              | 30.65                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | similarity_search_1_hop   | 94.36                          | 17.64                          | 83.39                              | 31.94                              | 7.50                        | 26.67                       |
| gpt-4o-2024-08-06        | lexical_search_0_hop      | 89.65                          | 25.34                          | 67.68                              | 30.52                              | 15.71                       | 36.47                       |
| gpt-4o-2024-08-06        | lexical_search_1_hop      | 92.58                          | 14.78                          | 69.04                              | 30.45                              | 34.38                       | 48.26                       |
| gpt-4o-2024-08-06        | similarity_search_0_hop   | 90.23                          | 23.83                          | 57.91                              | 30.79                              | 14.29                       | 35.50                       |
| gpt-4o-2024-08-06        | similarity_search_1_hop   | 87.78                          | 27.64                          | 61.89                              | 27.69                              | 34.29                       | 48.16                       |

In [28]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_176898/1164691038.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()

,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,lexical_search_0_hop,0.890446,0.259780,0.656250,0.927083,0.707858,0.318132,0.663158,0.794737,0.194372,0.396030,0.659686,0.806283
1,lexical_search_1_hop,0.926803,0.169193,0.455959,0.968912,0.710300,0.312827,0.556962,0.803797,0.285714,0.453163,0.546584,0.714286
2,similarity_search_0_hop,0.900798,0.262567,0.645503,0.920635,0.671442,0.300532,0.655914,0.779570,0.165780,0.371879,0.648936,0.835106
3,similarity_search_1_hop,0.864749,0.294149,0.463542,0.901042,0.663000,0.293803,0.502825,0.796610,0.331492,0.469104,0.491713,0.674033

In [29]:
grouped_df.columns

Index(['search_type', 'avg_score_Answer Relevancy',
       'std_score_Answer Relevancy', 'success_rate_Answer Relevancy',
       'metric_success_rate_Answer Relevancy',
       'avg_score_Contextual Relevancy', 'std_score_Contextual Relevancy',
       'success_rate_Contextual Relevancy',
       'metric_success_rate_Contextual Relevancy', 'avg_score_Hallucination',
       'std_score_Hallucination', 'success_rate_Hallucination',
       'metric_success_rate_Hallucination'],
      dtype='object')

In [30]:
grouped_df[
    [
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].to_dict()

{'search_type': {0: 'lexical_search_0_hop',
  1: 'lexical_search_1_hop',
  2: 'similarity_search_0_hop',
  3: 'similarity_search_1_hop'},
 'avg_score_Answer Relevancy': {0: 0.8904457200644487,
  1: 0.9268033228066901,
  2: 0.9007975216796167,
  3: 0.8647492551010095},
 'std_score_Answer Relevancy': {0: 0.25977984128596426,
  1: 0.16919319485839127,
  2: 0.26256746802718184,
  3: 0.29414905004858133},
 'avg_score_Contextual Relevancy': {0: 0.7078577584266439,
  1: 0.7102995986389075,
  2: 0.6714424709627673,
  3: 0.6629998913626916},
 'std_score_Contextual Relevancy': {0: 0.3181320604722851,
  1: 0.31282730402724096,
  2: 0.3005322254523021,
  3: 0.2938028316084035},
 'avg_score_Hallucination': {0: 0.1943717277486911,
  1: 0.2857142857142857,
  2: 0.1657801418439716,
  3: 0.3314917127071823},
 'std_score_Hallucination': {0: 0.3960301331393453,
  1: 0.4531634835874829,
  2: 0.37187890730054607,
  3: 0.4691037390455279}}