# Analysis for the deepeval metrics

In [156]:
gold_source = (
    "/home/baptvit/Documents/github/graphrag-on-fhir/evaluations/data/gold/deepeval/"
)

In [157]:
import glob
import os

import pandas as pd

all_files = glob.glob(os.path.join(gold_source, "*.csv"))

all_dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df["consumer_id"] = file.split("/")[-1]
    all_dfs.append(df)


df_gold = pd.concat(all_dfs, ignore_index=True)

In [158]:
df_gold.columns

Index(['consumer_id', 'test_name', 'success', 'metric_name', 'threshold',
       'metric_success', 'score', 'reason', 'strict_mode', 'evaluation_model',
       'error', 'evaluation_cost', 'verbose_logs', 'conversational',
       'multimodal', 'input', 'actual_output', 'expected_output', 'context',
       'retrieval_context', 'Unnamed: 0', 'Unnamed: 0.3', 'Unnamed: 0.2',
       'Unnamed: 0.1'],
      dtype='object')

In [159]:
df_gold.head()

,consumer_id,test_name,success,metric_name,threshold,metric_success,score,reason,strict_mode,evaluation_model,...,multimodal,input,actual_output,expected_output,context,retrieval_context,Unnamed: 0,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1
0,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:llama-3-70b-instruct-awq:similarity_search_...,True,Hallucination,0.5,True,0.000000,The score is 0.00 because the actual output al...,False,Custom Azure OpenAI Model,...,False,Can you summarize my care plan history ?,"\n\nBased on the retrieved records, I can prov...",NaN,{'Main health record': 'Observation Type: Surv...,{'Main health record': 'Observation Type: Surv...,NaN,NaN,NaN,NaN
1,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:llama-3-70b-instruct-awq:similarity_search_...,True,Answer Relevancy,0.5,True,1.000000,The score is 1.00 because the output perfectly...,False,Custom Azure OpenAI Model,...,False,Can you summarize my care plan history ?,"\n\nBased on the retrieved records, I can prov...",NaN,{'Main health record': 'Observation Type: Surv...,{'Main health record': 'Observation Type: Surv...,NaN,NaN,NaN,NaN
2,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q5:llama-3-70b-instruct-awq:similarity_search_...,True,Contextual Relevancy,0.5,True,0.500000,The score is 0.50 because while there are seve...,False,Custom Azure OpenAI Model,...,False,Can you summarize my care plan history ?,"\n\nBased on the retrieved records, I can prov...",NaN,{'Main health record': 'Observation Type: Surv...,{'Main health record': 'Observation Type: Surv...,NaN,NaN,NaN,NaN
3,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q4:llama-3-70b-instruct-awq:similarity_search_...,False,Hallucination,0.5,False,1.000000,The score is 1.00 because the 'actual output' ...,False,Custom Azure OpenAI Model,...,False,"What are my recent laboratory values, what do ...","\n\nBased on the laboratory results retrieved,...",NaN,{'Main health record': 'Resource Type: Observa...,{'Main health record': 'Resource Type: Observa...,NaN,NaN,NaN,NaN
4,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,Q4:llama-3-70b-instruct-awq:similarity_search_...,False,Answer Relevancy,0.5,True,0.952381,The score is 0.95 because the output is highly...,False,Custom Azure OpenAI Model,...,False,"What are my recent laboratory values, what do ...","\n\nBased on the laboratory results retrieved,...",NaN,{'Main health record': 'Resource Type: Observa...,{'Main health record': 'Resource Type: Observa...,NaN,NaN,NaN,NaN

In [160]:
df_gold[df_gold["context"].isna()]

,consumer_id,test_name,success,metric_name,threshold,metric_success,score,reason,strict_mode,evaluation_model,...,multimodal,input,actual_output,expected_output,context,retrieval_context,Unnamed: 0,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1
1635,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,Q2:gemini-1.5-pro:lexical_search_1_hop,False,Hallucination,0.5,True,0.0,The score is 0.00 because the output aligns wi...,False,Gemini 1.5 Pro,...,False,"What are my documented allergies, and how seve...",I do not see any documented allergies for you ...,NaN,NaN,NaN,3.0,NaN,NaN,NaN
1636,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,Q2:gemini-1.5-pro:lexical_search_1_hop,False,Answer Relevancy,0.5,True,1.0,The score is 1.00 because the response is a pe...,False,Gemini 1.5 Pro,...,False,"What are my documented allergies, and how seve...",I do not see any documented allergies for you ...,NaN,NaN,NaN,4.0,NaN,NaN,NaN
1637,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,Q2:gemini-1.5-pro:lexical_search_1_hop,False,Contextual Relevancy,0.5,False,0.0,The score is 0.00 because there are no stateme...,False,Gemini 1.5 Pro,...,False,"What are my documented allergies, and how seve...",I do not see any documented allergies for you ...,NaN,NaN,NaN,5.0,NaN,NaN,NaN
1659,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,Q2:gemini-1.5-pro:similarity_search_0_hop,False,Hallucination,0.5,True,0.0,The score is 0.00 because the actual output do...,False,Gemini 1.5 Pro,...,False,"What are my documented allergies, and how seve...",I do not see any documented allergies in your ...,NaN,NaN,NaN,27.0,NaN,NaN,NaN
1660,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,Q2:gemini-1.5-pro:similarity_search_0_hop,False,Answer Relevancy,0.5,True,1.0,The score is 1.00 because the response is a pe...,False,Gemini 1.5 Pro,...,False,"What are my documented allergies, and how seve...",I do not see any documented allergies in your ...,NaN,NaN,NaN,28.0,NaN,NaN,NaN
1661,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,Q2:gemini-1.5-pro:similarity_search_0_hop,False,Contextual Relevancy,0.5,False,0.0,The score is 0.00 because there is no relevant...,False,Gemini 1.5 Pro,...,False,"What are my documented allergies, and how seve...",I do not see any documented allergies in your ...,NaN,NaN,NaN,29.0,NaN,NaN,NaN
1683,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,Q2:gemini-1.5-pro:lexical_search_0_hop,False,Hallucination,0.5,True,0.0,The score is 0.00 because the actual output al...,False,Gemini 1.5 Pro,...,False,"What are my documented allergies, and how seve...",I do not see any documented allergies for you ...,NaN,NaN,NaN,51.0,NaN,NaN,NaN
1684,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,Q2:gemini-1.5-pro:lexical_search_0_hop,False,Answer Relevancy,0.5,True,1.0,The score is 1.00 because the response is a pe...,False,Gemini 1.5 Pro,...,False,"What are my documented allergies, and how seve...",I do not see any documented allergies for you ...,NaN,NaN,NaN,52.0,NaN,NaN,NaN
1685,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,Q2:gemini-1.5-pro:lexical_search_0_hop,False,Contextual Relevancy,0.5,False,0.0,The score is 0.00 because there was no relevan...,False,Gemini 1.5 Pro,...,False,"What are my documented allergies, and how seve...",I do not see any documented allergies for you ...,NaN,NaN,NaN,53.0,NaN,NaN,NaN
1707,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,Q2:gemini-1.5-pro:similarity_search_1_hop,False,Hallucination,0.5,True,0.0,The score is 0.00 because the actual output al...,False,Gemini 1.5 Pro,...,False,"What are my documented allergies, and how seve...",I do not see any documented allergies in your ...,NaN,NaN,NaN,75.0,NaN,NaN,NaN
1708,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,Q2:gemini-1.5-pro:similarity_search_1_hop,False,Answer Relevancy,0.5,True,1.0,The score is 1.00 because the response is rele...,False,Gemini 1.5 Pro,...,False,"What are my documented allergies, and how seve...",I do not see any documented allergies in your ...,NaN,NaN,NaN,76.0,NaN,NaN,NaN
1709,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,Q2:gemini-1.5-pro:similarity_search_1_hop,False,Contextual Relevancy,0.5,False,0.0,The score is 0.00 because there are no relevan...,False,Gemini 1.5 Pro,...,False,"What are my documented allergies, and how seve...",I do not see any documented allergies in your ...,NaN,NaN,NaN,77.0,NaN,NaN,NaN

In [163]:
df_gold["error"].unique()

array([nan,
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 2982616 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 2934370 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1179389 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1153253 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1179526 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1156312 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1150255 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1127686 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1177756 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1156322 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 314840 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 304461 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 212669 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 205838 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Evaluation LLM outputted an invalid JSON. Please use a better evaluation model.',
       'Error code: 400 - {\'error\': {\'message\': "Error code: 400 - {\'message\': \'Input is too long for requested model.\'}", \'type\': \'invalid_request_error\', \'code\': \'400\'}}',
       'No route',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1297062 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "Invalid \'messages[0].content\': string too long. Expected a string with maximum length 1048576, but got a string with length 1272904 instead.", \'type\': \'invalid_request_error\', \'param\': \'messages[0].content\', \'code\': \'string_above_max_length\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 162230 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\', \'callstack\': \'  File "/usr/local/bin/gunicorn", line 8, in <module>\\n    sys.exit(run())\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 66, in run\\n    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 235, in run\\n    super().run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 71, in run\\n    Arbiter(self).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 201, in run\\n    self.manage_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 570, in manage_workers\\n    self.spawn_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 641, in spawn_workers\\n    self.spawn_worker()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker\\n    worker.init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process\\n    super().init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 143, in init_process\\n    self.run()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 107, in run\\n    return asyncio.run(self._serve())\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run\\n    return runner.run(main)\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run\\n    return self._loop.run_until_complete(task)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro\\n    await self.app(scope, receive_or_disconnect, send_no_error)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__\\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app\\n    await app(scope, receive, sender)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__\\n    await self.middleware_stack(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app\\n    await route.handle(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app\\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 75, in wrapped_app\\n    response = await handler(conn, exc)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 82, in _datadog_error_tracking_wrapper\\n    return await call_next(request, exception)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 112, in create_response_from_api_error\\n    return _create_response(\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 51, in _create_response\\n    problem_response = {"message": message, "type": type, "param": param, "code": code, "callstack": "at ".join(traceback.format_stack())}\\n\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 156982 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 140503 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\', \'callstack\': \'  File "/usr/local/bin/gunicorn", line 8, in <module>\\n    sys.exit(run())\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 66, in run\\n    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 235, in run\\n    super().run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 71, in run\\n    Arbiter(self).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 210, in run\\n    self.manage_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 570, in manage_workers\\n    self.spawn_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 641, in spawn_workers\\n    self.spawn_worker()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker\\n    worker.init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process\\n    super().init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 143, in init_process\\n    self.run()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 107, in run\\n    return asyncio.run(self._serve())\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run\\n    return runner.run(main)\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run\\n    return self._loop.run_until_complete(task)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro\\n    await self.app(scope, receive_or_disconnect, send_no_error)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__\\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app\\n    await app(scope, receive, sender)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__\\n    await self.middleware_stack(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app\\n    await route.handle(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app\\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 75, in wrapped_app\\n    response = await handler(conn, exc)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 82, in _datadog_error_tracking_wrapper\\n    return await call_next(request, exception)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 112, in create_response_from_api_error\\n    return _create_response(\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 51, in _create_response\\n    problem_response = {"message": message, "type": type, "param": param, "code": code, "callstack": "at ".join(traceback.format_stack())}\\n\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 135564 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 145717 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\', \'callstack\': \'  File "/usr/local/bin/gunicorn", line 8, in <module>\\n    sys.exit(run())\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 66, in run\\n    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 235, in run\\n    super().run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 71, in run\\n    Arbiter(self).run()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 201, in run\\n    self.manage_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 570, in manage_workers\\n    self.spawn_workers()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 641, in spawn_workers\\n    self.spawn_worker()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker\\n    worker.init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process\\n    super().init_process()\\nat   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 143, in init_process\\n    self.run()\\nat   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 107, in run\\n    return asyncio.run(self._serve())\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run\\n    return runner.run(main)\\nat   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run\\n    return self._loop.run_until_complete(task)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro\\n    await self.app(scope, receive_or_disconnect, send_no_error)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/completionsapi/azureml/middlewares/request_context.py", line 20, in __call__\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__\\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app\\n    await app(scope, receive, sender)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__\\n    await self.middleware_stack(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app\\n    await route.handle(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle\\n    await self.app(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app\\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\\nat   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 75, in wrapped_app\\n    response = await handler(conn, exc)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 82, in _datadog_error_tracking_wrapper\\n    return await call_next(request, exception)\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 112, in create_response_from_api_error\\n    return _create_response(\\nat   File "/usr/local/lib/python3.11/site-packages/oai_fastapi/error_handling.py", line 51, in _create_response\\n    problem_response = {"message": message, "type": type, "param": param, "code": code, "callstack": "at ".join(traceback.format_stack())}\\n\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 135560 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',
       'Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 128000 tokens. However, your messages resulted in 154731 tokens. Please reduce the length of the messages.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}',

In [164]:
import numpy as np

df_gold = df_gold[df_gold["error"].isna()]
df_gold = df_gold[df_gold["context"].notna()]

In [166]:
df_gold = df_gold.query('not context.str.contains("No data available for this question")')

In [167]:
df_5 = df_gold[
    [
        "consumer_id",
        "test_name",
        "success",
        "metric_name",
        "threshold",
        "metric_success",
        "score",
        "reason",
    ]
].head()

In [168]:
df_5.to_dict()

{'consumer_id': {0: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv',
  1: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv',
  2: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv',
  3: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv',
  4: 'Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f6bbce1a32-llama-3-70b-instruct-awq_deepeval.csv'},
 'test_name': {0: 'Q5:llama-3-70b-instruct-awq:similarity_search_0_hop',
  1: 'Q5:llama-3-70b-instruct-awq:similarity_search_0_hop',
  2: 'Q5:llama-3-70b-instruct-awq:similarity_search_0_hop',
  3: 'Q4:llama-3-70b-instruct-awq:similarity_search_0_hop',
  4: 'Q4:llama-3-70b-instruct-awq:similarity_search_0_hop'},
 'success': {0: True, 1: True, 2: True, 3: False, 4: False},
 'metric_name': {0: 'Hallucination',
  1: 'Answer Relevancy',
  2: 'Contextual Relevancy',
  3: 'Hallucination',
  4: 'Answer Relevancy'},
 'threshold': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'metric_success': {0: True, 1: True, 2: True, 3: False, 4: True},
 'score': {0: 0.0, 1: 1.0, 2: 0.5, 3: 1.0, 4: 0.9523809523809524},
 'reason': {0: 'The score is 0.00 because the actual output aligns perfectly with the provided contexts and there are no contradictions.',
  1: 'The score is 1.00 because the output perfectly addresses the input without any irrelevant statements. Great job staying focused and precise!',
  2: "The score is 0.50 because while there are several relevant care plan details provided, such as 'Care Plan for Lifestyle education regarding hypertension' and 'Care Plan for Physiotherapy care plan,' the majority of the retrieval context is irrelevant, focusing on topics like social determinants of health and insurance claims.",
  3: "The score is 1.00 because the 'actual output' does not align with the context data and fails to reference specific findings or data points explicitly, indicating a complete lack of factual basis from the provided context.",
  4: 'The score is 0.95 because the output is highly relevant and mostly addresses the input, but it includes repeated mentions of specific healthcare facilities that are unnecessary and do not directly address the inquiry about laboratory values, their meanings, or ways to improve them.'}}

In [169]:
# Create DataFrame
df = df_gold

# Create the pivot table
pivot = pd.pivot_table(
    df,
    values=["success", "threshold", "metric_success", "score"],
    index=["consumer_id", "test_name"],
    columns=["metric_name"],
    aggfunc="first",  # Use 'first' to get the value as is since duplicates are unlikely
)

# Optional: Flatten the column multi-index for cleaner display
pivot.columns = ["_".join(col).strip() for col in pivot.columns.values]
pivot.reset_index(inplace=True)

# Display the pivot table
pivot

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,success_Hallucination,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,False,True,1.000000,0.333333,0.0,False,False,False,0.5,0.5,0.5
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.968750,1.000000,0.0,True,True,True,0.5,0.5,0.5
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarit...,True,False,False,0.838710,0.461538,1.0,False,False,False,0.5,0.5,0.5
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarit...,True,True,False,0.833333,0.750000,1.0,False,False,False,0.5,0.5,0.5
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.956522,1.000000,0.0,True,True,True,0.5,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
780,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:llama-3-70b-instruct-awq:similarity_search_...,True,True,True,0.666667,0.692308,0.0,True,True,True,0.5,0.5,0.5
781,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
782,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:lexical_search_1_hop,True,True,False,0.740741,0.571429,1.0,False,False,False,0.5,0.5,0.5
783,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:similarity_search_...,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
784,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:similarity_search_...,True,True,True,0.886364,0.500000,0.0,True,True,True,0.5,0.5,0.5

In [170]:
pivot.to_csv(
    "/home/baptvit/Documents/mestrado/master-experiments/evaluations/data/gold/Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58_deepeval_results.csv"
)

In [171]:
pivot.head().to_dict()

{'consumer_id': {0: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv',
  1: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv',
  2: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv',
  3: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv',
  4: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-DeepSeek-R1-Distill-Llama-70B-FP8_deepeval.csv'},
 'test_name': {0: 'Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_0_hop',
  1: 'Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_1_hop',
  2: 'Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity_search_0_hop',
  3: 'Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity_search_1_hop',
  4: 'Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_0_hop'},
 'metric_success_Answer Relevancy': {0: True,
  1: True,
  2: True,
  3: True,
  4: True},
 'metric_success_Contextual Relevancy': {0: False,
  1: True,
  2: False,
  3: True,
  4: True},
 'metric_success_Hallucination': {0: True,
  1: True,
  2: False,
  3: False,
  4: True},
 'score_Answer Relevancy': {0: 1.0,
  1: 0.96875,
  2: 0.8387096774193549,
  3: 0.8333333333333334,
  4: 0.9565217391304348},
 'score_Contextual Relevancy': {0: 0.3333333333333333,
  1: 1.0,
  2: 0.4615384615384615,
  3: 0.75,
  4: 1.0},
 'score_Hallucination': {0: 0.0, 1: 0.0, 2: 1.0, 3: 1.0, 4: 0.0},
 'success_Answer Relevancy': {0: False, 1: True, 2: False, 3: False, 4: True},
 'success_Contextual Relevancy': {0: False,
  1: True,
  2: False,
  3: False,
  4: True},
 'success_Hallucination': {0: False, 1: True, 2: False, 3: False, 4: True},
 'threshold_Answer Relevancy': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'threshold_Contextual Relevancy': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'threshold_Hallucination': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5}}

In [172]:
df = pivot
# Analysis 1: Overall success rates by metric
success_rates = (
    df[
        [
            "metric_success_Answer Relevancy",
            "metric_success_Contextual Relevancy",
            "metric_success_Hallucination",
        ]
    ].mean()
    * 100
)

print("Overall Success Rates by Metric (%):")
print(success_rates)

# Analysis 2: Average scores by metric
average_scores = df[
    ["score_Answer Relevancy", "score_Contextual Relevancy", "score_Hallucination"]
].mean()

print("\nAverage Scores by Metric:")
print(average_scores)


# Analysis 3: Threshold compliance (scores >= threshold)
def threshold_compliance(row, metric):
    return row[f"score_{metric}"] >= row[f"threshold_{metric}"]


for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
    df[f"threshold_compliance_{metric}"] = df.apply(
        threshold_compliance, axis=1, metric=metric
    )

threshold_compliance_rates = (
    df[
        [
            "threshold_compliance_Answer Relevancy",
            "threshold_compliance_Contextual Relevancy",
            "threshold_compliance_Hallucination",
        ]
    ].mean()
    * 100
)

print("\nThreshold Compliance Rates by Metric (%):")
print(threshold_compliance_rates)

# Analysis 4: Breakdown by test_name
breakdown = df.groupby(["consumer_id", "test_name"]).mean()

print("\nBreakdown by Test Name:")
print(breakdown)

Overall Success Rates by Metric (%):
metric_success_Answer Relevancy        95.774648
metric_success_Contextual Relevancy    84.357542
metric_success_Hallucination           77.353342
dtype: object

Average Scores by Metric:
score_Answer Relevancy        0.925793
score_Contextual Relevancy    0.737989
score_Hallucination           0.227815
dtype: float64

Threshold Compliance Rates by Metric (%):
threshold_compliance_Answer Relevancy        95.286624
threshold_compliance_Contextual Relevancy    76.942675
threshold_compliance_Hallucination           21.401274
dtype: float64

Breakdown by Test Name:
                                                                                                      metric_success_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                             1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                             1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             1.0
...                                                                                                                               ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                             1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                               1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                               1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                             1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                             1.0

                                                                                                      metric_success_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                                 0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                                 1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                                 0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                                 1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                                 1.0
...                                                                                                                                   ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                                 1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                                   1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                                   1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                                 1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                                 1.0

                                                                                                      metric_success_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                          0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                          0.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
...                                                                                                                            ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                          1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                            1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                            0.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                          1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                          1.0

                                                                                                       score_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                1.000000
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                0.968750
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                0.838710
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                0.833333
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                0.956522
...                                                                                                                       ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                0.666667
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                  1.000000
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                  0.740741
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                1.000000
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                0.886364

                                                                                                       score_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                    0.333333
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                    1.000000
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                    0.461538
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                    0.750000
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                    1.000000
...                                                                                                                           ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                    0.692308
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                      1.000000
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                      0.571429
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                    1.000000
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                    0.500000

                                                                                                       score_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                  0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                  0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                  1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                  1.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                  0.0
...                                                                                                                    ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                  0.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                    0.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                    1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                  0.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                  0.0

                                                                                                      success_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                      0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                      0.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      1.0
...                                                                                                                        ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                      1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                        1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                        0.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                      1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                      1.0

                                                                                                      success_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                          0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                          0.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                          1.0
...                                                                                                                            ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                          1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                            1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                            0.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                          1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                          1.0

                                                                                                      success_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                   0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                   1.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                   0.0
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                   0.0
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                   1.0
...                                                                                                                     ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                   1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                     1.0
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                     0.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                   1.0
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                   1.0

                                                                                                       threshold_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                         0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                         0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                         0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                         0.5
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                         0.5
...                                                                                                                           ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                         0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                           0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                           0.5
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                         0.5
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                         0.5

                                                                                                       threshold_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                             0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                             0.5
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                             0.5
...                                                                                                                               ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                             0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                               0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                               0.5
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                             0.5
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_1...                             0.5

                                                                                                       threshold_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                      0.5
                                                   Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity...                      0.5
                                                   Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_se...                      0.5
...                                                                                                                        ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:llama-3-70b-instruct-awq:similarity_search_1...                      0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_0_hop                        0.5
                                                   Q8:llama-3-70b-instruct-awq:lexical_search_1_hop                        0.5
                                                   Q8:llama-3-70b-instruct-awq:similarity_search_0...                      0.5

In [173]:
df = pivot

df[["question", "model", "search_type"]] = df["test_name"].str.split(":", expand=True)

In [174]:
df["hops"] = df["test_name"].str[-5:]

In [175]:
df["hops"] = df["hops"].str.replace("_hop", "", regex=False).astype(int)

In [176]:
df = df.replace("anthropic.claude-v3-5-sonnet-v2", "anthropic.claude-v3-opus")
df = df.replace("gpt-4o-2024-11-20", "gpt-4o-2024-08-06")

In [177]:
df = df.replace("lexical_search_0_hop", "L0")
df = df.replace("lexical_search_1_hop", "L1")
df = df.replace("similarity_search_1_hop", "S1")
df = df.replace("similarity_search_0_hop", "S0")

In [178]:
df = df[df["search_type"] != "lexical_search_2_hop"]

In [179]:
df

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,...,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination,threshold_compliance_Answer Relevancy,threshold_compliance_Contextual Relevancy,threshold_compliance_Hallucination,question,model,search_type,hops
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,False,True,1.000000,0.333333,0.0,False,False,...,0.5,0.5,0.5,True,False,False,Q1,DeepSeek-R1-Distill-Llama-70B-FP8,L0,0
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.968750,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q1,DeepSeek-R1-Distill-Llama-70B-FP8,L1,1
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarit...,True,False,False,0.838710,0.461538,1.0,False,False,...,0.5,0.5,0.5,True,False,True,Q1,DeepSeek-R1-Distill-Llama-70B-FP8,S0,0
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarit...,True,True,False,0.833333,0.750000,1.0,False,False,...,0.5,0.5,0.5,True,True,True,Q1,DeepSeek-R1-Distill-Llama-70B-FP8,S1,1
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_s...,True,True,True,0.956522,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q2,DeepSeek-R1-Distill-Llama-70B-FP8,L0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
780,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:llama-3-70b-instruct-awq:similarity_search_...,True,True,True,0.666667,0.692308,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q7,llama-3-70b-instruct-awq,S1,1
781,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,llama-3-70b-instruct-awq,L0,0
782,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:lexical_search_1_hop,True,True,False,0.740741,0.571429,1.0,False,False,...,0.5,0.5,0.5,True,True,True,Q8,llama-3-70b-instruct-awq,L1,1
783,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:similarity_search_...,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,llama-3-70b-instruct-awq,S0,0
784,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:llama-3-70b-instruct-awq:similarity_search_...,True,True,True,0.886364,0.500000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,llama-3-70b-instruct-awq,S1,1

In [180]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = (
    df.groupby(["consumer_id", "question", "search_type", "hops"])
    .apply(analyze_metrics)
    .reset_index()
)
grouped_df

/tmp/ipykernel_9130/833737725.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(analyze_metrics)

,consumer_id,question,search_type,hops,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,L0,0,1.000000,0.0,1.0,0.333333,0.0,0.0,0.0,0.0,1.0
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,L1,1,0.968750,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,S0,0,0.838710,0.0,1.0,0.461538,0.0,0.0,1.0,0.0,0.0
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,S1,1,0.833333,0.0,1.0,0.750000,0.0,1.0,1.0,0.0,0.0
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2,L0,0,0.956522,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
780,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7,S1,1,0.666667,1.0,1.0,0.692308,1.0,1.0,0.0,1.0,1.0
781,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,L0,0,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
782,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,L1,1,0.740741,0.0,1.0,0.571429,0.0,1.0,1.0,0.0,0.0
783,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,S0,0,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
784,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,S1,1,0.886364,1.0,1.0,0.500000,1.0,1.0,0.0,1.0,1.0

In [181]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = (
    df.groupby(["consumer_id", "search_type"]).apply(analyze_metrics).reset_index()
)
grouped_df

/tmp/ipykernel_9130/1437396366.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(["consumer_id", "search_type"]).apply(analyze_metrics).reset_index()

,consumer_id,search_type,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L0,0.985945,0.625000,1.000000,0.682411,0.625000,0.625000,0.250000,0.625000,0.750000
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L1,0.971551,0.500000,1.000000,0.877381,0.666667,1.000000,0.333333,0.666667,0.666667
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,S0,0.974839,0.750000,1.000000,0.725752,0.750000,0.875000,0.250000,0.750000,0.750000
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,S1,0.854167,0.250000,0.875000,0.756250,0.250000,1.000000,0.812500,0.250000,0.250000
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,L0,0.771987,0.625000,0.875000,0.681324,0.625000,0.875000,0.125000,0.625000,0.875000
...,...,...,...,...,...,...,...,...,...,...,...
102,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,S1,0.905377,0.428571,1.000000,0.664281,0.500000,0.833333,0.333333,0.500000,0.666667
103,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,L0,0.960111,0.428571,1.000000,0.654942,0.428571,0.857143,0.428571,0.428571,0.571429
104,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,L1,0.868481,0.142857,0.857143,0.576190,0.250000,0.750000,0.500000,0.250000,0.500000
105,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,S0,0.945238,0.714286,1.000000,0.670779,0.714286,0.857143,0.142857,0.714286,0.857143
106,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,S1,0.760570,0.250000,0.875000,0.463187,0.285714,0.571429,0.642857,0.285714,0.428571

In [182]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_9130/3565463073.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()

,search_type,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,L0,0.913174,0.707447,0.946809,0.760118,0.715054,0.849462,0.171791,0.711230,0.828877
1,L1,0.931318,0.485294,0.970588,0.765776,0.607362,0.858896,0.248521,0.585799,0.751479
2,S0,0.947417,0.675000,0.965000,0.718173,0.699482,0.823834,0.165144,0.678392,0.834171
3,S1,0.909499,0.502646,0.947090,0.710283,0.545977,0.844828,0.337079,0.533708,0.668539

In [183]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["question"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_9130/1271303342.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["question"]).apply(analyze_metrics).reset_index()

,question,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Q1,0.832830,0.417476,0.922330,0.578406,0.438776,0.581633,0.208333,0.413462,0.798077
1,Q2,0.883785,0.762712,0.898305,0.724056,0.789474,0.807018,0.078947,0.789474,0.929825
2,Q3,0.905275,0.549020,0.950980,0.706648,0.602151,0.860215,0.240489,0.608696,0.760870
3,Q4,0.951326,0.378641,0.970874,0.675308,0.448276,0.816092,0.397727,0.443182,0.602273
4,Q5,0.981704,0.669903,0.990291,0.750797,0.711340,0.845361,0.146970,0.690000,0.850000
5,Q6,0.993662,0.407767,1.000000,0.712784,0.488372,0.895349,0.478261,0.456522,0.521739
6,Q7,0.879106,0.688679,0.905660,0.839088,0.752577,0.938144,0.204082,0.744898,0.795918
7,Q8,0.962223,0.931373,1.000000,0.895611,0.940594,0.990099,0.049020,0.931373,0.950980

In [184]:
df.columns

Index(['consumer_id', 'test_name', 'metric_success_Answer Relevancy',
       'metric_success_Contextual Relevancy', 'metric_success_Hallucination',
       'score_Answer Relevancy', 'score_Contextual Relevancy',
       'score_Hallucination', 'success_Answer Relevancy',
       'success_Contextual Relevancy', 'success_Hallucination',
       'threshold_Answer Relevancy', 'threshold_Contextual Relevancy',
       'threshold_Hallucination', 'threshold_compliance_Answer Relevancy',
       'threshold_compliance_Contextual Relevancy',
       'threshold_compliance_Hallucination', 'question', 'model',
       'search_type', 'hops'],
      dtype='object')

In [185]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["model", "search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_9130/913412050.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["model", "search_type"]).apply(analyze_metrics).reset_index()

,model,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,DeepSeek-R1-Distill-Llama-70B-FP8,L0,0.884845,0.276843,0.621622,0.918919,0.744244,0.262226,0.621622,0.810811,0.270270,0.450225,0.621622,0.729730
1,DeepSeek-R1-Distill-Llama-70B-FP8,L1,0.876315,0.257049,0.410256,0.923077,0.677159,0.285567,0.571429,0.821429,0.275862,0.454859,0.551724,0.724138
2,DeepSeek-R1-Distill-Llama-70B-FP8,S0,0.956661,0.166325,0.648649,0.972973,0.691039,0.252558,0.648649,0.756757,0.189189,0.397061,0.648649,0.810811
3,DeepSeek-R1-Distill-Llama-70B-FP8,S1,0.913394,0.233769,0.388889,0.944444,0.681434,0.202048,0.437500,0.875000,0.455882,0.497991,0.411765,0.558824
4,anthropic.claude-v3-opus,L0,0.834101,0.302956,0.666667,0.900000,0.681738,0.183267,0.666667,0.866667,0.233333,0.430183,0.666667,0.766667
5,anthropic.claude-v3-opus,L1,0.950422,0.057317,0.406250,1.000000,0.786816,0.171785,0.464286,0.964286,0.518519,0.509175,0.481481,0.481481
6,anthropic.claude-v3-opus,S0,0.960597,0.053636,0.580645,1.000000,0.678194,0.156463,0.600000,0.900000,0.322581,0.475191,0.580645,0.677419
7,anthropic.claude-v3-opus,S1,0.888681,0.251898,0.451613,0.935484,0.750480,0.149052,0.482759,0.965517,0.433333,0.504007,0.466667,0.566667
8,gemini-1.5-pro,L0,0.989178,0.051221,0.893617,1.000000,0.879931,0.294413,0.893617,0.893617,0.000000,0.000000,0.893617,1.000000
9,gemini-1.5-pro,L1,0.986848,0.057237,0.724138,1.000000,0.873287,0.282182,0.823529,0.882353,0.035714,0.187256,0.750000,0.964286
10,gemini-1.5-pro,S0,0.994671,0.023320,0.774194,1.000000,0.829615,0.301338,0.827586,0.844828,0.027370,0.153608,0.774194,0.967742
11,gemini-1.5-pro,S1,0.949127,0.163398,0.808511,0.978723,0.842410,0.285153,0.808511,0.851064,0.063830,0.247092,0.808511,0.936170
12,gpt-4o-2024-08-06,L0,0.915176,0.215178,0.675676,0.945946,0.733156,0.242131,0.694444,0.861111,0.170139,0.376962,0.694444,0.833333
13,gpt-4o-2024-08-06,L1,0.919753,0.152253,0.432432,0.972973,0.764319,0.210661,0.571429,0.892857,0.310345,0.470824,0.551724,0.689655
14,gpt-4o-2024-08-06,S0,0.903478,0.244476,0.606061,0.909091,0.633424,0.261671,0.625000,0.750000,0.156250,0.368902,0.625000,0.843750
15,gpt-4o-2024-08-06,S1,0.921932,0.193768,0.432432,0.945946,0.676953,0.208706,0.500000,0.875000,0.375000,0.491869,0.500000,0.625000
16,llama-3-70b-instruct-awq,L0,0.907068,0.231294,0.621622,0.945946,0.712286,0.283731,0.638889,0.805556,0.243243,0.434959,0.621622,0.756757
17,llama-3-70b-instruct-awq,L1,0.898183,0.206496,0.315789,0.947368,0.638983,0.262896,0.428571,0.714286,0.321429,0.475595,0.428571,0.678571
18,llama-3-70b-instruct-awq,S0,0.887138,0.278336,0.675676,0.918919,0.675165,0.205193,0.694444,0.861111,0.247748,0.433229,0.675676,0.756757
19,llama-3-70b-instruct-awq,S1,0.861670,0.281088,0.342105,0.921053,0.551874,0.230435,0.382353,0.676471,0.471429,0.499159,0.371429,0.542857

In [186]:
grouped_df["ARS"] = grouped_df['avg_score_Answer Relevancy'].round(2).astype(str) + "±" + grouped_df['std_score_Answer Relevancy'].round(2).astype(str)

In [187]:
grouped_df["CRS"] = grouped_df['avg_score_Contextual Relevancy'].round(2).astype(str) + "±" + grouped_df['std_score_Contextual Relevancy'].round(2).astype(str)

In [188]:
grouped_df["HALS"] = grouped_df['avg_score_Hallucination'].round(2).astype(str) + "±" + grouped_df['std_score_Hallucination'].round(2).astype(str)

In [189]:
grouped_df[
    [
        "model",
        "search_type",
        "ARS",
        "CRS",
        "HALS"
    ]
].sort_values(by=["model", 'search_type'])

,model,search_type,ARS,CRS,HALS
0,DeepSeek-R1-Distill-Llama-70B-FP8,L0,0.88±0.28,0.74±0.26,0.27±0.45
1,DeepSeek-R1-Distill-Llama-70B-FP8,L1,0.88±0.26,0.68±0.29,0.28±0.45
2,DeepSeek-R1-Distill-Llama-70B-FP8,S0,0.96±0.17,0.69±0.25,0.19±0.4
3,DeepSeek-R1-Distill-Llama-70B-FP8,S1,0.91±0.23,0.68±0.2,0.46±0.5
4,anthropic.claude-v3-opus,L0,0.83±0.3,0.68±0.18,0.23±0.43
5,anthropic.claude-v3-opus,L1,0.95±0.06,0.79±0.17,0.52±0.51
6,anthropic.claude-v3-opus,S0,0.96±0.05,0.68±0.16,0.32±0.48
7,anthropic.claude-v3-opus,S1,0.89±0.25,0.75±0.15,0.43±0.5
8,gemini-1.5-pro,L0,0.99±0.05,0.88±0.29,0.0±0.0
9,gemini-1.5-pro,L1,0.99±0.06,0.87±0.28,0.04±0.19
10,gemini-1.5-pro,S0,0.99±0.02,0.83±0.3,0.03±0.15
11,gemini-1.5-pro,S1,0.95±0.16,0.84±0.29,0.06±0.25
12,gpt-4o-2024-08-06,L0,0.92±0.22,0.73±0.24,0.17±0.38
13,gpt-4o-2024-08-06,L1,0.92±0.15,0.76±0.21,0.31±0.47
14,gpt-4o-2024-08-06,S0,0.9±0.24,0.63±0.26,0.16±0.37
15,gpt-4o-2024-08-06,S1,0.92±0.19,0.68±0.21,0.38±0.49
16,llama-3-70b-instruct-awq,L0,0.91±0.23,0.71±0.28,0.24±0.43
17,llama-3-70b-instruct-awq,L1,0.9±0.21,0.64±0.26,0.32±0.48
18,llama-3-70b-instruct-awq,S0,0.89±0.28,0.68±0.21,0.25±0.43
19,llama-3-70b-instruct-awq,S1,0.86±0.28,0.55±0.23,0.47±0.5

In [191]:
grouped_df[
    [
        "model",
        "search_type",
        "ARS",
        "CRS",
        "HALS"
    ]
].sort_values(by=["model", 'search_type']).to_dict()

{'model': {0: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  1: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  2: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  3: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  4: 'anthropic.claude-v3-opus',
  5: 'anthropic.claude-v3-opus',
  6: 'anthropic.claude-v3-opus',
  7: 'anthropic.claude-v3-opus',
  8: 'gemini-1.5-pro',
  9: 'gemini-1.5-pro',
  10: 'gemini-1.5-pro',
  11: 'gemini-1.5-pro',
  12: 'gpt-4o-2024-08-06',
  13: 'gpt-4o-2024-08-06',
  14: 'gpt-4o-2024-08-06',
  15: 'gpt-4o-2024-08-06',
  16: 'llama-3-70b-instruct-awq',
  17: 'llama-3-70b-instruct-awq',
  18: 'llama-3-70b-instruct-awq',
  19: 'llama-3-70b-instruct-awq'},
 'search_type': {0: 'L0',
  1: 'L1',
  2: 'S0',
  3: 'S1',
  4: 'L0',
  5: 'L1',
  6: 'S0',
  7: 'S1',
  8: 'L0',
  9: 'L1',
  10: 'S0',
  11: 'S1',
  12: 'L0',
  13: 'L1',
  14: 'S0',
  15: 'S1',
  16: 'L0',
  17: 'L1',
  18: 'S0',
  19: 'S1'},
 'ARS': {0: '0.88±0.28',
  1: '0.88±0.26',
  2: '0.96±0.17',
  3: '0.91±0.23',
  4: '0.83±0.3',
  5: '0.95±0.06',
  6: '0.96±0.05',
  7: '0.89±0.25',
  8: '0.99±0.05',
  9: '0.99±0.06',
  10: '0.99±0.02',
  11: '0.95±0.16',
  12: '0.92±0.22',
  13: '0.92±0.15',
  14: '0.9±0.24',
  15: '0.92±0.19',
  16: '0.91±0.23',
  17: '0.9±0.21',
  18: '0.89±0.28',
  19: '0.86±0.28'},
 'CRS': {0: '0.74±0.26',
  1: '0.68±0.29',
  2: '0.69±0.25',
  3: '0.68±0.2',
  4: '0.68±0.18',
  5: '0.79±0.17',
  6: '0.68±0.16',
  7: '0.75±0.15',
  8: '0.88±0.29',
  9: '0.87±0.28',
  10: '0.83±0.3',
  11: '0.84±0.29',
  12: '0.73±0.24',
  13: '0.76±0.21',
  14: '0.63±0.26',
  15: '0.68±0.21',
  16: '0.71±0.28',
  17: '0.64±0.26',
  18: '0.68±0.21',
  19: '0.55±0.23'},
 'HALS': {0: '0.27±0.45',
  1: '0.28±0.45',
  2: '0.19±0.4',
  3: '0.46±0.5',
  4: '0.23±0.43',
  5: '0.52±0.51',
  6: '0.32±0.48',
  7: '0.43±0.5',
  8: '0.0±0.0',
  9: '0.04±0.19',
  10: '0.03±0.15',
  11: '0.06±0.25',
  12: '0.17±0.38',
  13: '0.31±0.47',
  14: '0.16±0.37',
  15: '0.38±0.49',
  16: '0.24±0.43',
  17: '0.32±0.48',
  18: '0.25±0.43',
  19: '0.47±0.5'}}

In [ ]:
## PARAR AQUI

In [107]:
grouped_df[
    [
        "model",
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].sort_values(by=["model", 'search_type'])

,model,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination
0,DeepSeek-R1-Distill-Llama-70B-FP8,L0,0.884845,0.276843,0.744244,0.262226,0.270270,0.450225
1,DeepSeek-R1-Distill-Llama-70B-FP8,L1,0.876315,0.257049,0.677159,0.285567,0.275862,0.454859
2,DeepSeek-R1-Distill-Llama-70B-FP8,S0,0.956661,0.166325,0.691039,0.252558,0.189189,0.397061
3,DeepSeek-R1-Distill-Llama-70B-FP8,S1,0.913394,0.233769,0.681434,0.202048,0.455882,0.497991
4,anthropic.claude-v3-opus,L0,0.834101,0.302956,0.681738,0.183267,0.233333,0.430183
5,anthropic.claude-v3-opus,L1,0.950422,0.057317,0.786816,0.171785,0.518519,0.509175
6,anthropic.claude-v3-opus,S0,0.960597,0.053636,0.678194,0.156463,0.322581,0.475191
7,anthropic.claude-v3-opus,S1,0.888681,0.251898,0.750480,0.149052,0.433333,0.504007
8,gemini-1.5-pro,L0,0.989178,0.051221,0.879931,0.294413,0.000000,0.000000
9,gemini-1.5-pro,L1,0.987495,0.055862,0.875724,0.279954,0.033898,0.182521
10,gemini-1.5-pro,S0,0.994994,0.022628,0.823626,0.298977,0.025712,0.148952
11,gemini-1.5-pro,S1,0.949127,0.163398,0.842410,0.285153,0.063830,0.247092
12,gpt-4o-2024-08-06,L0,0.915176,0.215178,0.733156,0.242131,0.170139,0.376962
13,gpt-4o-2024-08-06,L1,0.919753,0.152253,0.764319,0.210661,0.310345,0.470824
14,gpt-4o-2024-08-06,S0,0.903478,0.244476,0.633424,0.261671,0.156250,0.368902
15,gpt-4o-2024-08-06,S1,0.921932,0.193768,0.676953,0.208706,0.375000,0.491869
16,llama-3-70b-instruct-awq,L0,0.907068,0.231294,0.712286,0.283731,0.243243,0.434959
17,llama-3-70b-instruct-awq,L1,0.898183,0.206496,0.638983,0.262896,0.321429,0.475595
18,llama-3-70b-instruct-awq,S0,0.887138,0.278336,0.675165,0.205193,0.247748,0.433229
19,llama-3-70b-instruct-awq,S1,0.861670,0.281088,0.551874,0.230435,0.471429,0.499159

In [108]:
grouped_df[
    [
        "search_type",
        "model",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].sort_values(by=['search_type', "model"])

,search_type,model,avg_score_Answer Relevancy,std_score_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination
0,L0,DeepSeek-R1-Distill-Llama-70B-FP8,0.884845,0.276843,0.744244,0.262226,0.270270,0.450225
4,L0,anthropic.claude-v3-opus,0.834101,0.302956,0.681738,0.183267,0.233333,0.430183
8,L0,gemini-1.5-pro,0.989178,0.051221,0.879931,0.294413,0.000000,0.000000
12,L0,gpt-4o-2024-08-06,0.915176,0.215178,0.733156,0.242131,0.170139,0.376962
16,L0,llama-3-70b-instruct-awq,0.907068,0.231294,0.712286,0.283731,0.243243,0.434959
1,L1,DeepSeek-R1-Distill-Llama-70B-FP8,0.876315,0.257049,0.677159,0.285567,0.275862,0.454859
5,L1,anthropic.claude-v3-opus,0.950422,0.057317,0.786816,0.171785,0.518519,0.509175
9,L1,gemini-1.5-pro,0.987495,0.055862,0.875724,0.279954,0.033898,0.182521
13,L1,gpt-4o-2024-08-06,0.919753,0.152253,0.764319,0.210661,0.310345,0.470824
17,L1,llama-3-70b-instruct-awq,0.898183,0.206496,0.638983,0.262896,0.321429,0.475595
2,S0,DeepSeek-R1-Distill-Llama-70B-FP8,0.956661,0.166325,0.691039,0.252558,0.189189,0.397061
6,S0,anthropic.claude-v3-opus,0.960597,0.053636,0.678194,0.156463,0.322581,0.475191
10,S0,gemini-1.5-pro,0.994994,0.022628,0.823626,0.298977,0.025712,0.148952
14,S0,gpt-4o-2024-08-06,0.903478,0.244476,0.633424,0.261671,0.156250,0.368902
18,S0,llama-3-70b-instruct-awq,0.887138,0.278336,0.675165,0.205193,0.247748,0.433229
3,S1,DeepSeek-R1-Distill-Llama-70B-FP8,0.913394,0.233769,0.681434,0.202048,0.455882,0.497991
7,S1,anthropic.claude-v3-opus,0.888681,0.251898,0.750480,0.149052,0.433333,0.504007
11,S1,gemini-1.5-pro,0.949127,0.163398,0.842410,0.285153,0.063830,0.247092
15,S1,gpt-4o-2024-08-06,0.921932,0.193768,0.676953,0.208706,0.375000,0.491869
19,S1,llama-3-70b-instruct-awq,0.861670,0.281088,0.551874,0.230435,0.471429,0.499159

In [109]:
grouped_df[
    [
        "model",
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].to_dict()

{'model': {0: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  1: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  2: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  3: 'DeepSeek-R1-Distill-Llama-70B-FP8',
  4: 'anthropic.claude-v3-opus',
  5: 'anthropic.claude-v3-opus',
  6: 'anthropic.claude-v3-opus',
  7: 'anthropic.claude-v3-opus',
  8: 'gemini-1.5-pro',
  9: 'gemini-1.5-pro',
  10: 'gemini-1.5-pro',
  11: 'gemini-1.5-pro',
  12: 'gpt-4o-2024-08-06',
  13: 'gpt-4o-2024-08-06',
  14: 'gpt-4o-2024-08-06',
  15: 'gpt-4o-2024-08-06',
  16: 'llama-3-70b-instruct-awq',
  17: 'llama-3-70b-instruct-awq',
  18: 'llama-3-70b-instruct-awq',
  19: 'llama-3-70b-instruct-awq'},
 'search_type': {0: 'L0',
  1: 'L1',
  2: 'S0',
  3: 'S1',
  4: 'L0',
  5: 'L1',
  6: 'S0',
  7: 'S1',
  8: 'L0',
  9: 'L1',
  10: 'S0',
  11: 'S1',
  12: 'L0',
  13: 'L1',
  14: 'S0',
  15: 'S1',
  16: 'L0',
  17: 'L1',
  18: 'S0',
  19: 'S1'},
 'avg_score_Answer Relevancy': {0: 0.884844670933103,
  1: 0.8763150212902858,
  2: 0.9566613591091769,
  3: 0.9133941686779851,
  4: 0.8341011140088219,
  5: 0.9504222299542489,
  6: 0.9605965761238401,
  7: 0.8886807021599792,
  8: 0.9891779166379255,
  9: 0.9874950478905955,
  10: 0.9949938270522196,
  11: 0.9491273400400021,
  12: 0.9151762705824492,
  13: 0.9197534375180828,
  14: 0.9034782253088889,
  15: 0.9219316384465586,
  16: 0.9070680817611532,
  17: 0.8981828722416488,
  18: 0.8871379904121642,
  19: 0.8616703394470422},
 'std_score_Answer Relevancy': {0: 0.2768425501153924,
  1: 0.25704880536204594,
  2: 0.1663249301155657,
  3: 0.23376877072865843,
  4: 0.302955989963187,
  5: 0.05731718345423768,
  6: 0.05363583913707017,
  7: 0.25189806451317265,
  8: 0.05122115631127062,
  9: 0.05586183230026836,
  10: 0.022627634053322243,
  11: 0.16339782876625844,
  12: 0.21517805171815468,
  13: 0.1522533261997558,
  14: 0.24447587825061187,
  15: 0.1937679948918523,
  16: 0.23129377628122835,
  17: 0.20649626424320608,
  18: 0.2783359060292602,
  19: 0.28108801461628613},
 'avg_score_Contextual Relevancy': {0: 0.7442436493907083,
  1: 0.6771588131809806,
  2: 0.6910389028036088,
  3: 0.6814341908091909,
  4: 0.6817382154882154,
  5: 0.7868164573521715,
  6: 0.6781939356939357,
  7: 0.7504795491864457,
  8: 0.879931263285456,
  9: 0.8757239219216062,
  10: 0.823626470319997,
  11: 0.8424096671094333,
  12: 0.7331563498230165,
  13: 0.7643189152117723,
  14: 0.6334236502410844,
  15: 0.6769531890323299,
  16: 0.7122862091612092,
  17: 0.6389833711262283,
  18: 0.6751650274676592,
  19: 0.551874295927064},
 'std_score_Contextual Relevancy': {0: 0.26222626878837746,
  1: 0.2855674762187864,
  2: 0.2525579980146615,
  3: 0.20204841166452533,
  4: 0.1832670959065373,
  5: 0.17178515378250703,
  6: 0.15646308853537422,
  7: 0.1490523255720812,
  8: 0.29441295509229864,
  9: 0.27995363618691604,
  10: 0.29897699920609355,
  11: 0.2851530730751875,
  12: 0.2421310571643378,
  13: 0.21066080401804246,
  14: 0.2616714067092841,
  15: 0.20870558921501997,
  16: 0.2837306116427444,
  17: 0.2628961240749081,
  18: 0.20519306674074492,
  19: 0.2304345814113983},
 'avg_score_Hallucination': {0: 0.2702702702702703,
  1: 0.27586206896551724,
  2: 0.1891891891891892,
  3: 0.45588235294117646,
  4: 0.23333333333333334,
  5: 0.5185185185185185,
  6: 0.3225806451612903,
  7: 0.43333333333333335,
  8: 0.0,
  9: 0.03389830508474576,
  10: 0.02571166207529844,
  11: 0.06382978723404255,
  12: 0.1701388888888889,
  13: 0.3103448275862069,
  14: 0.15625,
  15: 0.375,
  16: 0.24324324324324326,
  17: 0.32142857142857145,
  18: 0.24774774774774774,
  19: 0.4714285714285714},
 'std_score_Hallucination': {0: 0.4502251688907482,
  1: 0.454858826147342,
  2: 0.3970612769556578,
  3: 0.4979906147774445,
  4: 0.4301830671520762,
  5: 0.5091750772173156,
  6: 0.4751909633114914,
  7: 0.5040069329937309,
  8: 0.0,
  9: 0.182520824972938,
  10: 0.14895197197514706,
  11: 0.24709224814516548,
  12: 0.3769624576061182,
  13: 0.4708236154307584,
  14: 0.36890203262847354,
  15: 0.4918693768379647,
  16: 0.43495883620084,
  17: 0.47559486560567094,
  18: 0.43322937075836365,
  19: 0.4991589565113966}}

In [26]:
markdown_table = """| Model                   | Search Type               | Avg Score Answer Relevancy (%) | Std Score Answer Relevancy (%) | Avg Score Contextual Relevancy (%) | Std Score Contextual Relevancy (%) | Avg Score Hallucination (%) | Std Score Hallucination (%) |
|-------------------------|---------------------------|--------------------------------|--------------------------------|------------------------------------|------------------------------------|-----------------------------|-----------------------------|
| anthropic.claude-v3-opus | lexical_search_0_hop      | 83.47                          | 29.32                          | 63.91                              | 24.40                              | 21.88                       | 42.00                       |
| anthropic.claude-v3-opus | lexical_search_1_hop      | 94.50                          | 6.15                           | 73.44                              | 25.95                              | 48.28                       | 50.85                       |
| anthropic.claude-v3-opus | similarity_search_0_hop   | 90.24                          | 23.85                          | 63.58                              | 22.52                              | 30.30                       | 46.67                       |
| anthropic.claude-v3-opus | similarity_search_1_hop   | 83.48                          | 32.54                          | 70.21                              | 23.63                              | 40.63                       | 49.90                       |
| gemini-1.5-pro           | lexical_search_0_hop      | 98.73                          | 5.54                           | 86.17                              | 33.04                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | lexical_search_1_hop      | 98.93                          | 5.52                           | 84.06                              | 33.70                              | 2.50                        | 15.81                       |
| gemini-1.5-pro           | similarity_search_0_hop   | 99.43                          | 2.70                           | 86.00                              | 30.65                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | similarity_search_1_hop   | 94.36                          | 17.64                          | 83.39                              | 31.94                              | 7.50                        | 26.67                       |
| gpt-4o-2024-08-06        | lexical_search_0_hop      | 89.65                          | 25.34                          | 67.68                              | 30.52                              | 15.71                       | 36.47                       |
| gpt-4o-2024-08-06        | lexical_search_1_hop      | 92.58                          | 14.78                          | 69.04                              | 30.45                              | 34.38                       | 48.26                       |
| gpt-4o-2024-08-06        | similarity_search_0_hop   | 90.23                          | 23.83                          | 57.91                              | 30.79                              | 14.29                       | 35.50                       |
| gpt-4o-2024-08-06        | similarity_search_1_hop   | 87.78                          | 27.64                          | 61.89                              | 27.69                              | 34.29                       | 48.16                       |"""

In [27]:
from IPython.display import display, Markdown

display(Markdown(markdown_table))

| Model                   | Search Type               | Avg Score Answer Relevancy (%) | Std Score Answer Relevancy (%) | Avg Score Contextual Relevancy (%) | Std Score Contextual Relevancy (%) | Avg Score Hallucination (%) | Std Score Hallucination (%) |
|-------------------------|---------------------------|--------------------------------|--------------------------------|------------------------------------|------------------------------------|-----------------------------|-----------------------------|
| anthropic.claude-v3-opus | lexical_search_0_hop      | 83.47                          | 29.32                          | 63.91                              | 24.40                              | 21.88                       | 42.00                       |
| anthropic.claude-v3-opus | lexical_search_1_hop      | 94.50                          | 6.15                           | 73.44                              | 25.95                              | 48.28                       | 50.85                       |
| anthropic.claude-v3-opus | similarity_search_0_hop   | 90.24                          | 23.85                          | 63.58                              | 22.52                              | 30.30                       | 46.67                       |
| anthropic.claude-v3-opus | similarity_search_1_hop   | 83.48                          | 32.54                          | 70.21                              | 23.63                              | 40.63                       | 49.90                       |
| gemini-1.5-pro           | lexical_search_0_hop      | 98.73                          | 5.54                           | 86.17                              | 33.04                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | lexical_search_1_hop      | 98.93                          | 5.52                           | 84.06                              | 33.70                              | 2.50                        | 15.81                       |
| gemini-1.5-pro           | similarity_search_0_hop   | 99.43                          | 2.70                           | 86.00                              | 30.65                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | similarity_search_1_hop   | 94.36                          | 17.64                          | 83.39                              | 31.94                              | 7.50                        | 26.67                       |
| gpt-4o-2024-08-06        | lexical_search_0_hop      | 89.65                          | 25.34                          | 67.68                              | 30.52                              | 15.71                       | 36.47                       |
| gpt-4o-2024-08-06        | lexical_search_1_hop      | 92.58                          | 14.78                          | 69.04                              | 30.45                              | 34.38                       | 48.26                       |
| gpt-4o-2024-08-06        | similarity_search_0_hop   | 90.23                          | 23.83                          | 57.91                              | 30.79                              | 14.29                       | 35.50                       |
| gpt-4o-2024-08-06        | similarity_search_1_hop   | 87.78                          | 27.64                          | 61.89                              | 27.69                              | 34.29                       | 48.16                       |

In [28]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_19658/1164691038.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()

,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,lexical_search_0_hop,0.894828,0.255413,0.665000,0.930000,0.714050,0.316999,0.671717,0.797980,0.186558,0.389831,0.668342,0.814070
1,lexical_search_1_hop,0.933050,0.161903,0.462963,0.972222,0.727291,0.308716,0.578035,0.815029,0.263736,0.441874,0.549451,0.736264
2,lexical_search_2_hop,1.000000,0.000000,0.000000,1.000000,0.000000,NaN,0.000000,0.000000,0.000000,NaN,0.000000,1.000000
3,similarity_search_0_hop,0.913134,0.247101,0.631336,0.930876,0.673354,0.304619,0.655502,0.770335,0.156776,0.362193,0.634259,0.842593
4,similarity_search_1_hop,0.869476,0.289173,0.475000,0.905000,0.668050,0.292412,0.513514,0.794595,0.317460,0.463867,0.502646,0.687831

In [29]:
grouped_df.columns

Index(['search_type', 'avg_score_Answer Relevancy',
       'std_score_Answer Relevancy', 'success_rate_Answer Relevancy',
       'metric_success_rate_Answer Relevancy',
       'avg_score_Contextual Relevancy', 'std_score_Contextual Relevancy',
       'success_rate_Contextual Relevancy',
       'metric_success_rate_Contextual Relevancy', 'avg_score_Hallucination',
       'std_score_Hallucination', 'success_rate_Hallucination',
       'metric_success_rate_Hallucination'],
      dtype='object')

In [30]:
grouped_df[
    [
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].to_dict()

{'search_type': {0: 'lexical_search_0_hop',
  1: 'lexical_search_1_hop',
  2: 'lexical_search_2_hop',
  3: 'similarity_search_0_hop',
  4: 'similarity_search_1_hop'},
 'avg_score_Answer Relevancy': {0: 0.8948278912618707,
  1: 0.9330500992756257,
  2: 1.0,
  3: 0.9131341496748164,
  4: 0.8694761017137859},
 'std_score_Answer Relevancy': {0: 0.2554129529599243,
  1: 0.16190257753746928,
  2: 0.0,
  3: 0.24710127652503208,
  4: 0.2891730837434111},
 'avg_score_Contextual Relevancy': {0: 0.7140498130805618,
  1: 0.7272914192619411,
  2: 0.0,
  3: 0.6733539232565638,
  4: 0.6680501810648602},
 'std_score_Contextual Relevancy': {0: 0.3169994868603728,
  1: 0.3087157781624958,
  2: nan,
  3: 0.3046191610085095,
  4: 0.2924115011550224},
 'avg_score_Hallucination': {0: 0.1865577889447236,
  1: 0.26373626373626374,
  2: 0.0,
  3: 0.15677609427609426,
  4: 0.31746031746031744},
 'std_score_Hallucination': {0: 0.38983075248492816,
  1: 0.44187358096021545,
  2: nan,
  3: 0.3621931637354864,
  4: 0.46386661779913557}}

In [31]:
df.groupby("test_name").count()

,consumer_id,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,success_Hallucination,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination,threshold_compliance_Answer Relevancy,threshold_compliance_Contextual Relevancy,threshold_compliance_Hallucination,question,model,search_type,hops
test_name,,,,,,,,,,,,,,,,,,,,
Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_0_hop,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Q1:DeepSeek-R1-Distill-Llama-70B-FP8:lexical_search_1_hop,5,5,4,5,5,4,5,5,4,5,5,4,5,5,5,5,5,5,5,5
Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity_search_0_hop,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Q1:DeepSeek-R1-Distill-Llama-70B-FP8:similarity_search_1_hop,5,5,4,5,5,4,5,5,4,5,5,4,5,5,5,5,5,5,5,5
Q1:anthropic.claude-v3-opus:lexical_search_0_hop,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q8:gpt-4o-2024-11-20:similarity_search_1_hop,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Q8:llama-3-70b-instruct-awq:lexical_search_0_hop,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Q8:llama-3-70b-instruct-awq:lexical_search_1_hop,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Q8:llama-3-70b-instruct-awq:similarity_search_0_hop,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Q8:llama-3-70b-instruct-awq:similarity_search_1_hop,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5

In [38]:
df[(df["consumer_id"].isin(["Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv", "Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro-preview-0409_deepeval.csv"])) & (df["test_name"] == "Q7:gemini-1.5-pro:similarity_search_0_hop")]

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,...,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination,threshold_compliance_Answer Relevancy,threshold_compliance_Contextual Relevancy,threshold_compliance_Hallucination,question,model,search_type,hops
262,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,Q7:gemini-1.5-pro:similarity_search_0_hop,True,True,True,1.0,0.777778,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q7,gemini-1.5-pro,similarity_search_0_hop,0
294,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,Q7:gemini-1.5-pro:similarity_search_0_hop,True,True,True,1.0,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q7,gemini-1.5-pro,similarity_search_0_hop,0

In [41]:
test = df[(df["consumer_id"].isin(["Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv", "Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro-preview-0409_deepeval.csv"])) & (df["test_name"] == "Q7:gemini-1.5-pro:similarity_search_0_hop")].to_dict()

{'consumer_id': {262: 'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro-preview-0409_deepeval.csv',
  294: 'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv'},
 'test_name': {262: 'Q7:gemini-1.5-pro:similarity_search_0_hop',
  294: 'Q7:gemini-1.5-pro:similarity_search_0_hop'},
 'metric_success_Answer Relevancy': {262: True, 294: True},
 'metric_success_Contextual Relevancy': {262: True, 294: True},
 'metric_success_Hallucination': {262: True, 294: True},
 'score_Answer Relevancy': {262: 1.0, 294: 1.0},
 'score_Contextual Relevancy': {262: 0.7777777777777778, 294: 1.0},
 'score_Hallucination': {262: 0.0, 294: 0.0},
 'success_Answer Relevancy': {262: True, 294: True},
 'success_Contextual Relevancy': {262: True, 294: True},
 'success_Hallucination': {262: True, 294: True},
 'threshold_Answer Relevancy': {262: 0.5, 294: 0.5},
 'threshold_Contextual Relevancy': {262: 0.5, 294: 0.5},
 'threshold_Hallucination': {262: 0.5, 294: 0.5},
 'threshold_compliance_Answer Relevancy': {262: True, 294: True},
 'threshold_compliance_Contextual Relevancy': {262: True, 294: True},
 'threshold_compliance_Hallucination': {262: False, 294: False},
 'question': {262: 'Q7', 294: 'Q7'},
 'model': {262: 'gemini-1.5-pro', 294: 'gemini-1.5-pro'},
 'search_type': {262: 'similarity_search_0_hop',
  294: 'similarity_search_0_hop'},
 'hops': {262: 0, 294: 0}}

In [44]:
teste = df[(df["consumer_id"].isin(["Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv", "Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro-preview-0409_deepeval.csv"])) & (df["test_name"] == "Q7:gemini-1.5-pro:similarity_search_0_hop")]

In [45]:
teste[["consumer_id", "score_Answer Relevancy", "score_Contextual Relevancy", "score_Hallucination"]]

,consumer_id,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination
262,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,1.0,0.777778,0.0
294,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,1.0,1.000000,0.0