# Analysis for the deepeval metrics

In [1]:
gold_source = (
    "/home/baptvit/Documents/github/graphrag-on-fhir/evaluations/data/gold/deepeval/"
)

In [2]:
import glob
import os

import pandas as pd

all_files = glob.glob(os.path.join(gold_source, "*.csv"))

all_dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df["consumer_id"] = file.split("/")[-1]
    all_dfs.append(df)


df_gold = pd.concat(all_dfs, ignore_index=True)

In [3]:
df_gold.columns

Index(['Unnamed: 0', 'test_name', 'success', 'metric_name', 'threshold',
       'metric_success', 'score', 'reason', 'strict_mode', 'evaluation_model',
       'error', 'evaluation_cost', 'verbose_logs', 'conversational',
       'multimodal', 'input', 'actual_output', 'expected_output', 'context',
       'retrieval_context', 'consumer_id'],
      dtype='object')

In [31]:
df_gold.head()

,Unnamed: 0,test_name,success,metric_name,threshold,metric_success,score,reason,strict_mode,evaluation_model,...,evaluation_cost,verbose_logs,conversational,multimodal,input,actual_output,expected_output,context,retrieval_context,consumer_id
0,0.0,Q6:gemini-1.5-pro:lexical_search_1_hop,True,Hallucination,0.5,True,0.0,The score is 0.00 because the actual output ac...,False,Gemini 1.5 Pro,...,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,Can you provide a breakdown of my medical bills ?,This is a summary of your medical bills:\n\n**...,NaN,"{'Main health record': 'Resource Type: Claim,\...","{'Main health record': 'Resource Type: Claim,\...",Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...
1,1.0,Q6:gemini-1.5-pro:lexical_search_1_hop,True,Answer Relevancy,0.5,True,1.0,"The score is 1.00 because, given the lack of c...",False,Gemini 1.5 Pro,...,NaN,"Statements:\n[\n ""This is a summary of your...",False,False,Can you provide a breakdown of my medical bills ?,This is a summary of your medical bills:\n\n**...,NaN,"{'Main health record': 'Resource Type: Claim,\...","{'Main health record': 'Resource Type: Claim,\...",Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...
2,2.0,Q6:gemini-1.5-pro:lexical_search_1_hop,True,Contextual Relevancy,0.5,True,1.0,The score is 1.00 because the retrieval contex...,False,Gemini 1.5 Pro,...,NaN,"Verdicts:\n[\n {\n ""verdicts"": [\n ...",False,False,Can you provide a breakdown of my medical bills ?,This is a summary of your medical bills:\n\n**...,NaN,"{'Main health record': 'Resource Type: Claim,\...","{'Main health record': 'Resource Type: Claim,\...",Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...
3,3.0,Q8:gemini-1.5-pro:lexical_search_1_hop,True,Hallucination,0.5,True,0.0,The score is 0.00 because the output correctly...,False,Gemini 1.5 Pro,...,NaN,"Verdicts:\n[\n {\n ""verdict"": ""yes"",...",False,False,Can you summarize my immunization history ?,Your immunization history shows that you recei...,NaN,{'Main health record': 'Resource Type: Immuniz...,{'Main health record': 'Resource Type: Immuniz...,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...
4,4.0,Q8:gemini-1.5-pro:lexical_search_1_hop,True,Answer Relevancy,0.5,True,1.0,The score is 1.00 because there were no irrele...,False,Gemini 1.5 Pro,...,NaN,"Statements:\n[\n ""Your immunization history...",False,False,Can you summarize my immunization history ?,Your immunization history shows that you recei...,NaN,{'Main health record': 'Resource Type: Immuniz...,{'Main health record': 'Resource Type: Immuniz...,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...

In [4]:
df_5 = df_gold[
    [
        "consumer_id",
        "test_name",
        "success",
        "metric_name",
        "threshold",
        "metric_success",
        "score",
        "reason",
    ]
].head()

In [5]:
df_5.to_dict()

{'consumer_id': {0: 'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv',
  1: 'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv',
  2: 'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv',
  3: 'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv',
  4: 'Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58-gemini-1.5-pro_deepeval.csv'},
 'test_name': {0: 'Q6:gemini-1.5-pro:lexical_search_1_hop',
  1: 'Q6:gemini-1.5-pro:lexical_search_1_hop',
  2: 'Q6:gemini-1.5-pro:lexical_search_1_hop',
  3: 'Q8:gemini-1.5-pro:lexical_search_1_hop',
  4: 'Q8:gemini-1.5-pro:lexical_search_1_hop'},
 'success': {0: True, 1: True, 2: True, 3: True, 4: True},
 'metric_name': {0: 'Hallucination',
  1: 'Answer Relevancy',
  2: 'Contextual Relevancy',
  3: 'Hallucination',
  4: 'Answer Relevancy'},
 'threshold': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'metric_success': {0: True, 1: True, 2: True, 3: True, 4: True},
 'score': {0: 0.0, 1: 1.0, 2: 1.0, 3: 0.0, 4: 1.0},
 'reason': {0: 'The score is 0.00 because the actual output accurately summarizes the key information from each medical bill, aligning perfectly with the provided contexts and containing no contradictions.',
  1: "The score is 1.00 because, given the lack of context/information, the response appropriately asks clarifying questions to better address the user's request to break down medical bills.  There were no irrelevant statements made, and the response stays focused and on-topic, which maintains the high score.",
  2: 'The score is 1.00 because the retrieval context contains statements directly related to medical claims and bills, which is exactly what the user is asking for. The context includes various claim details, such as claim IDs, dates, amounts, types, statuses, and descriptions of services. Perfect match!',
  3: 'The score is 0.00 because the output correctly summarizes the immunization records provided in the context, aligning with all factual information and presenting no contradictions.',
  4: "The score is 1.00 because there were no irrelevant statements made and the response was relevant and concise, addressing all parts of the user's prompt/question."}}

In [6]:
# Create DataFrame
df = df_gold

# Create the pivot table
pivot = pd.pivot_table(
    df,
    values=["success", "threshold", "metric_success", "score"],
    index=["consumer_id", "test_name"],
    columns=["metric_name"],
    aggfunc="first",  # Use 'first' to get the value as is since duplicates are unlikely
)

# Optional: Flatten the column multi-index for cleaner display
pivot.columns = ["_".join(col).strip() for col in pivot.columns.values]
pivot.reset_index(inplace=True)

# Display the pivot table
pivot

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,success_Hallucination,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:lexical_search_0_hop,False,True,True,0.000000,0.500000,0.0,False,False,False,0.5,0.5,0.5
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:lexical_search_1_hop,True,False,False,0.964286,0.400000,1.0,False,False,False,0.5,0.5,0.5
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:similarity_search_...,True,False,False,1.000000,0.333333,1.0,False,False,False,0.5,0.5,0.5
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:similarity_search_...,True,False,False,0.931034,0.333333,1.0,False,False,False,0.5,0.5,0.5
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:anthropic.claude-v3-opus:lexical_search_0_hop,True,True,True,0.960000,0.714286,0.0,True,True,True,0.5,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:gpt-4o-2024-08-06:similarity_search_1_hop,True,True,False,0.781250,0.700000,1.0,False,False,False,0.5,0.5,0.5
476,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
477,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:lexical_search_1_hop,True,True,True,0.961538,0.933333,0.0,True,True,True,0.5,0.5,0.5
478,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:similarity_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,True,0.5,0.5,0.5
479,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:similarity_search_1_hop,True,True,True,0.714286,0.875000,0.0,True,True,True,0.5,0.5,0.5

In [7]:
pivot.to_csv(
    "/home/baptvit/Documents/mestrado/master-experiments/evaluations/data/gold/Beatris270_Bogan287_5b3645de-a2d0-d016-0839-bab3757c4c58_deepeval_results.csv"
)

In [8]:
pivot.head().to_dict()

{'consumer_id': {0: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-anthropic.claude-v3-opus_deepeval.csv',
  1: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-anthropic.claude-v3-opus_deepeval.csv',
  2: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-anthropic.claude-v3-opus_deepeval.csv',
  3: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-anthropic.claude-v3-opus_deepeval.csv',
  4: 'Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff119c625-anthropic.claude-v3-opus_deepeval.csv'},
 'test_name': {0: 'Q1:anthropic.claude-v3-opus:lexical_search_0_hop',
  1: 'Q1:anthropic.claude-v3-opus:lexical_search_1_hop',
  2: 'Q1:anthropic.claude-v3-opus:similarity_search_0_hop',
  3: 'Q1:anthropic.claude-v3-opus:similarity_search_1_hop',
  4: 'Q2:anthropic.claude-v3-opus:lexical_search_0_hop'},
 'metric_success_Answer Relevancy': {0: False,
  1: True,
  2: True,
  3: True,
  4: True},
 'metric_success_Contextual Relevancy': {0: True,
  1: False,
  2: False,
  3: False,
  4: True},
 'metric_success_Hallucination': {0: True,
  1: False,
  2: False,
  3: False,
  4: True},
 'score_Answer Relevancy': {0: 0.0,
  1: 0.9642857142857144,
  2: 1.0,
  3: 0.9310344827586208,
  4: 0.96},
 'score_Contextual Relevancy': {0: 0.5,
  1: 0.4,
  2: 0.3333333333333333,
  3: 0.3333333333333333,
  4: 0.7142857142857143},
 'score_Hallucination': {0: 0.0, 1: 1.0, 2: 1.0, 3: 1.0, 4: 0.0},
 'success_Answer Relevancy': {0: False, 1: False, 2: False, 3: False, 4: True},
 'success_Contextual Relevancy': {0: False,
  1: False,
  2: False,
  3: False,
  4: True},
 'success_Hallucination': {0: False, 1: False, 2: False, 3: False, 4: True},
 'threshold_Answer Relevancy': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'threshold_Contextual Relevancy': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5},
 'threshold_Hallucination': {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5}}

In [9]:
df = pivot
# Analysis 1: Overall success rates by metric
success_rates = (
    df[
        [
            "metric_success_Answer Relevancy",
            "metric_success_Contextual Relevancy",
            "metric_success_Hallucination",
        ]
    ].mean()
    * 100
)

print("Overall Success Rates by Metric (%):")
print(success_rates)

# Analysis 2: Average scores by metric
average_scores = df[
    ["score_Answer Relevancy", "score_Contextual Relevancy", "score_Hallucination"]
].mean()

print("\nAverage Scores by Metric:")
print(average_scores)


# Analysis 3: Threshold compliance (scores >= threshold)
def threshold_compliance(row, metric):
    return row[f"score_{metric}"] >= row[f"threshold_{metric}"]


for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
    df[f"threshold_compliance_{metric}"] = df.apply(
        threshold_compliance, axis=1, metric=metric
    )

threshold_compliance_rates = (
    df[
        [
            "threshold_compliance_Answer Relevancy",
            "threshold_compliance_Contextual Relevancy",
            "threshold_compliance_Hallucination",
        ]
    ].mean()
    * 100
)

print("\nThreshold Compliance Rates by Metric (%):")
print(threshold_compliance_rates)

# Analysis 4: Breakdown by test_name
breakdown = df.groupby(["consumer_id", "test_name"]).mean()

print("\nBreakdown by Test Name:")
print(breakdown)

Overall Success Rates by Metric (%):
metric_success_Answer Relevancy        88.958333
metric_success_Contextual Relevancy    73.333333
metric_success_Hallucination           71.875000
dtype: float64

Average Scores by Metric:
score_Answer Relevancy        0.922396
score_Contextual Relevancy    0.729277
score_Hallucination           0.192330
dtype: float64

Threshold Compliance Rates by Metric (%):
threshold_compliance_Answer Relevancy        88.958333
threshold_compliance_Contextual Relevancy    73.333333
threshold_compliance_Hallucination           17.083333
dtype: float64

Breakdown by Test Name:
                                                                                                       metric_success_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                                0.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                                1.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                              1.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                              1.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                                1.0
...                                                                                                                                ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                                    1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                       1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                       1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                                    1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                                    1.0

                                                                                                       metric_success_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                                    1.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                                    0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                                  0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                                  0.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                                    1.0
...                                                                                                                                    ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                                        1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                           1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                           1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                                        1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                                        1.0

                                                                                                       metric_success_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                             1.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                             0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                           0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                           0.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                             1.0
...                                                                                                                             ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                                 0.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                    1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                    1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                                 1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                                 1.0

                                                                                                       score_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                  0.000000
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                  0.964286
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                1.000000
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                0.931034
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                  0.960000
...                                                                                                                       ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                      0.781250
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                         1.000000
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                         0.961538
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                      1.000000
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                      0.714286

                                                                                                       score_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                      0.500000
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                      0.400000
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                    0.333333
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                    0.333333
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                      0.714286
...                                                                                                                           ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                          0.700000
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                             1.000000
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                             0.933333
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                          1.000000
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                          0.875000

                                                                                                       score_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                    0.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                    1.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                  1.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                  1.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                    0.0
...                                                                                                                    ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                        1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                           0.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                           0.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                        0.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                        0.0

                                                                                                       success_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                         0.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                         0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                       0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                       0.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                         1.0
...                                                                                                                         ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                             0.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                             1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                             1.0

                                                                                                       success_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                             0.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                             0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                           0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                           0.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                             1.0
...                                                                                                                             ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                                 0.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                    1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                    1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                                 1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                                 1.0

                                                                                                       success_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                      0.0
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                      0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                    0.0
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                    0.0
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                      1.0
...                                                                                                                      ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                          0.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                             1.0
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                             1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                          1.0
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                          1.0

                                                                                                       threshold_Answer Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                           0.5
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                           0.5
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                         0.5
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                         0.5
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                           0.5
...                                                                                                                           ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                               0.5
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                  0.5
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                  0.5
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                               0.5
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                               0.5

                                                                                                       threshold_Contextual Relevancy  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                               0.5
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                               0.5
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                             0.5
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                             0.5
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                               0.5
...                                                                                                                               ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                                   0.5
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                                      0.5
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                                      0.5
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                                   0.5
                                                   Q8:gpt-4o-2024-08-06:similarity_search_1_hop                                   0.5

                                                                                                       threshold_Hallucination  \
consumer_id                                        test_name
Allen322_Ferry570_ad134528-56a5-35fd-c37f-466ff... Q1:anthropic.claude-v3-opus:lexical_search_0_hop                        0.5
                                                   Q1:anthropic.claude-v3-opus:lexical_search_1_hop                        0.5
                                                   Q1:anthropic.claude-v3-opus:similarity_search_0...                      0.5
                                                   Q1:anthropic.claude-v3-opus:similarity_search_1...                      0.5
                                                   Q2:anthropic.claude-v3-opus:lexical_search_0_hop                        0.5
...                                                                                                                        ...
Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-8568... Q7:gpt-4o-2024-08-06:similarity_search_1_hop                            0.5
                                                   Q8:gpt-4o-2024-08-06:lexical_search_0_hop                               0.5
                                                   Q8:gpt-4o-2024-08-06:lexical_search_1_hop                               0.5
                                                   Q8:gpt-4o-2024-08-06:similarity_search_0_hop                            0.5

In [10]:
df = pivot

df[["question", "model", "search_type"]] = df["test_name"].str.split(":", expand=True)

In [11]:
df["hops"] = df["test_name"].str[-5:]

In [12]:
df["hops"] = df["hops"].str.replace("_hop", "", regex=False).astype(int)

In [13]:
df = df.replace("anthropic.claude-v3-5-sonnet-v2", "anthropic.claude-v3-opus")
df = df.replace("gpt-4o-2024-11-20", "gpt-4o-2024-08-06")

In [14]:
df

,consumer_id,test_name,metric_success_Answer Relevancy,metric_success_Contextual Relevancy,metric_success_Hallucination,score_Answer Relevancy,score_Contextual Relevancy,score_Hallucination,success_Answer Relevancy,success_Contextual Relevancy,...,threshold_Answer Relevancy,threshold_Contextual Relevancy,threshold_Hallucination,threshold_compliance_Answer Relevancy,threshold_compliance_Contextual Relevancy,threshold_compliance_Hallucination,question,model,search_type,hops
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:lexical_search_0_hop,False,True,True,0.000000,0.500000,0.0,False,False,...,0.5,0.5,0.5,False,True,False,Q1,anthropic.claude-v3-opus,lexical_search_0_hop,0
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:lexical_search_1_hop,True,False,False,0.964286,0.400000,1.0,False,False,...,0.5,0.5,0.5,True,False,True,Q1,anthropic.claude-v3-opus,lexical_search_1_hop,1
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:similarity_search_...,True,False,False,1.000000,0.333333,1.0,False,False,...,0.5,0.5,0.5,True,False,True,Q1,anthropic.claude-v3-opus,similarity_search_0_hop,0
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1:anthropic.claude-v3-opus:similarity_search_...,True,False,False,0.931034,0.333333,1.0,False,False,...,0.5,0.5,0.5,True,False,True,Q1,anthropic.claude-v3-opus,similarity_search_1_hop,1
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2:anthropic.claude-v3-opus:lexical_search_0_hop,True,True,True,0.960000,0.714286,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q2,anthropic.claude-v3-opus,lexical_search_0_hop,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7:gpt-4o-2024-08-06:similarity_search_1_hop,True,True,False,0.781250,0.700000,1.0,False,False,...,0.5,0.5,0.5,True,True,True,Q7,gpt-4o-2024-08-06,similarity_search_1_hop,1
476,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:lexical_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,gpt-4o-2024-08-06,lexical_search_0_hop,0
477,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:lexical_search_1_hop,True,True,True,0.961538,0.933333,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,gpt-4o-2024-08-06,lexical_search_1_hop,1
478,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:similarity_search_0_hop,True,True,True,1.000000,1.000000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,gpt-4o-2024-08-06,similarity_search_0_hop,0
479,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8:gpt-4o-2024-08-06:similarity_search_1_hop,True,True,True,0.714286,0.875000,0.0,True,True,...,0.5,0.5,0.5,True,True,False,Q8,gpt-4o-2024-08-06,similarity_search_1_hop,1

In [15]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = (
    df.groupby(["consumer_id", "question", "search_type", "hops"])
    .apply(analyze_metrics)
    .reset_index()
)
grouped_df

/tmp/ipykernel_104608/833737725.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(analyze_metrics)

,consumer_id,question,search_type,hops,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,lexical_search_0_hop,0,0.000000,0.0,0.0,0.500000,0.0,1.0,0.0,0.0,1.0
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,lexical_search_1_hop,1,0.964286,0.0,1.0,0.400000,0.0,0.0,1.0,0.0,0.0
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,similarity_search_0_hop,0,1.000000,0.0,1.0,0.333333,0.0,0.0,1.0,0.0,0.0
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q1,similarity_search_1_hop,1,0.931034,0.0,1.0,0.333333,0.0,0.0,1.0,0.0,0.0
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,Q2,lexical_search_0_hop,0,0.960000,1.0,1.0,0.714286,1.0,1.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q7,similarity_search_1_hop,1,0.781250,0.0,1.0,0.700000,0.0,1.0,1.0,0.0,0.0
476,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,lexical_search_0_hop,0,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
477,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,lexical_search_1_hop,1,0.961538,1.0,1.0,0.933333,1.0,1.0,0.0,1.0,1.0
478,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,similarity_search_0_hop,0,1.000000,1.0,1.0,1.000000,1.0,1.0,0.0,1.0,1.0
479,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,Q8,similarity_search_1_hop,1,0.714286,1.0,1.0,0.875000,1.0,1.0,0.0,1.0,1.0

In [16]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = (
    df.groupby(["consumer_id", "search_type"]).apply(analyze_metrics).reset_index()
)
grouped_df

/tmp/ipykernel_104608/1437396366.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(["consumer_id", "search_type"]).apply(analyze_metrics).reset_index()

,consumer_id,search_type,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_0_hop,0.771987,0.625,0.875,0.681324,0.625,0.875,0.125000,0.625,0.875
1,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_1_hop,0.973637,0.125,1.000,0.773810,0.125,0.750,0.857143,0.125,0.125
2,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_0_hop,0.986392,0.500,1.000,0.678175,0.500,0.875,0.500000,0.500,0.500
3,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_1_hop,0.852109,0.250,0.875,0.663889,0.250,0.875,0.750000,0.250,0.250
4,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_0_hop,1.000000,0.750,1.000,0.712897,0.750,0.750,0.000000,0.750,1.000
5,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_1_hop,1.000000,0.875,1.000,0.822674,0.875,0.875,0.000000,0.875,1.000
6,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_0_hop,0.995787,1.000,1.000,0.995748,1.000,1.000,0.000000,1.000,1.000
7,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_1_hop,1.000000,1.000,1.000,1.000000,1.000,1.000,0.000000,1.000,1.000
8,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_0_hop,0.921972,0.875,1.000,0.711837,0.875,0.875,0.140625,0.875,0.875
9,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,lexical_search_1_hop,0.939804,0.500,1.000,0.737408,0.500,0.625,0.166667,0.500,0.625
10,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_0_hop,0.932692,0.250,0.500,0.690476,0.250,0.375,0.250000,0.250,0.375
11,Allen322_Ferry570_ad134528-56a5-35fd-c37f-466f...,similarity_search_1_hop,0.841071,0.375,0.875,0.674576,0.375,0.875,0.625000,0.375,0.375
12,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_0_hop,0.792707,0.750,0.875,0.747069,0.750,1.000,0.250000,0.750,0.750
13,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_1_hop,0.912143,0.875,1.000,0.744731,0.875,1.000,0.125000,0.875,0.875
14,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_0_hop,0.889891,0.875,1.000,0.654167,0.875,0.875,0.000000,0.875,1.000
15,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_1_hop,0.773897,0.875,0.875,0.799206,0.875,1.000,0.000000,0.875,1.000
16,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_0_hop,0.977273,1.000,1.000,1.000000,1.000,1.000,0.000000,1.000,1.000
17,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_1_hop,1.000000,1.000,1.000,1.000000,1.000,1.000,0.000000,1.000,1.000
18,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_0_hop,1.000000,1.000,1.000,0.992647,1.000,1.000,0.000000,1.000,1.000
19,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_1_hop,0.806066,0.875,0.875,0.992647,0.875,1.000,0.000000,0.875,1.000
20,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_0_hop,0.914583,0.875,0.875,0.906944,0.875,1.000,0.000000,0.875,1.000
21,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,lexical_search_1_hop,0.869744,0.625,0.875,0.752232,0.625,0.875,0.250000,0.625,0.750
22,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_0_hop,0.773659,0.500,0.750,0.470062,0.500,0.625,0.000000,0.500,1.000
23,Beatris270_Bogan287_5b3645de-a2d0-d016-0839-ba...,similarity_search_1_hop,0.912768,0.500,0.875,0.665307,0.500,0.875,0.285714,0.500,0.625
24,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_0_hop,0.819048,0.500,0.875,0.558333,0.500,0.625,0.250000,0.500,0.750
25,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_1_hop,0.934402,0.500,1.000,0.708532,0.500,0.875,0.375000,0.500,0.625
26,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_0_hop,0.864120,0.625,0.875,0.604911,0.625,0.875,0.250000,0.625,0.750
27,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_1_hop,0.817632,0.375,0.875,0.662392,0.375,0.875,0.500000,0.375,0.500
28,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_0_hop,0.961957,0.875,1.000,0.845588,0.875,0.875,0.000000,0.875,1.000
29,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_1_hop,0.997283,0.625,1.000,0.776786,0.625,0.750,0.125000,0.625,0.875
30,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_0_hop,0.979167,0.750,1.000,0.770115,0.750,0.750,0.000000,0.750,1.000
31,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_1_hop,0.973611,0.625,1.000,0.663690,0.625,0.625,0.125000,0.625,0.875
32,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_0_hop,1.000000,0.500,1.000,0.562500,0.500,0.750,0.250000,0.500,0.750
33,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,lexical_search_1_hop,0.978571,0.375,1.000,0.760169,0.375,0.875,0.500000,0.375,0.500
34,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_0_hop,0.973214,0.625,1.000,0.599702,0.625,0.750,0.125000,0.625,0.875
35,Edythe31_Morar593_9c3df38a-d3b7-2198-3898-51f9...,similarity_search_1_hop,0.989358,0.625,1.000,0.700000,0.625,0.875,0.250000,0.625,0.750
36,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_0_hop,0.955249,0.625,1.000,0.569792,0.625,0.750,0.250000,0.625,0.750
37,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_1_hop,0.956971,0.125,1.000,0.645833,0.125,0.375,0.500000,0.125,0.250
38,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_0_hop,0.856908,0.250,0.875,0.605975,0.250,0.750,0.500000,0.250,0.500
39,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_1_hop,0.875000,0.250,0.875,0.672123,0.250,0.625,0.500000,0.250,0.375
40,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_0_hop,1.000000,0.875,1.000,0.875000,0.875,0.875,0.000000,0.875,1.000
41,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_1_hop,0.949145,0.500,1.000,0.746377,0.500,0.500,0.000000,0.500,1.000
42,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_0_hop,1.000000,1.000,1.000,0.937500,1.000,1.000,0.000000,1.000,1.000
43,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_1_hop,0.940448,0.750,1.000,0.845307,0.750,0.875,0.250000,0.750,0.750
44,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_0_hop,0.943421,0.500,1.000,0.644841,0.500,0.625,0.142857,0.500,0.750
45,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,lexical_search_1_hop,0.949811,0.250,1.000,0.575758,0.250,0.250,0.250000,0.250,0.375
46,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_0_hop,0.985119,0.375,1.000,0.521357,0.375,0.500,0.285714,0.375,0.625
47,Jacklyn830_Veum823_e0e1f21a-22a7-d166-7bb1-63f...,similarity_search_1_hop,0.853532,0.125,0.875,0.404611,0.125,0.250,0.200000,0.125,0.500
48,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_0_hop,NaN,0.000,0.000,NaN,0.000,0.000,NaN,0.000,0.000
49,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_1_hop,0.956481,0.000,0.250,0.801587,0.000,0.375,1.000000,0.000,0.000
50,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_0_hop,1.000000,0.000,0.125,NaN,0.000,0.000,0.000000,0.000,0.125
51,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_1_hop,1.000000,0.000,0.125,0.727273,0.000,0.125,0.000000,0.000,0.250
52,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_0_hop,0.997191,0.875,1.000,0.875000,0.875,0.875,0.000000,0.875,1.000
53,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_1_hop,1.000000,0.875,1.000,0.833703,0.875,0.875,0.000000,0.875,1.000
54,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_0_hop,0.996324,0.625,1.000,0.603808,0.625,0.625,0.000000,0.625,1.000
55,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_1_hop,0.998077,0.750,1.000,0.667724,0.750,0.750,0.000000,0.750,1.000
56,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_0_hop,0.702714,0.375,0.750,0.553686,0.375,0.625,0.250000,0.375,0.750
57,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,lexical_search_1_hop,0.890930,0.250,1.000,0.525000,0.250,0.500,0.500000,0.250,0.375
58,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_0_hop,0.861842,0.750,0.875,0.662504,0.750,0.750,0.125000,0.750,0.875
59,Milton509_Ortiz186_d66b5418-06cb-fc8a-8c13-856...,similarity_search_1_hop,0.792205,0.375,0.875,0.569384,0.375,0.625,0.285714,0.375,0.625

In [17]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_104608/3565463073.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()

,search_type,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,lexical_search_0_hop,0.911293,0.666667,0.883333,0.732555,0.666667,0.766667,0.118243,0.666667,0.816667
1,lexical_search_1_hop,0.953794,0.500000,0.941667,0.761367,0.500000,0.700000,0.257426,0.500000,0.625000
2,similarity_search_0_hop,0.936056,0.608333,0.866667,0.701065,0.608333,0.716667,0.138889,0.608333,0.775000
3,similarity_search_1_hop,0.888550,0.516667,0.866667,0.724352,0.516667,0.750000,0.261682,0.516667,0.658333

In [18]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["question"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_104608/1271303342.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["question"]).apply(analyze_metrics).reset_index()

,question,avg_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,Q1,0.845893,0.466667,0.833333,0.665269,0.466667,0.650000,0.245614,0.466667,0.716667
1,Q2,0.818040,0.400000,0.783333,0.394498,0.400000,0.416667,0.071429,0.400000,0.866667
2,Q3,0.906605,0.500000,0.900000,0.704227,0.500000,0.733333,0.233173,0.500000,0.666667
3,Q4,0.953109,0.500000,0.900000,0.725829,0.500000,0.716667,0.285714,0.500000,0.583333
4,Q5,0.988971,0.666667,0.933333,0.787787,0.666667,0.766667,0.129630,0.666667,0.783333
5,Q6,0.988343,0.500000,0.933333,0.796316,0.500000,0.800000,0.360000,0.500000,0.533333
6,Q7,0.921870,0.700000,0.916667,0.878770,0.700000,0.866667,0.166667,0.700000,0.750000
7,Q8,0.957537,0.850000,0.916667,0.902326,0.850000,0.916667,0.072727,0.850000,0.850000

In [19]:
df.columns

Index(['consumer_id', 'test_name', 'metric_success_Answer Relevancy',
       'metric_success_Contextual Relevancy', 'metric_success_Hallucination',
       'score_Answer Relevancy', 'score_Contextual Relevancy',
       'score_Hallucination', 'success_Answer Relevancy',
       'success_Contextual Relevancy', 'success_Hallucination',
       'threshold_Answer Relevancy', 'threshold_Contextual Relevancy',
       'threshold_Hallucination', 'threshold_compliance_Answer Relevancy',
       'threshold_compliance_Contextual Relevancy',
       'threshold_compliance_Hallucination', 'question', 'model',
       'search_type', 'hops'],
      dtype='object')

In [24]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["model", "search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_104608/913412050.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["model", "search_type"]).apply(analyze_metrics).reset_index()

,model,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,anthropic.claude-v3-opus,lexical_search_0_hop,0.834748,0.293249,0.500,0.725,0.639130,0.243989,0.500,0.650,0.218750,0.420013,0.500,0.625
1,anthropic.claude-v3-opus,lexical_search_1_hop,0.945005,0.061450,0.325,0.850,0.734362,0.259468,0.325,0.675,0.482759,0.508548,0.325,0.375
2,anthropic.claude-v3-opus,similarity_search_0_hop,0.902379,0.238481,0.450,0.775,0.635807,0.225213,0.450,0.675,0.303030,0.466694,0.450,0.575
3,anthropic.claude-v3-opus,similarity_search_1_hop,0.834821,0.325354,0.350,0.725,0.702062,0.236349,0.350,0.700,0.406250,0.498991,0.350,0.475
4,gemini-1.5-pro,lexical_search_0_hop,0.987284,0.055406,0.875,1.000,0.861697,0.330413,0.875,0.875,0.000000,0.000000,0.875,1.000
5,gemini-1.5-pro,lexical_search_1_hop,0.989285,0.055153,0.775,1.000,0.840620,0.336954,0.775,0.800,0.025000,0.158114,0.775,0.975
6,gemini-1.5-pro,similarity_search_0_hop,0.994255,0.027013,0.875,1.000,0.859964,0.306490,0.875,0.875,0.000000,0.000000,0.875,1.000
7,gemini-1.5-pro,similarity_search_1_hop,0.943641,0.176364,0.800,0.975,0.833874,0.319440,0.800,0.850,0.075000,0.266747,0.800,0.925
8,gpt-4o-2024-08-06,lexical_search_0_hop,0.896538,0.253433,0.625,0.925,0.676760,0.305238,0.625,0.775,0.157051,0.364680,0.625,0.825
9,gpt-4o-2024-08-06,lexical_search_1_hop,0.925772,0.147838,0.400,0.975,0.690353,0.304475,0.400,0.625,0.343750,0.482559,0.400,0.525
10,gpt-4o-2024-08-06,similarity_search_0_hop,0.902262,0.238283,0.500,0.825,0.579130,0.307893,0.500,0.600,0.142857,0.355036,0.500,0.750
11,gpt-4o-2024-08-06,similarity_search_1_hop,0.877787,0.276411,0.400,0.900,0.618929,0.276919,0.400,0.700,0.342857,0.481594,0.400,0.575

In [27]:
grouped_df[
    [
        "model",
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].to_dict()

{'model': {0: 'anthropic.claude-v3-opus',
  1: 'anthropic.claude-v3-opus',
  2: 'anthropic.claude-v3-opus',
  3: 'anthropic.claude-v3-opus',
  4: 'gemini-1.5-pro',
  5: 'gemini-1.5-pro',
  6: 'gemini-1.5-pro',
  7: 'gemini-1.5-pro',
  8: 'gpt-4o-2024-08-06',
  9: 'gpt-4o-2024-08-06',
  10: 'gpt-4o-2024-08-06',
  11: 'gpt-4o-2024-08-06'},
 'search_type': {0: 'lexical_search_0_hop',
  1: 'lexical_search_1_hop',
  2: 'similarity_search_0_hop',
  3: 'similarity_search_1_hop',
  4: 'lexical_search_0_hop',
  5: 'lexical_search_1_hop',
  6: 'similarity_search_0_hop',
  7: 'similarity_search_1_hop',
  8: 'lexical_search_0_hop',
  9: 'lexical_search_1_hop',
  10: 'similarity_search_0_hop',
  11: 'similarity_search_1_hop'},
 'avg_score_Answer Relevancy': {0: 0.8347475721610482,
  1: 0.9450052360353716,
  2: 0.9023786018133044,
  3: 0.8348212656654349,
  4: 0.9872840520495625,
  5: 0.9892854444870588,
  6: 0.9942553425864729,
  7: 0.9436405404629185,
  8: 0.8965380502887654,
  9: 0.9257719297042266,
  10: 0.9022624472738888,
  11: 0.8777867655630665},
 'std_score_Answer Relevancy': {0: 0.29324870194553926,
  1: 0.06145006359545406,
  2: 0.23848137294508237,
  3: 0.3253535646158535,
  4: 0.05540587396807781,
  5: 0.05515305248281869,
  6: 0.02701329506627158,
  7: 0.17636415603586583,
  8: 0.25343283073283834,
  9: 0.14783812653542927,
  10: 0.2382825435478025,
  11: 0.2764109287300937},
 'avg_score_Contextual Relevancy': {0: 0.639129577020202,
  1: 0.7343620268620268,
  2: 0.6358068147130648,
  3: 0.7020615137550621,
  4: 0.8616970121381886,
  5: 0.840620131383029,
  6: 0.8599636081993175,
  7: 0.8338737907085161,
  8: 0.6767597075289382,
  9: 0.6903525685783751,
  10: 0.5791301945061343,
  11: 0.6189286299724159},
 'std_score_Contextual Relevancy': {0: 0.2439894325729546,
  1: 0.25946828996352156,
  2: 0.22521250868897127,
  3: 0.23634933875689074,
  4: 0.33041252612162114,
  5: 0.33695388599502857,
  6: 0.30649008133202443,
  7: 0.3194402981738698,
  8: 0.3052381615515825,
  9: 0.30447517065850166,
  10: 0.30789293226286224,
  11: 0.2769187522375345},
 'avg_score_Hallucination': {0: 0.21875,
  1: 0.4827586206896552,
  2: 0.30303030303030304,
  3: 0.40625,
  4: 0.0,
  5: 0.025,
  6: 0.0,
  7: 0.075,
  8: 0.15705128205128205,
  9: 0.34375,
  10: 0.14285714285714285,
  11: 0.34285714285714286},
 'std_score_Hallucination': {0: 0.42001344064515445,
  1: 0.5085476277156078,
  2: 0.46669372215943755,
  3: 0.49899091723584604,
  4: 0.0,
  5: 0.15811388300841897,
  6: 0.0,
  7: 0.2667467828369185,
  8: 0.36468031773465637,
  9: 0.48255870443481425,
  10: 0.3550358012483632,
  11: 0.4815939919779354}}

In [29]:
markdown_table = """| Model                   | Search Type               | Avg Score Answer Relevancy (%) | Std Score Answer Relevancy (%) | Avg Score Contextual Relevancy (%) | Std Score Contextual Relevancy (%) | Avg Score Hallucination (%) | Std Score Hallucination (%) |
|-------------------------|---------------------------|--------------------------------|--------------------------------|------------------------------------|------------------------------------|-----------------------------|-----------------------------|
| anthropic.claude-v3-opus | lexical_search_0_hop      | 83.47                          | 29.32                          | 63.91                              | 24.40                              | 21.88                       | 42.00                       |
| anthropic.claude-v3-opus | lexical_search_1_hop      | 94.50                          | 6.15                           | 73.44                              | 25.95                              | 48.28                       | 50.85                       |
| anthropic.claude-v3-opus | similarity_search_0_hop   | 90.24                          | 23.85                          | 63.58                              | 22.52                              | 30.30                       | 46.67                       |
| anthropic.claude-v3-opus | similarity_search_1_hop   | 83.48                          | 32.54                          | 70.21                              | 23.63                              | 40.63                       | 49.90                       |
| gemini-1.5-pro           | lexical_search_0_hop      | 98.73                          | 5.54                           | 86.17                              | 33.04                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | lexical_search_1_hop      | 98.93                          | 5.52                           | 84.06                              | 33.70                              | 2.50                        | 15.81                       |
| gemini-1.5-pro           | similarity_search_0_hop   | 99.43                          | 2.70                           | 86.00                              | 30.65                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | similarity_search_1_hop   | 94.36                          | 17.64                          | 83.39                              | 31.94                              | 7.50                        | 26.67                       |
| gpt-4o-2024-08-06        | lexical_search_0_hop      | 89.65                          | 25.34                          | 67.68                              | 30.52                              | 15.71                       | 36.47                       |
| gpt-4o-2024-08-06        | lexical_search_1_hop      | 92.58                          | 14.78                          | 69.04                              | 30.45                              | 34.38                       | 48.26                       |
| gpt-4o-2024-08-06        | similarity_search_0_hop   | 90.23                          | 23.83                          | 57.91                              | 30.79                              | 14.29                       | 35.50                       |
| gpt-4o-2024-08-06        | similarity_search_1_hop   | 87.78                          | 27.64                          | 61.89                              | 27.69                              | 34.29                       | 48.16                       |"""

In [30]:
from IPython.display import display, Markdown

display(Markdown(markdown_table))

| Model                   | Search Type               | Avg Score Answer Relevancy (%) | Std Score Answer Relevancy (%) | Avg Score Contextual Relevancy (%) | Std Score Contextual Relevancy (%) | Avg Score Hallucination (%) | Std Score Hallucination (%) |
|-------------------------|---------------------------|--------------------------------|--------------------------------|------------------------------------|------------------------------------|-----------------------------|-----------------------------|
| anthropic.claude-v3-opus | lexical_search_0_hop      | 83.47                          | 29.32                          | 63.91                              | 24.40                              | 21.88                       | 42.00                       |
| anthropic.claude-v3-opus | lexical_search_1_hop      | 94.50                          | 6.15                           | 73.44                              | 25.95                              | 48.28                       | 50.85                       |
| anthropic.claude-v3-opus | similarity_search_0_hop   | 90.24                          | 23.85                          | 63.58                              | 22.52                              | 30.30                       | 46.67                       |
| anthropic.claude-v3-opus | similarity_search_1_hop   | 83.48                          | 32.54                          | 70.21                              | 23.63                              | 40.63                       | 49.90                       |
| gemini-1.5-pro           | lexical_search_0_hop      | 98.73                          | 5.54                           | 86.17                              | 33.04                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | lexical_search_1_hop      | 98.93                          | 5.52                           | 84.06                              | 33.70                              | 2.50                        | 15.81                       |
| gemini-1.5-pro           | similarity_search_0_hop   | 99.43                          | 2.70                           | 86.00                              | 30.65                              | 0.00                        | 0.00                        |
| gemini-1.5-pro           | similarity_search_1_hop   | 94.36                          | 17.64                          | 83.39                              | 31.94                              | 7.50                        | 26.67                       |
| gpt-4o-2024-08-06        | lexical_search_0_hop      | 89.65                          | 25.34                          | 67.68                              | 30.52                              | 15.71                       | 36.47                       |
| gpt-4o-2024-08-06        | lexical_search_1_hop      | 92.58                          | 14.78                          | 69.04                              | 30.45                              | 34.38                       | 48.26                       |
| gpt-4o-2024-08-06        | similarity_search_0_hop   | 90.23                          | 23.83                          | 57.91                              | 30.79                              | 14.29                       | 35.50                       |
| gpt-4o-2024-08-06        | similarity_search_1_hop   | 87.78                          | 27.64                          | 61.89                              | 27.69                              | 34.29                       | 48.16                       |

In [21]:
# 2. Aggregation and Grouping: Analyze by search type and hops
def analyze_metrics(df_group):
    results = {}
    for metric in ["Answer Relevancy", "Contextual Relevancy", "Hallucination"]:
        results[f"avg_score_{metric}"] = df_group[f"score_{metric}"].mean()
        results[f"std_score_{metric}"] = df_group[f"score_{metric}"].std()
        results[f"success_rate_{metric}"] = df_group[
            f"success_{metric}"
        ].mean()  # calculates the percentage of True values
        results[f"metric_success_rate_{metric}"] = df_group[
            f"metric_success_{metric}"
        ].mean()
    return pd.Series(results)


grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()
grouped_df

/tmp/ipykernel_104608/1164691038.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby(["search_type"]).apply(analyze_metrics).reset_index()

,search_type,avg_score_Answer Relevancy,std_score_Answer Relevancy,success_rate_Answer Relevancy,metric_success_rate_Answer Relevancy,avg_score_Contextual Relevancy,std_score_Contextual Relevancy,success_rate_Contextual Relevancy,metric_success_rate_Contextual Relevancy,avg_score_Hallucination,std_score_Hallucination,success_rate_Hallucination,metric_success_rate_Hallucination
0,lexical_search_0_hop,0.911293,0.226959,0.666667,0.883333,0.732555,0.312053,0.666667,0.766667,0.118243,0.322824,0.666667,0.816667
1,lexical_search_1_hop,0.953794,0.102191,0.500000,0.941667,0.761367,0.308904,0.500000,0.700000,0.257426,0.439397,0.500000,0.625000
2,similarity_search_0_hop,0.936056,0.193642,0.608333,0.866667,0.701065,0.309070,0.608333,0.716667,0.138889,0.347443,0.608333,0.775000
3,similarity_search_1_hop,0.888550,0.263924,0.516667,0.866667,0.724352,0.295150,0.516667,0.750000,0.261682,0.441619,0.516667,0.658333

In [22]:
grouped_df.columns

Index(['search_type', 'avg_score_Answer Relevancy',
       'std_score_Answer Relevancy', 'success_rate_Answer Relevancy',
       'metric_success_rate_Answer Relevancy',
       'avg_score_Contextual Relevancy', 'std_score_Contextual Relevancy',
       'success_rate_Contextual Relevancy',
       'metric_success_rate_Contextual Relevancy', 'avg_score_Hallucination',
       'std_score_Hallucination', 'success_rate_Hallucination',
       'metric_success_rate_Hallucination'],
      dtype='object')

In [23]:
grouped_df[
    [
        "search_type",
        "avg_score_Answer Relevancy",
        "std_score_Answer Relevancy",
        "avg_score_Contextual Relevancy",
        "std_score_Contextual Relevancy",
        "avg_score_Hallucination",
        "std_score_Hallucination",
    ]
].to_dict()

{'search_type': {0: 'lexical_search_0_hop',
  1: 'lexical_search_1_hop',
  2: 'similarity_search_0_hop',
  3: 'similarity_search_1_hop'},
 'avg_score_Answer Relevancy': {0: 0.9112929143097023,
  1: 0.9537936227443337,
  2: 0.9360564739922749,
  3: 0.8885503894513164},
 'std_score_Answer Relevancy': {0: 0.22695893328153824,
  1: 0.10219077710865027,
  2: 0.19364158543884122,
  3: 0.26392368589665666},
 'avg_score_Contextual Relevancy': {0: 0.7325554553495729,
  1: 0.7613672265085408,
  2: 0.7010646654813596,
  3: 0.7243524585262464},
 'std_score_Contextual Relevancy': {0: 0.31205299217417126,
  1: 0.3089042486203476,
  2: 0.309070361509755,
  3: 0.29515008268039217},
 'avg_score_Hallucination': {0: 0.11824324324324324,
  1: 0.25742574257425743,
  2: 0.1388888888888889,
  3: 0.2616822429906542},
 'std_score_Hallucination': {0: 0.3228239378365471,
  1: 0.43939652585187,
  2: 0.347442816738851,
  3: 0.44161898967345653}}